### ISSUE TITLE
ACL's for ksql - clarification

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluent#101]
Below are few questions from the ksql ACL example
https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/ksql-acls/main.tf

1. **Why isn't the "confluent_api_key" resource being used to assign a key/secret to the service account**?  Instead in the outputs.tf file, the key/secret is being assigned using the confluent CLI? 

2. **Why does the "app-ksql" service account need access to "ALL" ACL, the topics ksql works with**?  This will let this service account read/write from the Kafka topics.  Isn't this dangerous and neglecting ACL's assigned to producers/consumers for this Kafka topic?  (line 294 in the example link above)

Also is there a link to ksql related ACL documentation?  I feel this ksql service account will have unrestricted access to all the Kafka topics it gets assigned to, hence allowing people with access to the service account, free access to all the topics they aren't supposed to have. 

Thanks

**Comment by linouk23** [comment]
Thanks for asking @bluedog13!

> Why isn't the "confluent_api_key" resource being used to assign a key/secret to the service account? Instead in the outputs.tf file, the key/secret is being assigned using the confluent CLI?

That is a temporary limitation since `confluent_api_key` only supports Cloud and Kafka API Keys for now (and not ksqlDB API Keys).

I'll try to find someone who will be able to help with your second & third questions, stay tuned!

**Comment by tolgadur** [comment]
Hey @bluedog13, we added the "ALL" ACL permissions as a shortcut to get ksqlDB up and running in terraform. You are correct that in a production environment you would probably want to have more granular permission for the topics you are using. I will add a comment in the example file clarifying this. Thanks for pointing it out!

**Comment by bluedog13** [comment]
@linouk23 

Going forward, in the future releases of Terraform - will it be possible to deploy the ksql queries directly from Terraform? I am assuming once the feature to generate key/secret for the ksql clusters exists, then the Terraform code can directly read the key/secret and deploy the ksql queries to the ksql cluster? 

Thanks.

**Comment by bluedog13** [comment]
@tolgadur 

To further clarify,  if I already have another producer/consumer/service account which has the read/write or required ACL on the Kafka topics of interest, then there is no need for me to assign any ACL to the ksql related service account right?

From what I understand the "app-ksql" service account (in the examples) is required to interact and deploy ksql queries to ksql cluster mainly?

Thanks.

**Comment by javiervelamindcurv** [comment]
@bluedog13 it isn't need to setup the ACL to ALL. In this link you can check the permissions needed https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/server-config/security/#required-acls

**Comment by tolgadur** [comment]
> Going forward, in the future releases of Terraform - will it be possible to deploy the ksql queries directly from Terraform? 

This is currently not on our roadmap but we are aware that this is wanted. We will try to prioritize this in future.

> To further clarify, if I already have another producer/consumer/service account which has the read/write or required ACL on the Kafka topics of interest, then there is no need for me to assign any ACL to the ksql related service account right?

Yes, I think that's correct.

**Comment by linouk23** [comment]
> Going forward, in the future releases of Terraform - will it be possible to deploy the ksql queries directly from Terraform? I am assuming once the feature to generate key/secret for the ksql clusters exists, then the Terraform code can directly read the key/secret and deploy the ksql queries to the ksql cluster?

Do you want to create a separate issue to track it? @bluedog13

**Comment by bluedog13** [comment]
Thank you for all the answers and clarifications. @linouk23 @tolgadur @javiervelamindcurv 

@linouk23 
I'll create a new ticket to track the deployment of ksql queries via Terraform.

**Comment by linouk23** [comment]
Sounds great @bluedog13! Are there any other questions left with this issue?

**Comment by bluedog13** [comment]
I am good with all the answers provided.  Thanks.
