### ISSUE TITLE
Enable key rotation for confluent_api_key

### ISSUE THREAD

**Issue by afireinside09** [confluentinc/terraform-provider-confluent#102]
Hi there, I have a need for my team to rotate service account API keys on a yearly (or some self-defined time) basis.
Enabling this feature with the `create_before_destroy` lifecycle meta-argument would be 👨‍🍳 💋 
This would largely solve the security mandates my company has surrounding 3rd party api keys.

An example for completeness:
```
resource "confluent_api_key" "team_application_kafka_api_key" {
  for_each = { for project in var.project_list : project.name => project.topic_list }

  display_name = "${each.key}-kafka-api-key"
  description  = "Application Kafka API Key that is owned by the '${each.key}' service account"

  owner {
    id          = confluent_service_account.team_application[each.key].id
    api_version = confluent_service_account.team_application[each.key].api_version
    kind        = confluent_service_account.team_application[each.key].kind
  }

  managed_resource {
    id          = var.cluster_id
    api_version = var.cluster_api_version
    kind        = var.cluster_kind

    environment {
      id = var.environment_id
    }
  }

  enable_key_rotation {
    enabled = true
    rotation_cadence = "1Y" #M(onth), W(eek), D(ay) would be supported
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

**Comment by linouk23** [comment]
Thanks for opening an issue!

I'm afraid it's going to be very challenging to implement with the current API Keys Management API since it returns both API Key ID (`id` attribute) and API Key Secret (`secret` attribute) but I'll ask a backend team to look into it (the way it works for `aws_kms_key` [resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_key#enable_key_rotation)).

As of now, the only supported API Key rotation workflow is:
```
// before
resource "confluent_api_key" "old_kafka_api_key" {
}
------------
// after: step #1
resource "confluent_api_key" "old_kafka_api_key" {
}
resource "confluent_api_key" "new_kafka_api_key" {
}
-------------
// after: step #2
resource "confluent_api_key" "new_kafka_api_key" {
}
```

and

```
// before
resource "confluent_kafka_topic" "orders" {
  ...
  credentials {
    key    = confluent_api_key.old_kafka_api_key
    secret = confluent_api_key.old_kafka_api_key
  }
}
// after: step #2
resource "confluent_kafka_topic" "orders" {
  ...
  credentials {
    key    = confluent_api_key.new_kafka_api_key
    secret = confluent_api_key.new_kafka_api_key
  }
}
```

![image](https://user-images.githubusercontent.com/5459870/189268140-1a66d73e-ec3b-4bea-bcca-e3edf0523e84.png)

**Comment by mcolomerc** [comment]
Workaround:

```
resource` "time_rotating" "rotate" { 
  rotation_days = var.api_key_rotate_days
}

resource "time_static" "rotate" {
  rfc3339 = time_rotating.rotate.rfc3339
}
```
And then trigger the API Key resource recreation with:

```
  lifecycle {
    replace_triggered_by = [ 
        time_static.rotate
    ]
    create_before_destroy = true
  }
```

That will trigger the resource create/delete process after the rotation period.

**Comment by linouk23** [comment]
update: using [this module](https://registry.terraform.io/modules/nerdynick/api-key-rotation/confluent/latest) might help.
