### ISSUE TITLE
how to create end to end automation, confluent cloud organization and login to that org with out opening browser interface.

### ISSUE THREAD

**Issue by Maheshsuthari** [confluentinc/terraform-provider-confluent#103]
I have created terraform org with terraform azapi provider but when use confluent cli command in terraform provisionar it is navigating browser inteferface.

confluent login --no-browser  --organization-id 9e71788d-2cf8-48ff-b4bb-7f567b2ac0d5
Navigate to the following link in your browser to authenticate:

Dow we have any option to login to confluent org wih terrafrom and create resources.

**Comment by linouk23** [comment]
👋 @Maheshsuthari, thanks for opening this issue!

In order to use TF Provider for Confluent there's no expectation that a user would use AzAPI TF Provider, please see out [Getting Started](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project) guide that will help you to create resources on Confluent Cloud in your org. Let me know if that helps!

**Comment by Maheshsuthari** [comment]
But since this is a new organization created with terraform, how would i login to confluent without manual intervineaince  ?
We can create resources with api keys, concern is how we can get cloud api keys with manual effort.

**Comment by linouk23** [comment]
In order to use TF Provider for Confluent a user has to provide a Cloud API Key owned by a user / service account with `OrganizationAdmin` role.

Could you describe your setup in a little bit more detail?

**Comment by Maheshsuthari** [comment]
We are working on entire automation confluent cloud kafka.

1.	Create confluent organization
2.	Login to confluent and generate the cloud Api keys
3.	Create cluster, environment, cluster-apikeys using confluent terraform provider.
4.	Create private endpoints with kafka cluster private link services.

**Comment by linouk23** [comment]
Oh I see, 

nit: A more descriptive way for the 2nd step could be `Login to confluent and generate a service account, assign OrganizationAdmin role to it and then create a Cloud API Key for that service account`

Unfortunately I don't think the first 2 steps is something that is directly related to the source code of TF Provider for Confluent so you might want to contact Confluent Support to figure out a solution for it.
