### ISSUE TITLE
Error when ksql cluster status is Provisioning 

### ISSUE THREAD

**Issue by javiervelamindcurv** [confluentinc/terraform-provider-confluent#106]
If you deploy a ksql cluster and you apply again the changes, terraform confluent module will try again create the cluster and you get an error:

` Error: error creating ksqlDB Cluster "": 400 Bad Request: failed to create API key for KSQL healthcheck: user id or user resource id must be provided to create a key`

The module must control the status of the cluster when you try apply the changes.

Now there are two ksql cluster with the same name in 'Provisiong' status.

![image](https://user-images.githubusercontent.com/102152403/189861186-e0f4ece1-4ae0-4706-84a5-09d5770ce196.png)

**Comment by de1et3d** [comment]
Facing the same issue even if there is no existing ksql cluster in place. Terraform fails with exactly the same 400 error but UI shows cluster is being provisioned. A week ago everything worked properly. We use the version 1.3.0 if it makes sense.

**Comment by linouk23** [comment]
@javiervelamindcurv @de1et3d thanks for reporting a bug! We're aware of this backend issue and our backend team is working on a fix.

**Comment by linouk23** [comment]
I was told our backend team has fixed the issue. Could you try again @javiervelamindcurv @de1et3d?

**Comment by linouk23** [comment]
I tried again and it seems to work for me now so I'm closing this issue.
