### ISSUE TITLE
Setup Visual Studio Dev Containers to be more easy to develop the module.

### ISSUE THREAD

**Issue by javiervelamindcurv** [confluentinc/terraform-provider-confluent#107]
It could be great Visual Studio Dev Containers to be more easy to develop the module.

https://code.visualstudio.com/docs/remote/containers

**Comment by linouk23** [comment]
Thanks for the suggestion @javiervelamindcurv! Could you add an example / a little bit more details how you can think _Visual Studio Dev Containers_ can be used with TF Provider for Confluent?

**Comment by javiervelamindcurv** [comment]
Now if you want develop the provider you need install some requirements: https://github.com/confluentinc/terraform-provider-confluent/blob/master/docs/DEVELOPING.md

If you add Visual Studio Dev Containers to the repository any developer can clone the repository and start working with the code without installing any requirements. Also if tomorrow you add  new tools to develop the provider you don't need to update your computer, you will download new tools when you pull the branch.

**Comment by linouk23** [comment]
Sounds like a great idea! 

> If you add Visual Studio Dev Containers 

Is there a button I could click to enable it? I read [this doc](https://code.visualstudio.com/docs/remote/containers) but it wasn't super clear how to enable it for this repo.

**Comment by linouk23** [comment]
@FloBeji this issue was [resolved](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1400-april-26-2023) in our latest 1.40.0 release.
