### ISSUE TITLE
confluent_network.private-link.azure[0].private_link_service_aliases is a map of string, known only after apply

### ISSUE THREAD

**Issue by Maheshsuthari** [confluentinc/terraform-provider-confluent#108]
Below is the my terraform resource and trying to create private endpoint based on the private-link aliaces, but i am not able to do that since throwing error below error.

**╷
│ Error: Invalid for_each argument
│
│   on privatelink.tf line 172, in resource "azurerm_private_endpoint" "endpoint":
│  172:   for_each = confluent_network.private-link.azure[0].private_link_service_aliases
│     ├────────────────
│     │ confluent_network.private-link.azure[0].private_link_service_aliases is a map of string, known only after apply
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources
│ that the for_each depends on.**

<
resource "azurerm_private_endpoint" "endpoint" {
  for_each = confluent_network.private-link.azure[0].private_link_service_aliases

  name                = "confluent-${local.network_id}-${each.key}"
  location            = var.region
  resource_group_name = data.azurerm_resource_group.rg.name

  subnet_id = data.azurerm_subnet.subnet[each.key].id

  private_service_connection {
    name                              = "confluent-${local.network_id}-${each.key}"
    is_manual_connection              = true
    private_connection_resource_alias = each.value
    request_message                   = "PL"
  }
  depends_on = [ confluent_network.private-link ]
}
``>>

**Comment by linouk23** [comment]
Thanks for opening an issue @Maheshsuthari!

See step #2 from [README](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/dedicated-privatelink-azure-kafka-acls/README.md):

```
Apply Terraform configuration in 2 steps:

# Creates an environment and a network
terraform apply -target=confluent_network.private-link

# Creates others resources (except already created environment and network) declared in main.tf
terraform apply
```

Going forward, we'll update the docs to make it more clear:
![image](https://user-images.githubusercontent.com/5459870/190493533-f59f7ed0-ea18-4b90-989e-7c73654c070f.png)
