### ISSUE TITLE
Inconsistent configuration properties names for aws credentials

### ISSUE THREAD

**Issue by Schekn** [confluentinc/terraform-provider-confluent#110]
TF provider uses inconsistent names for the AWS key/secret pairs.
For example
Kinesis source
```
aws.access.key.id
aws.secret.key.id
```
S3 source
```
aws.access.key.id
aws.secret.access.key
```

**Comment by linouk23** [comment]
@Schekn thanks for reporting an issue!

Unfortunately it's not something that can be fixed in a client but I'll pass this to our backend team to update our [Connect API](https://docs.confluent.io/cloud/current/api.html#tag/Connectors-(v1)).
