### ISSUE TITLE
Error creating Role Binding: 400 Bad Request

### ISSUE THREAD

**Issue by JWDobken** [confluentinc/terraform-provider-confluent#111]
I try to create a service account that can read from specific topics with a role binding to my cluster `confluent_kafka_cluster.cluster.rbac_crn` with the [Confluent cloud provider](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs):

```tf
resource "confluent_service_account" "team-read-sa" {
  display_name = "myteam_sa"
  description  = "Service Account for my team"
}

resource "confluent_role_binding" "team-read-sa" {
  principal   = "User:${confluent_service_account.team-read-sa.id}"
  role_name   = "DeveloperRead"
  crn_pattern = confluent_kafka_cluster.cluster.rbac_crn
}
```

But when applied, it gives:

> Error: error creating Role Binding: 400 Bad Request
> 
> with module.confluent-kafka.confluent_role_binding.team-read-sa,
> on service_accounts.tf line 7, in resource "confluent_role_binding" "team-read-sa":
> 7: resource "confluent_role_binding" "team-read-sa" {

I have also tried to reconstruct [the API call](https://docs.confluent.io/cloud/current/api.html#tag/Role-Bindings-(iamv2)/operation/createIamV2RoleBinding):

```bash
curl --request POST \
  --url https://api.confluent.cloud/iam/v2/role-bindings \
  --header 'Authorization: Basic AUTHKEY' \
  --header 'content-type: application/json' \
  --data '{"principal":"User:u-111aaa","role_name":"DeveloperRead","crn_pattern":"crn://confluent.cloud/organization=1111aaaa-11aa-11aa-11aa-111111aaaaaa/environment=t-38nbaz/cloud-cluster=lkc-1111aaa"}'
```

which also gives a non-verbose answer:

```json
{'errors': [{
    'id': 'ef1f324fe11519ade95790167479c066',
   'status': '400',
   'code': 'bad_request',
   'detail': 'Bad Request',
   'source': {}
}]}
```

**Comment by JWDobken** [comment]
Changed the crn to `crn_pattern = "${confluent_kafka_cluster.cluster.rbac_crn}/topic=my-topic"` but now I get:

> Error: error creating Role Binding: 403 Forbidden: Forbidden - Basic Clusters can not use resource roles

**Comment by linouk23** [comment]
👋  @JWDobken, thanks for creating an issue!

There's #21 for showing a descriptive error messages with RBAC API.

Speaking about your request 
> service account that can read from specific topics with a role binding to my cluster

it sounds like you're interested in creating the following (see the difference in your value for `crn_pattern` attribute and the ones listed here):
```
// Note that in order to consume from a topic, the principal of the consumer ('app-consumer' service account)
// needs to be authorized to perform 'READ' operation on both Topic and Group resources:
resource "confluent_role_binding" "app-producer-developer-read-from-topic" {
  principal   = "User:${confluent_service_account.app-consumer.id}"
  role_name   = "DeveloperRead"
  crn_pattern = "${confluent_kafka_cluster.standard.rbac_crn}/kafka=${confluent_kafka_cluster.standard.id}/topic=${confluent_kafka_topic.orders.topic_name}"
}

resource "confluent_role_binding" "app-producer-developer-read-from-group" {
  principal = "User:${confluent_service_account.app-consumer.id}"
  role_name = "DeveloperRead"
  // The existing value of crn_pattern's suffix (group=confluent_cli_consumer_*) are set up to match Confluent CLI's default consumer group ID ("confluent_cli_consumer_<uuid>").
  // https://docs.confluent.io/confluent-cli/current/command-reference/kafka/topic/confluent_kafka_topic_consume.html
  // Update it to match your target consumer group ID.
  crn_pattern = "${confluent_kafka_cluster.standard.rbac_crn}/kafka=${confluent_kafka_cluster.standard.id}/group=confluent_cli_consumer_*"
}
```

See 
* [standartd-kafka-rbac example](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/standard-kafka-rbac/main.tf)
* [confluent_role_binding doc](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_role_binding)
for more details.

Let me know if that helps!

**Comment by JWDobken** [comment]
I cannot create resource roles on our DEV cluster:

> Error: error creating Role Binding: 403 Forbidden: Forbidden - Basic Clusters can not use 

So I try to create a `ClusterAdmin` role instead on the cluster level:

```
resource "confluent_role_binding" "team-read-sa" {
  principal   = "User:${confluent_service_account.team-read-sa.id}"
  role_name   = "ClusterAdmin"
  crn_pattern = confluent_kafka_cluster.cluster.rbac_crn
}
```

which gives the non-verbose `Error: error creating Role Binding: 400 Bad Request`

**Comment by JWDobken** [comment]
changed `ClusterAdmin` to `CloudClusterAdmin` solved the issue
