### ISSUE TITLE
Error: error creating Kafka ACLs: 403 Forbidden

### ISSUE THREAD

**Issue by JWDobken** [confluentinc/terraform-provider-confluent#112]
while creating a ACL:

```tf
resource "confluent_kafka_acl" "team-read-consumer-group" {
  kafka_cluster {
    id = confluent_kafka_cluster.cluster.id
  }
  resource_type = "GROUP"
  resource_name = "read-account"
  pattern_type  = "PREFIXED"
  principal     = "User:sa-xxxxxx"
  host          = "*"
  operation     = "READ"
  permission    = "ALLOW"
  rest_endpoint = confluent_kafka_cluster.cluster.rest_endpoint
  credentials {
    key    = confluent_api_key.team-read-api-key.id
    secret = confluent_api_key.team-read-api-key.secret
  }
}
```

It returns the following error:

```logs
│ Error: error creating Kafka ACLs: 403 Forbidden
│ 
│   with module.confluent-kafka.confluent_kafka_acl.team-read-consumer-group,
│   on service_accounts.tf line 47, in resource "confluent_kafka_acl" "team-read-consumer-group":
│   47: resource "confluent_kafka_acl" "team-read-consumer-group" {
```

## confluent

The equivalent of the confluent CLI works just fine:

```cmd
$ confluent kafka acl create \
    --operation read \
    --principal User:sa-xxxxxx \
    --allow \
    --consumer-group read-account \
    --prefix \
    --cluster lkc-xxxxx \
    --environment env-xxxxx
    Principal    | Permission | Operation | Resource Type | Resource Name | Pattern Type  
-----------------+------------+-----------+---------------+---------------+---------------
  User:sa-xxxxxx | ALLOW      | READ      | GROUP         | read-account  | PREFIXED    
```

**Comment by JWDobken** [comment]
If relevant, when I set:

```cmd
export TF_LOG=trace
export TF_LOG_PATH="./logs.txt"
```

I can see from the logs that the principal has been replaced by a number:

```json
{
    "resource_type": "GROUP",
    "resource_name": "kafka-group",
    "pattern_type": "LITERAL",
    "principal": "User:876543",
    "host": "*",
    "operation": "DESCRIBE",
    "permission": "ALLOW",
}```

**Comment by linouk23** [comment]
@JWDobken thanks for creating an issue!

Could you check that the owner of `confluent_api_key.team-read-api-key` has a sufficient role to create ACLs? For example, `CloudClusterAdmin`. See [basic-kafka-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/basic-kafka-acls) as an example.

Let me know if that helps.

**Comment by JWDobken** [comment]
Thank you @linouk23; fixed it by adding a `depends_on`:

```tf
resource "confluent_kafka_acl" "team-read-consumer-group" {
  ...
  depends_on = [
    confluent_role_binding.team-read-sa
  ]
}

**Comment by apurv-jay** [comment]
when i am using this on basic cluster its showing this error 
<img width="797" alt="Screenshot 2023-06-21 at 3 13 48 PM" src="https://github.com/confluentinc/terraform-provider-confluent/assets/83883023/1aa83225-8585-4406-80bc-8b2d8f0ec0b0">

**Comment by linouk23** [comment]
AFAK only a subset of [roles](https://docs.confluent.io/cloud/current/access-management/access-control/cloud-rbac.html) is supported for _Basic_ Kafka clusters (and Standard supports all of them) but you might want to double check with our support as it doesn't seem to be an issue with TF Provider. @apurv-jay

**Comment by apurv-jay** [comment]
so you mean to say that Topic rolebindings are not available for Basic clusters. but they are availabe for standard and dedicated clusters topic.
