### ISSUE TITLE
Terraform destroy and import -  Errors: 401 and 403 Unauthorized: Unauthorized

### ISSUE THREAD

**Issue by rogerioefonseca** [confluentinc/terraform-provider-confluent#115]
Hello there,
While trying to destroy a module that I created with my confluent Kafka code, I received 401 unauthorized error:
![image](https://user-images.githubusercontent.com/17765109/194586509-2e35cfaa-cd95-4e7c-84b8-e8d56a37a025.png)

Code used:
```
module "confluentcloud_kafka_cluster" {
  source                         = "git::git@referece"
  application_name        = "testing"
  type                             = "dedicated"
  azure_keyvault_name  = azurerm_key_vault.this.name
  subnet_name               = "test"
  virtual_network_name = azurerm_subnet.this.virtual_network_name
  resource_group_name = data.azurerm_resource_group.this.name
  subnet_rg_name          = "example"
}
```

I noticed another similar error related to authorization as well while trying to import a resource:
![image](https://user-images.githubusercontent.com/17765109/194590466-1e0e332a-5638-4e18-bc21-382c511ee6d5.png)

I do not have more details, it was working before, and I could be wrong, but looks like a backend error.
Can you please help me with that

**Comment by rogerioefonseca** [comment]
> Hello there, While trying to destroy a module that I created with my confluent Kafka code, I received 401 unauthorized error: ![image](https://user-images.githubusercontent.com/17765109/194586509-2e35cfaa-cd95-4e7c-84b8-e8d56a37a025.png)
> 
> Code used:
> 
> ```
> module "confluentcloud_kafka_cluster" {
>   source                         = "git::git@referece"
>   application_name        = "testing"
>   type                             = "dedicated"
>   azure_keyvault_name  = azurerm_key_vault.this.name
>   subnet_name               = "test"
>   virtual_network_name = azurerm_subnet.this.virtual_network_name
>   resource_group_name = data.azurerm_resource_group.this.name
>   subnet_rg_name          = "example"
> }
> ```
> 
> I noticed another similar error related to authorization as well while trying to import a resource: ![image](https://user-images.githubusercontent.com/17765109/194590466-1e0e332a-5638-4e18-bc21-382c511ee6d5.png)
> 
> I do not have more details, it was working before, and I could be wrong, but looks like a backend error. Can you please help me with that

I increased the TF to TRACE and then I was able to see some more details of the error:
![image](https://user-images.githubusercontent.com/17765109/194592856-b8281cca-ab79-402e-9906-b961d03adc06.png)

**Comment by linouk23** [comment]
👋 @rogerioefonseca, thanks for creating the issue!

That looks interesting, it looks like the latest change to [resource_environment.go](https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/resource_environment.go) file was 4 months ago.

![image](https://user-images.githubusercontent.com/5459870/194692628-2778aebd-0e0b-4058-b45a-eee28d660844.png)

> I noticed another similar error related to authorization as well while trying to import a resource

1. Could you confirm that you tried to import an environment by following [our guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_environment#import)?

![image](https://user-images.githubusercontent.com/5459870/194692687-4f792481-2977-4717-bb1e-f77af2c81fe2.png)

2. _403_ might also mean there's no environment with such an ID (i.e., it's kinda like 404) or your Cloud API Key might not have enough access to read it. 

3. It might also be a good idea to check whether your Cloud API Key that you're using is still active (and was not deleted by someone else as a part of key rotation or something).

Let me know if it helps!

**Comment by linouk23** [comment]
@rogerioefonseca I'm closing this issue but feel free to let me know if my comment above didn't help to resolve the issue.

**Comment by rogerioefonseca** [comment]
> @rogerioefonseca I'm closing this issue but feel free to let me know if my comment above didn't help to resolve the issue.

Sure, sorry about the lack of reply.
I believe it was a one-time issue, because after recreating the cluster it worked as expected, BTW I double-checked the points that you mentioned, and it was all fine, I was not able to find problems related to API or granting,
Thanks for the support
