### ISSUE TITLE
RBAC for Managed Connectors

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluent#116]
Does Terraform support RBAC for Confluent managed connectors? I did not come across any examples indicating the same. 

Thanks.

**Comment by linouk23** [comment]
👋 @bluedog13, thanks for creating this issue!

It does, see [this message](https://github.com/confluentinc/terraform-provider-confluent/issues/93#issuecomment-1256581770) for more details.

We did include an example in our docs: 
![image](https://user-images.githubusercontent.com/5459870/195207601-b21a7417-ca98-4d46-ba96-f01e1924a8d7.png)
but correct, at some point we might want to add a separate example to our `configuration/examples` folder.

Let me know if that helps!
