### ISSUE TITLE
Avoid Recreation of API keys & Secret while upgrading confluent terraform provider version (0.5.0 -> 0.7.0)

### ISSUE THREAD

**Issue by SukantArora** [confluentinc/terraform-provider-confluent#117]
While upgrading confluent terraform provider version from 0.5.0 to 0.7.0, We're adding `confluent_api_key` resource to avoid manual creation of keys & secrets.

`Current Scenario`:
We already have API keys & Secret for existing service accounts.

`After Upgrading terraform provider version`:
It's adding confluent_api_key resource i.e creating API keys & secret for existing service accounts. 

`Queries`: 
-  Is this expected behaviour while upgrading provider version
-  Is there any way we can avoid recreation of API keys & secret for already created service accounts,
-  Also can we limit creation of API key & secret for a service account.

**Comment by linouk23** [comment]
👋 @SukantArora thanks for creating an issue!

In general, we'd very much recommend updating to the latest version of TF Provider (`1.7.0`) as soon as possible or at least to `1.0.0` (which is the first version that is recommended for using in production).

Speaking about migration to `0.7.0`, did you see https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.7.0 already?

**Comment by SukantArora** [comment]
@linouk23, We are planning to update to latest version (`1.7.0`) eventually, We referred the same doc which you mentioned for upgrading our confluent terraform provider version.

We are upgrading confluent terraform provider version in our existing environment, which have service accounts & topics already, we want to avoid recreation of API keys & secret for it.

It would be great if you can help us with this and also questions asked in my above comment.

Thank You!

**Comment by linouk23** [comment]
Sounds great!

Could you list your TF configuration before & after? It's not super clear to me why TF Provider attempts to create new API Keys.

If you want to import existing API Keys into TF configuration it might be a good idea to [import](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_api_key#import) them one by one.

**Comment by SukantArora** [comment]
[previous.txt](https://github.com/confluentinc/terraform-provider-confluent/files/9784388/previous.txt)
[current.txt](https://github.com/confluentinc/terraform-provider-confluent/files/9784389/current.txt)

I have attached both the files, we only have added `confluent_api_key' resource in the current.

For importing API keys , but there is no resource `confluent_api_key' for previously created service accounts, I couldn't get how can I import that.
Can you please explain.

**Comment by linouk23** [comment]
Sure, so I'm not too familiar how importing works with `for_each` but if you get rid of it and introduce separate resources for each _topic_ the importing flow would work as following:
1. Declare new `confluent_api_key. app_consumer_kafka_api_key_1` (it's almost done in current.txt -- you only need to remove `for_each` now).
2. Follow [import](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_api_key#import) doc.
3. Running `terraform plan` should show 0 changes.

By the way, here's an example for _[Importing into Resource configured with for_each](https://www.terraform.io/cli/commands/import#example-import-into-resource-configured-with-for_each)_ that might be helpful.

Let me know if that helps!

**Comment by SukantArora** [comment]
Hi @linouk23, Thank You!
I'm able to import `confluent_api_key` resource, but I have to do it one by one for each key, and we are having around 100 API keys & Secret, and that too in each environment ( STG, PERF, PROD )

Is there any way we can import multiple `confluent_api_key` resources at once. some kind of a loop, or scripts where we can enter API secrets for all the API keys we can import.

**Comment by linouk23** [comment]
That's great to hear!

Could you create a separate issue for that (something like "How to import lots of resources at once?") and resolve this one?

There're some plans about launching a script that would allow a user to import their existing CC infrastructure to TF but for now you might have to write your own scripting tool or something.

**Comment by SukantArora** [comment]
Got It, Thanks for the support!
