### ISSUE TITLE
Topic creation appears fundamentally broken

### ISSUE THREAD

**Issue by christophermaier** [confluentinc/terraform-provider-confluent#121]
I'm trying to create a new topic using the Terraform provider.

I have read the advisories about the topic configuration values that aren't editable after topic creation. However, it appears that you can't even edit those values when you *create* the topic, and that any of those overridden defaults that remain in your resource definition trigger subsequent updates that can never succeed.

As long as you don't want to change any configuration values, it seems that you can create a topic; as soon as you want to customize the configuration, however, things begin to break.

Here is a minimal Terraform program that illustrates this:

```terraform
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.8.0"
    }
  }
}

variable "kafka_cluster_id" {
  type        = string
}

# Must set all of the following environment variables:
# - CONFLUENT_CLOUD_API_KEY
# - CONFLUENT_CLOUD_API_SECRET
# - KAFKA_REST_ENDPOINT
# - KAFKA_API_KEY
# - KAFKA_API_SECRET
provider "confluent" {}

resource "confluent_kafka_topic" "testing-topic" {
  kafka_cluster {
    id = var.kafka_cluster_id
  }
  topic_name         = "testing-topic"
  partitions_count   = 6
  config = {
    "cleanup.policy" = "delete"
    # NOTE: This is overridden from the default value of 'producer'
    "compression.type" = "zstd"
    "connection.failed.authentication.delay.ms" = "5000"
    "default.replication.factor" = "3"
    "delete.retention.ms" = "86400000"
    "file.delete.delay.ms" = "60000"
    "flush.messages" = "9223372036854775807"
    "flush.ms" = "9223372036854775807"
    "group.max.session.timeout.ms" = "1200000"
    "index.interval.bytes" = "4096"
    "max.compaction.lag.ms" = "9223372036854775807"
    "max.message.bytes" = "2097164"
    "max.downconversion.enable" = "true"
    "message.format.version" = "3.0-IV1"
    "message.timestamp.difference.max.ms" = "9223372036854775807"
    "message.timestamp.type" = "CreateTime"
    "min.cleanable.dirty.ratio" = "0.5"
    "min.compaction.lag.ms" = "0"
    "min.insync.replicas" = "2"
    "offsets.retention.minutes" = "10080"
    "preallocate" = "false"
    "retention.bytes" = "-1"
    "retention.ms" = "604800000"
    "segment.bytes" = "104857600"
    "segment.index.bytes" = "10485760"
    "segment.jitter.ms" = "0"
    "segment.ms" = "604800000"
    "unclean.leader.election.enable" = "false"
  }
}
```
Some important things to note:
- I'm specifying configuration values for pretty much all variables for a topic, including ones that are editable after topic creation, and ones that are *not* editable after topic creation.
- Everything is the default value except for `compression.type` which has been changed to `zstd` from the default of `producer`.

Saved to a `main.tf` file, it can be run as follows:
```
CONFLUENT_CLOUD_API_KEY="..." \
CONFLUENT_CLOUD_API_SECRET="..." \
KAFKA_REST_ENDPOINT="..." \
KAFKA_API_KEY="..." \
KAFKA_API_SECRET="..." \
TF_VAR_kafka_cluster_id="lkc-XXXXX" \
terraform apply
```
Here is the output of that first `terraform apply`:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # confluent_kafka_topic.testing-2 will be created
  + resource "confluent_kafka_topic" "testing-topic" {
      + config           = {
          + "cleanup.policy"                            = "delete"
          + "compression.type"                          = "zstd"
          + "connection.failed.authentication.delay.ms" = "5000"
          + "default.replication.factor"                = "3"
          + "delete.retention.ms"                       = "86400000"
          + "file.delete.delay.ms"                      = "60000"
          + "flush.messages"                            = "9223372036854775807"
          + "flush.ms"                                  = "9223372036854775807"
          + "group.max.session.timeout.ms"              = "1200000"
          + "index.interval.bytes"                      = "4096"
          + "max.compaction.lag.ms"                     = "9223372036854775807"
          + "max.downconversion.enable"                 = "true"
          + "max.message.bytes"                         = "2097164"
          + "message.format.version"                    = "3.0-IV1"
          + "message.timestamp.difference.max.ms"       = "9223372036854775807"
          + "message.timestamp.type"                    = "CreateTime"
          + "min.cleanable.dirty.ratio"                 = "0.5"
          + "min.compaction.lag.ms"                     = "0"
          + "min.insync.replicas"                       = "2"
          + "offsets.retention.minutes"                 = "10080"
          + "preallocate"                               = "false"
          + "retention.bytes"                           = "-1"
          + "retention.ms"                              = "604800000"
          + "segment.bytes"                             = "104857600"
          + "segment.index.bytes"                       = "10485760"
          + "segment.jitter.ms"                         = "0"
          + "segment.ms"                                = "604800000"
          + "unclean.leader.election.enable"            = "false"
        }
      + id               = (known after apply)
      + partitions_count = 4
      + topic_name       = "testing-topic"

      + kafka_cluster {
          + id = "lkc-XXXXXX"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

confluent_kafka_topic.testing-topic: Creating...
confluent_kafka_topic.testing-topic: Still creating... [10s elapsed]
confluent_kafka_topic.testing-topic: Creation complete after 11s [id=lkc-XXXXXX/testing-topic]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

The initial `terraform apply` run succeeds, but the configuration values are not honored. In particular, the topic is created with a `compression.type` of `producer`, *not* `zstd`, as was specified. 

This can be seen in the Confluent Cloud SaaS UI as well as via the REST API:

```json
{
  "kind": "KafkaTopicConfig",
  "metadata": {
    "self": "https://pkc-XXXXX.region.aws.confluent.cloud/kafka/v3/clusters/lkc-XXXXXX/topics/testing-topic/configs/compression.type",
    "resource_name": "crn:///kafka=lkc-XXXXXX/topic=testing-topic/config=compression.type"
  },
  "cluster_id": "lkc-XXXXXX",
  "name": "compression.type",
  "value": "producer",                          # <-- This should be "zstd"
  "is_read_only": true,
  "is_sensitive": false,
  "source": "DEFAULT_CONFIG",
  "synonyms": [
    {
      "name": "compression.type",
      "value": "producer",
      "source": "DEFAULT_CONFIG"
    }
  ],
  "topic_name": "testing-topic",
  "is_default": true
}
```

Subsequent `terraform apply` runs mark the topic resource as needing an update. All the updates are for the non-editable configuration values, even though they haven't changed their values.

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # confluent_kafka_topic.testing-topic will be updated in-place
  ~ resource "confluent_kafka_topic" "testing-topic" {
      ~ config           = {
          + "compression.type"                          = "zstd"
          + "connection.failed.authentication.delay.ms" = "5000"
          + "default.replication.factor"                = "3"
          + "file.delete.delay.ms"                      = "60000"
          + "flush.messages"                            = "9223372036854775807"
          + "flush.ms"                                  = "9223372036854775807"
          + "group.max.session.timeout.ms"              = "1200000"
          + "index.interval.bytes"                      = "4096"
          + "max.downconversion.enable"                 = "true"
          + "message.format.version"                    = "3.0-IV1"
          + "min.cleanable.dirty.ratio"                 = "0.5"
          + "offsets.retention.minutes"                 = "10080"
          + "preallocate"                               = "false"
          + "segment.index.bytes"                       = "10485760"
          + "segment.jitter.ms"                         = "0"
          + "unclean.leader.election.enable"            = "false"
            # (12 unchanged elements hidden)
        }
        id               = "lkc-XXXXXX/testing-topic"
        # (2 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

confluent_kafka_topic.testing-topic: Modifying... [id=lkc-XXXXXX/testing-topic]
╷
│ Error: error updating Kafka Topic "lkc-XXXXXX/testing-topic": "offsets.retention.minutes" topic setting is read-only and cannot be updated. Read https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic for more details.
│
│   with confluent_kafka_topic.testing-topic,
│   on main.tf line 32, in resource "confluent_kafka_topic" "testing-topic":
│   32: resource "confluent_kafka_topic" "testing-topic" {
│
```
Have I missed something fundamental here, or can you not use this provider to create topics with modified configurations?

Thanks :pray:

**Comment by linouk23** [comment]
👋 thanks for creating this issue and writing such a detailed summary!

I think [our docs](https://docs.confluent.io/cloud/current/clusters/broker-config.html#custom-topic-settings-for-all-cluster-types) are a little bit unclear and they don't specify which topic settings can be specified on `CREATE` and the assumption a reader might have is as long as the topic setting is listed in that table, one could override its value on `CREATE` which is not totally accurate.

To specifically answer your question, `compression.type` is a read-only topic setting that can't be overriden during `CREATE` or after. To make things a little bit worse, there're some gotchas with Kafka REST API and it returns `201` even though ideally it'd have returned `400` with a descriptive error messages like `X topic setting can't be set on CREATE`. There's an internal ticket `FF-4417` to support custom values on CREATE / updates for `compression.type`.

The following list of setting topic can't set on CREATE either (FWIW most of them are marked `editable: no` in that table):
* "connection.failed.authentication.delay.ms"      
* "default.replication.factor"               
* "file.delete.delay.ms"                     
* "flush.messages"                           
* "flush.ms"                                 
* "group.max.session.timeout.ms"             
* "index.interval.bytes"                     
* "max.downconversion.enable"                
* "message.format.version"                   
* "min.cleanable.dirty.ratio"                
* "offsets.retention.minutes"                
* "preallocate"                              
* "segment.index.bytes"                      
* "segment.jitter.ms"                        
* "unclean.leader.election.enable"           
* "compression.type"                   

> I'm specifying configuration values for pretty much all variables for a topic, including ones that are editable after topic creation, and ones that are not editable after topic creation.

However for others topic settings updates (on CREATE and after) are actually supported for _editable_ topic settings: for example, you can try to use:
```
resource "confluent_kafka_topic" "orders" {
  kafka_cluster {
    id = "lkc-y62rg7"
  }
  topic_name    = "orders"

  # https://docs.confluent.io/cloud/current/clusters/broker-config.html#custom-topic-settings-for-all-cluster-types
  config = {
    # NOTE: This is overridden from the default value of 'delete'
    "cleanup.policy"   = "compact"
    # NOTE: Overriding segment.ms to the default value:
    "segment.ms"       = "604800000"
    # NOTE: Overriding retention.ms to a custom value:
    "retention.ms"     = "604800001"
  }
}
```
and then you could run `terraform plan` with:
```
$ terraform plan
confluent_kafka_topic.orders: Refreshing state... [id=lkc-y62rg7/orders]

No changes. Your infrastructure matches the configuration.
```

For readability I'd also recommend not to list topic settings unless you want them to be set to a custom value.

Let me know if it helps / makes sense at all!

**Comment by linouk23** [comment]
cc @christophermaier ⬆️

**Comment by christophermaier** [comment]
@linouk23 This is very much a documentation issue, then. Calling something a configuration value when it can't be changed at all, even at topic creation time, is needlessly confusing. If I see something described as "configuration", it is entirely reasonable to think that I can actually configure it.

I'm glad that work is underway to enable changing these values, but until that capability is ready, I don't see the use of the documentation even mentioning them, let alone going to such lengths to make distinctions between what a user can and cannot edit.

**Comment by linouk23** [comment]
Thanks for the feedback @christophermaier! We're working on updating [docs](https://docs.confluent.io/cloud/current/clusters/broker-config.html#custom-topic-settings-for-all-cluster-types) to split `Editable` column into `Editable on Create` and `Editable after Create` columns.

> I don't see the use of the documentation even mentioning them, let alone going to such lengths to make distinctions between what a user can and cannot edit.

Do you think it'll helpful to delete topic settings that have `No` as a value for both `Editable on Create` and `Editable after Create`  columns?

**Comment by christophermaier** [comment]
> Do you think it'll helpful to delete topic settings that have `No` as a value for both `Editable on Create` and `Editable after Create` columns?

@linouk23 That depends on what operators or users can do with that knowledge. Is there any benefit to knowing about an internal detail that you can't change? Maybe it's good information to know, in order to have a better understanding of how the system works, so you can better reason about things when you're trying to, say, debug something. Maybe it's not useful to know.

In any event, I don't think having that information in a section about _configuration_ is useful, because _it can't be configured_.

(Creating separate columns in the documentation for `Editable on Create` and `Editable after Create` is a great idea, however!)

**Comment by linouk23** [comment]
I'm closing this PR since we updated the docs, see https://docs.confluent.io/cloud/current/clusters/broker-config.html#custom-topic-settings-for-all-cluster-types-supported-by-kafka-rest-api-and-terraform-provider

We'll update TF docs accordingly in our next release of TF Provider.
