### ISSUE TITLE
Unable to configure a provider using a confluent_api_key resource.

### ISSUE THREAD

**Issue by pichouk** [confluentinc/terraform-provider-confluent#122]
Hi,

I have the following (simplified) Terraform code

```
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.8.0"
    }
  }
  required_version = ">= 1.0.3"
}

provider "confluent" {}

provider "confluent" {
  alias = "kafka"

  kafka_rest_endpoint = confluent_kafka_cluster.kafka.rest_endpoint
  kafka_api_key       = confluent_api_key.kafka_provider.id
  kafka_api_secret    = confluent_api_key.kafka_provider.secret
}

resource "confluent_kafka_cluster" "kafka" {
  display_name = "${var.namespace}-${var.environment}-kafka"
  [... CONFIG ...]
  basic {}
}

resource "confluent_api_key" "kafka_provider" {
  display_name = "terraform-provider-kafka-api-key"
  description  = "Terraform provider access for Kafka"

  owner {
    [... CONFIG ...]
  }

  managed_resource {
    id          = confluent_kafka_cluster.kafka.id
    api_version = confluent_kafka_cluster.kafka.api_version
    kind        = confluent_kafka_cluster.kafka.kind

    environment {
      id = confluent_environment.ccloud.id
    }
  }
}
```

What I'm trying to achieve is to create some resources using the `confluent` provider, and create some topics (I only have one cluster) using the `confluent.kafka` provider. In this setup, the `confluent` provider create the Kafka Cluster API key used for the `confluent.kafka` provider.

But when I run `terraform plan` I have this error : 
```
confluent_api_key.kafka_provider: Refreshing state... [id=XXXXXXXXXXX]
╷
│ Error: All 3 kafka_api_key, kafka_api_secret, kafka_rest_endpoint attributes should be set or not set in the provider block at the same time
│ 
│   with provider["registry.terraform.io/confluentinc/confluent"].kafka,
│   on _provider.tf line 13, in provider "confluent":
│   13: provider "confluent" {
```

If I hardcoded the values for `kafka_api_key` and `kafka_api_secret` in the provider, then it works. I don't know why I have this error message, I don't think it is a Terraform limitation because I do the same kind of things with other providers.

Any idea ? Is that a "bug" ?

**Comment by linouk23** [comment]
Thanks for creating this issue @pichouk!

That's a very interesting idea!

First things first, could you double check you [provided](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs#example-usage) Cloud API Key & Cloud API Secret to TF Provider as well?
```
# Option #1 when managing multiple clusters in the same Terraform workspace
provider "confluent" {
  cloud_api_key    = var.confluent_cloud_api_key    # optionally use CONFLUENT_CLOUD_API_KEY env var
  cloud_api_secret = var.confluent_cloud_api_secret # optionally use CONFLUENT_CLOUD_API_SECRET env var
}

# Option #2 when managing a single cluster in the same Terraform workspace
# See https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/managing-single-cluster for more details
provider "confluent" {
  cloud_api_key       = var.confluent_cloud_api_key    # optionally use CONFLUENT_CLOUD_API_KEY env var
  cloud_api_secret    = var.confluent_cloud_api_secret # optionally use CONFLUENT_CLOUD_API_SECRET env var

  kafka_rest_endpoint = var.kafka_rest_endpoint        # optionally use KAFKA_REST_ENDPOINT env var 
  kafka_api_key       = var.kafka_api_key              # optionally use KAFKA_API_KEY env var
  kafka_api_secret    = var.kafka_api_secret           # optionally use KAFKA_API_SECRET env var
}
```


Also you might want to update
```
kafka_api_secret    = confluent_api_key.kafka_provider.id
->
kafka_api_secret    = confluent_api_key.kafka_provider.secret
```

**Comment by pichouk** [comment]
Hi @linouk23 
Sorry I made a mistake will copying my code, I actually use `confluent_api_key.kafka_provider.secret` for the key (I edited my original post).

Also I have correctly set `CONFLUENT_CLOUD_API_KEY` and `CONFLUENT_CLOUD_API_SECRET ` env variables. The first provider is working fine, I know it because the API key have been created and is in my state :

```
$ terraform state show confluent_api_key.kafka_provider
# confluent_api_key.kafka_provider:
resource "confluent_api_key" "kafka_provider" {
    description            = "Kafka Terraform provider access"
    disable_wait_for_ready = false
    id                     = "XXXXXXXX"
    secret                 = (sensitive value)

    managed_resource {
        api_version = "cmk/v2"
        id          = "lkc-772rj"
        kind        = "Cluster"
    }

    owner {
        api_version = "iam/v2"
        id          = "u-lonwjj"
        kind        = "User"
    }
}
```

**Comment by pichouk** [comment]
When doing something like this it works
```
provider "confluent" {
  alias = "kafka"

  kafka_rest_endpoint = confluent_kafka_cluster.kafka.rest_endpoint
  kafka_api_key       = "XXXXXXXX"
  kafka_api_secret    = "ezfzefdsuioaj"
}
```

So I think it's an issue related to the `confluent_api_key` resource. This resource have been imported on Terraform so maybe it might be on issue related to key import ?

**Comment by linouk23** [comment]
That's great to hear you managed to fix the issue!

I was about to create a bug for

> I don't know why the import works because it is supposed to be a Kafka Cluster key, but it was the reason of my issue.

but then I opened [the docs](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_api_key#import) and realized that `confluent_api_key` is the unique resource that supports both options for importing which is why you didn't get the error during `terraform import` command.

![image](https://user-images.githubusercontent.com/5459870/196892594-cfd924e4-1697-477d-9cb9-6694a8d1ea86.png)
