### ISSUE TITLE
error creating Role Binding

### ISSUE THREAD

**Issue by mps021** [confluentinc/terraform-provider-confluent#126]
I am writing to use create role bindings using the RBAC module on version 1.8.0, I am able to create the service accounts, while trying to assign role to the new service accounts it throws the below message 

error creating Role Binding: Post "https://api.confluent.cloud/iam/v2/role-bindings" POST https://api.confluent.cloud/iam/v2/role-bindings giving up after 5 attempt(s). 

My initially thought was that it might be affected due to absence of Kafka secrets not mentioned in resource file, however despite adding them, the error is still the same. Additionally, role assignment does not works for the user as well. I'd request you to please assist with it. 
<img width="1511" alt="Screenshot 2022-10-27 at 4 23 54 PM" src="https://user-images.githubusercontent.com/116357028/198266269-3bd697dd-fea1-4362-b4cd-a15dbfff68f3.png">

**Comment by linouk23** [comment]
@mps021 could you share an example of your `confluent_role_binding` resource definition that fails with `500`?

**Comment by mps021** [comment]
> @mps021 could you share an example of your `confluent_role_binding` resource definition that fails with `500`?

@linouk23  below is my resource definition. 
`resource "confluent_role_binding" "DeveloperRead" {
  role_name     = "DeveloperRead"
  crn_pattern   = var.crn_pattern
  count         =  length(var.user_developer_read)
  principal     =  var.user_developer_read[count.index]
}
`
`variable "user_developer_read" {
  type = list(string)
  description = "user_name" 
  default = ["User:sa-xxxx"]
}`

**Comment by linouk23** [comment]
Could you share the CRN pattern you're using? I'm wondering whether our backend returns `500` instead of `400`.

**Comment by linouk23** [comment]
I'll close it due to inactivity, feel free to reopen.

**Comment by apurv-jay** [comment]
can you please tell me what i should i mention in the crn pattern of confluent_role_binding block of terraform if i want to use it for a topic

**Comment by linouk23** [comment]
@apurv-jay see our docs:
* https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_role_binding#example-usage
* https://docs.confluent.io/cloud/current/api.html#section/Identifiers-and-URLs/Confluent-Resource-Names-(CRNs)
