### ISSUE TITLE
 error creating Kafka ACLs: 400 Bad Request: pattern_type cannot be MATCH

### ISSUE THREAD

**Issue by S1M0NM** [confluentinc/terraform-provider-confluent#127]
Provider Version: 1.51
Cluster Type: Dedicated Cluster
Connection Type: Azure-Private-Link

---

Hello,

we are currently trying to create some ACLs and were trying to get an ACL working for a pattern using a wildcard asterisk inside the resource name - example: "company.location.private.*.dev"
Using LITERAL pattern type is not working using an asterisk and using **PREFIX** would include all topics not containing .dev as suffix.
As mentioned in the [Provider Docs](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_acl#pattern_type) allowed pattern types are **UNKNOWN**, **MATCH**, **LITERAL**, and **PREFIXED**
Same is documented for the underlying [API](https://docs.confluent.io/cloud/current/api.html#tag/ACL-(v3)/operation/createKafkaAcls).

During terraform plan **MATCH** is accepted as valid pattern type but when running apply it fails with the following error message:
`Error: error creating Kafka ACLs: 400 Bad Request: pattern_type cannot be MATCH`

I tried to figure out what MATCH is doing excactly but was not able to find any hint of this pattern type in the [Documentation](https://docs.confluent.io/platform/current/kafka/authorization.html). For my taste, the documentation generally lacks some information about which ACLs are possible.

Maybe you could also tell us if its possible to achieve an ACL working for a resource name containing wildcard asterisk and why MATCH is not working.

**Comment by S1M0NM** [comment]
So i found the [PatternType-Enum](https://kafka.apache.org/20/javadoc/org/apache/kafka/common/resource/PatternType.html) Java Doc.

If i get this right ANY and MATCH can only be used in filters an not for ACL creation?


`ANY In a filter, matches any resource pattern type. 
MATCH In a filter, will perform pattern matching.`

**Comment by linouk23** [comment]
👋 thanks for creating this issue @S1M0NM!

> we are currently trying to create some ACLs and were trying to get an ACL working for a pattern using a wildcard asterisk inside the resource name - example: "company.location.private.*.dev"

Your question definitely makes sense to me but unfortunately it seems to be too advanced for me, I asked our backend team who works on this but it might take a while for them to reply so I'd probably recommend asking ⬆️ on StackOverflow or something.

That said, your initial results look reasonable to me.

**Comment by linouk23** [comment]
OK so the backend team confirmed that both `ANY` and `MATCH` are for filters (not for create operations). In fact, only supported options should be `PREFIX` and `LITERAL`. We'll work on updating the docs accordingly.
