### ISSUE TITLE
Documentation about bootstrap_endpoint of confluent_cluster_link is invalid

### ISSUE THREAD

**Issue by yusaito01** [confluentinc/terraform-provider-confluent#128]
According to [a page of confluent_cluster_link](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_cluster_link#bootstrap_endpoint), `bootstrap_endpoint` argument of `source_kafka_cluster` block accepts both format like `SASL_SSL://XXX:9092` and `XXX:9092`.
But in fact, it accepts only a format starting with `SASL_SSL://`.

My codes is below:
```
resource "confluent_cluster_link" "destination-outbound" {
  link_name = "link_name"

  source_kafka_cluster {
    id                 = "my_cluster_id"
    bootstrap_endpoint = "XXX.XXX.XXX.XXX:9092" # raw IP address
  }

  destination_kafka_cluster {
    id            = confluent_kafka_cluster.destination-cluster.id
    rest_endpoint = confluent_kafka_cluster.destination-cluster.rest_endpoint
    credentials {
      key    = confluent_api_key.app-manager-api-key-destination.id
      secret = confluent_api_key.app-manager-api-key-destination.secret
    }
  }
}
```

And the error message is below:
```
% terraform plan
╷
│ Error: invalid value for source_kafka_cluster.0.bootstrap_endpoint (the bootstrap endpoint must start with 'SASL_SSL://')
│ 
│   with confluent_cluster_link.destination-outbound,
│   on link_and_mirror.tf line 6, in resource "confluent_cluster_link" "destination-outbound":
│    6:     bootstrap_endpoint = "XXX.XXX.XXX.XXX:9092"
│ 
╵
%
```

**Comment by linouk23** [comment]
@yusaito01 could you confirm you're using TF Provider for Confluent with version `1.9.0` or later? The issue you're referencing seems like a duplicate of #118 that we should have [fixed](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#190-october-24-2022) in `1.9.0`.

**Comment by linouk23** [comment]
It doesn't look like there're any validations for `SASL_SSL://` prefix left in [resource_cluster_link.go](https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/resource_cluster_link.go).

**Comment by yusaito01** [comment]
@linouk23 Thank you for your comment. 
> could you confirm you're using TF Provider for Confluent with version 1.9.0 or later?
sorry I used TF Provider version 1.5.1. After update to 1.10.0, this error was resolved.
