### ISSUE TITLE
How to create confluent_cluster_link without credentials block?

### ISSUE THREAD

**Issue by yusaito01** [confluentinc/terraform-provider-confluent#129]
I have tried to create `confluent_cluster_link` without `credentials` block in `source_kafka_cluster` because our on-prem kafka cluster have no auth settings, and it was failed.
According to [document](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_cluster_link#credentials), credentials block is not Required Configuration Block. But terraform states `credentials` block must be specified. 
How to create `confluent_cluster_link` without `credentials` block?

My environment is below:
* terraform version: 1.3.0
* tf provider version: 1.10.0

tf code and error message are below:
```
resource "confluent_cluster_link" "destination-outbound" {
  link_name = "destination-initiated-cluster-link"

  source_kafka_cluster {
    id                 = "<kafka cluster id>"
    bootstrap_endpoint = "XXX.XXX.XXX.XXX:9092"
  }

  destination_kafka_cluster {
    id            = confluent_kafka_cluster.destination-cluster.id
    rest_endpoint = confluent_kafka_cluster.destination-cluster.rest_endpoint
    credentials {
      key    = confluent_api_key.app-manager-api-key-destination.id
      secret = confluent_api_key.app-manager-api-key-destination.secret
    }
  }
}
```

**Comment by linouk23** [comment]
Thanks for creating this issue @yusaito01!

> According to [document](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_cluster_link#credentials), credentials block is not Required Configuration Block.

When I took another look at our examples, it looks like `destination_kafka_cluster.credentials` is required (we'll update our docs 👌) and `source_kafka_cluster.credentials` is optional.

The reason why `source_kafka_cluster.credentials` is optional is that it should not be specified for just for _destination inbound_ part of Cluster Link, see [source-initiated-cluster-link-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/source-initiated-cluster-link-rbac) example.

That said, it sounds like you're using [destination-initiated-cluster-link-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/destination-initiated-cluster-link-rbac) where _credentials_ block is [required](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/destination-initiated-cluster-link-rbac/main.tf):
```
resource "confluent_cluster_link" "destination-outbound" {
  link_name = var.cluster_link_name
  source_kafka_cluster {
    id                 = data.confluent_kafka_cluster.source.id
    bootstrap_endpoint = data.confluent_kafka_cluster.source.bootstrap_endpoint
    credentials {
      key    = confluent_api_key.app-manager-source-cluster-api-key.id
      secret = confluent_api_key.app-manager-source-cluster-api-key.secret
    }
  }

  destination_kafka_cluster {
    id            = data.confluent_kafka_cluster.destination.id
    rest_endpoint = data.confluent_kafka_cluster.destination.rest_endpoint
    credentials {
      key    = confluent_api_key.app-manager-destination-cluster-api-key.id
      secret = confluent_api_key.app-manager-destination-cluster-api-key.secret
    }
  }
}
```

**Comment by linouk23** [comment]
> because our on-prem kafka cluster have no auth settings, and it was failed.

By the way, as of now, `confluent_cluster_link` only supports Cloud <-> Cloud 😕

**Comment by yusaito01** [comment]
@linouk23 Thank you for your reply.

>The reason why source_kafka_cluster.credentials is optional is that it should not be specified for just for destination inbound part of Cluster Link, see [source-initiated-cluster-link-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/source-initiated-cluster-link-rbac) example.

I understood this and why I need to add credential block to source_kafka_cluster.

> By the way, as of now, confluent_cluster_link only supports Cloud <-> Cloud 😕

Umm, I did not know it. I checked the document again, but I guess it does not state it.

By the way, we are using a dedicated confluent cloud cluster with private network, and according to our Confluent Account Team, we need to make a support request in this situation. So I understood that we can not manage cluster linking for a dedicated cluster for private network.

I will close this issue. Thank you for your support.

**Comment by linouk23** [comment]
> Umm, I did not know it. I checked the document again, but I guess it does not state it.

That's a great catch @yusaito01 and we'll work on updating our docs if we don't add CP support before GA release.

> By the way, we are using a dedicated confluent cloud cluster with private network, and according to our Confluent Account Team, we need to make a support request in this situation. So I understood that we can not manage cluster linking for a dedicated cluster for private network.

I'm not sure I'm following this. There's this [doc page](https://docs.confluent.io/cloud/current/multi-cloud/cluster-linking/index.html#supported-cluster-types) that says:
![image](https://user-images.githubusercontent.com/5459870/199203823-6b883ed3-cadd-48e8-b091-03426bd775f5.png)

so _dedicated confluent cloud cluster with private network_ seems to be supported in some capacity. FWIW you might want to use [source-initiated-cluster-link-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/source-initiated-cluster-link-rbac) example for these scenarios.

**Comment by yusaito01** [comment]
@linouk23 thank you for your reply and giving information.

>  I'm not sure I'm following this. There's this [doc page](https://docs.confluent.io/cloud/current/multi-cloud/cluster-linking/index.html#supported-cluster-types) that says:

I guess this row says **source cluster** is a dedicated cluster with private networking and destination is a dedicated cluster. In our situation, source cluster is a on-prem kafka cluster and **destination* is a dedicated cluster with private networking.
And according to this [page](https://docs.confluent.io/cloud/current/multi-cloud/cluster-linking/private-networking.html#ccloud-and-ak-tm)'s second row, when source cluster is on-prem kafka and destination is a dedicated cluster with private networking, we need to contact our account team or support team.
