### ISSUE TITLE
terraform confluent provider - SINGLE_ZONE cluster deployment doesn't show zone placement

### ISSUE THREAD

**Issue by cmkb** [confluentinc/terraform-provider-confluent#132]
**Problem**
When choosing a SINGLE_ZONE  deploymentfor a Kafka cluster, it doesn’t tell you which zone it got deployed to after the resource gets deployed. The result of this is that if you are automating all the networking components via terraform, you don’t know which zone to route to get to the cluster. If you do all three zones, you will get errors trying to access the cluster since the kafka cluser will not exist in the other zones.
You must go inside the UI to the Cluster settings to find out and then rerun terraform with the zone manually specified.

Here is what it looks like when I output the state in terraform right now:

```
resource "confluent_kafka_cluster" "cluster_primary" {
    api_version        = "cmk/v2"
    availability       = "SINGLE_ZONE"
    bootstrap_endpoint = "madeupid-madeupnetwork.eastus2.azure.glb.confluent.cloud:9092"
    cloud              = "AZURE"
    display_name       = "mykafkacluster"
    id                 = "madeupid"
    kind               = "Cluster"
    rbac_crn           = "crn://confluent.cloud/organization=349879h398-47fg-485f-madeupguid/environment=env-fake/cloud-cluster=madeupid"
    region             = "eastus2"
    rest_endpoint      = [https://madeupid-madeupnetwork.eastus2.azure.glb.confluent.cloud:443]
 
    dedicated {
        cku = 1
    }

    environment {
        id = "env-fake"
    }
 
    network {
        id = "madeupnetwork"
        zones = [“AZ1”]
    }
```

**Can we please have a variable inside the networking block(or anywhere in the cluster resource really) specifying which zones the cluster got deployed to?**

Something like:
```
resource "confluent_kafka_cluster" "cluster_primary" {
    api_version        = "cmk/v2"
    availability       = "SINGLE_ZONE"
    bootstrap_endpoint = "madeupid-madeupnetwork.eastus2.azure.glb.confluent.cloud:9092"
    cloud              = "AZURE"
    display_name       = "mykafkacluster"
    id                 = "madeupid"
    kind               = "Cluster"
    rbac_crn           = "crn://confluent.cloud/organization=349879h398-47fg-485f-madeupguid/environment=env-fake/cloud-cluster=madeupid"
    region             = "eastus2"
    rest_endpoint      = [https://madeupid-madeupnetwork.eastus2.azure.glb.confluent.cloud:443]
 
    dedicated {
        cku = 1
    }
 
    environment {
        id = "env-fake"
    }
 
    network {
        id = "madeupnetwork"
        zones = [“AZ1”]                 # <--- ADD SOME THING LIKE THIS
    }
}
```

**Comment by linouk23** [comment]
Thanks for reporting it @cmkb!

It's worth mentioning that current CMK API doesn't support this yet and this request is being tracked as `ORC-4711` internally. You might want to reach out to Confluent support so that they'll record it as +1 interested customers for that feature. Thanks!

**Comment by linouk23** [comment]
update: we merged a fix internally so this issue will be resolved in the next release of TF Provider for Confluent. cc @cmkb

**Comment by linouk23** [comment]
@cmkb see our latest [1.34.0](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.34.0) release where we

> Added support for new computed zones attribute of confluent_kafka_cluster [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_cluster) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_kafka_cluster) in a [Generally Available lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy)

**Comment by cmkb** [comment]
> @cmkb see our latest [1.34.0](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.34.0) release where we
> 
> > Added support for new computed zones attribute of confluent_kafka_cluster [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_cluster) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_kafka_cluster) in a [Generally Available lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy)

Thanks man! I see the change on the tf documentation. woooo
https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_cluster#zones

**Comment by linouk23** [comment]
Thanks for reporting it @cmkb!
