### ISSUE TITLE
How to change terraform provider  from mongey to confluentinc without impacting current terraform resources created 

### ISSUE THREAD

**Issue by ravichoudhary20** [confluentinc/terraform-provider-confluent#135]

**Comment by ravichoudhary20** [comment]
Currently, I am using "Mongey/kafka" provider and now I have to switch to "confluentinc/confluent" provider with my existing terraform pipeline.
How can I do this ?

Steps currently following to switch the provider

Changing the provider in main.tf file and running following command to replace provider

    terraform state replace-provider Mongey/kafka confluentinc/confluent

and after that I run 
`terraform init` command to install the new provider 
But after that when I am running 

    terraform plan

 it is giving "`no schema available for module.iddn_news_cms_kafka_topics.kafka_acl.topic_writer[13] while reading state; this is a bug in terraform and should be reported"` error.

Is there any way, I will change the terraform provider without disturbing the existing resources created using terraform pipeline ?

**Comment by linouk23** [comment]
👋 @ravichoudhary20, thanks for opening this issue!

I haven't got a ton of experience using "Mongey/kafka" provider but it [looks like](https://registry.terraform.io/providers/Mongey/kafka/latest/docs/resources/topic) the resource definitions are slightly different so I'm not sure whether `terraform state replace-provider` will help.

Until our TF provider provides a resource exporter or something, the safest way to switch to "confluentinc/confluent" provider seems to be a manual reimporting of every [topic](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#import) / other resources to a new TF workspace without updating your existing TF workspace that uses "Mongey/kafka" provider.

Alternatively, it might be a good idea to update your `.tf` and `.tfstate` files to match the resource definitions of "confluentinc/confluent" provider. Here's an [managing-single-cluster](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/managing-single-cluster) example that might be helpful.

Let me know if it helps!

**Comment by linouk23** [comment]
@ravichoudhary20 you might also find [Experimental Resource Importer for Confluent Terraform Provider](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/experimental-resource-importer) useful.
