### ISSUE TITLE
Unable to create role bindings using terraform

### ISSUE THREAD

**Issue by mps021** [confluentinc/terraform-provider-confluent#137]
I am writing to use create role bindings using the RBAC module on version 1.8.0, I am able to create the service accounts, while trying to assign role to the new service accounts it throws the below message

error creating Role Binding: Post "https://api.confluent.cloud/iam/v2/role-bindings" POST https://api.confluent.cloud/iam/v2/role-bindings giving up after 5 attempt(s).

My initially thought was that it might be affected due to absence of Kafka secrets not mentioned in resource file, however despite adding them, the error is still the same. Additionally, role assignment does not works for the user as well. I'd request you to please assist with it.

**Comment by linouk23** [comment]
👋 thanks for creating the issue @mps021! 

I can see our role bindings backend works OK for other users but it does return quite a bit of 500s for your specific org.

Could you share an example of a role binding you're trying to create? I feel like it might be `400` (Bad Request) error that our backend return as `500`, see this [doc page](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_role_binding#example-usage) for more examples.

**Comment by mps021** [comment]
`resource "confluent_role_binding" "CloudClusterAdmin" {
  role_name     = "CloudClusterAdmin"
  crn_pattern   = var.crn_pattern
  count         =  length(var.user_admin)
  principal     =  var.user_admin[count.index]
}`

**Comment by mps021** [comment]
` "crn://confluent.cloud/organization=xxxxxxx/environment=test=xxxx/cloud-cluster=xxxxx/kafka=xxxxxx"
`

**Comment by linouk23** [comment]
@mps021 could you try to use data source:
```
data "confluent_kafka_cluster" "example_using_id" {
  id = "lkc-abc123"
  environment {
    id = "env-xyz456"
  }
}
```
to infer correct value for `crn_pattern` by using `data.confluent_kafka_cluster.example_using_id.resource_name`?

That might be a typo but having `environment=test` vs `environment=env-xyz123` might be an issue.

**Comment by linouk23** [comment]
I looked at the logs and it seems like the value for `crn_pattern` is a little bit off:

Our backend receives:
```
crn://confluent.cloud/organization=***/environment=A***=env-******/cloud-cluster=***/kafka=***
```
instead of
```
crn://confluent.cloud/organization=***/environment=env-******/cloud-cluster=***/kafka=***
```

Let me know if it helps!
