### ISSUE TITLE
Orphan cluster issue

### ISSUE THREAD

**Issue by maheshbhole** [confluentinc/terraform-provider-confluent#139]
Hello,

Getting following error but from portal cluster id "lksqlc-6kvw12" does not exist.

Error: -15T12:45:14.289Z [ERROR] vertex "module.shared-cluster.confluent_ksql_cluster.ksqldb-btt-pos (orphan)" error: error reading ksqlDB Cluster "lksqlc-6kvw12": 401 Unauthorized: Unauthorized

Please help how to approch this problem.

-Mahesh

**Comment by linouk23** [comment]
👋 thanks for creating an issue @maheshbhole!

That sounds like an auth issue to me, could you double [check](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs) you're setting Cloud API Keys?
```
provider "confluent" {
  cloud_api_key    = var.confluent_cloud_api_key    # optionally use CONFLUENT_CLOUD_API_KEY env var
  cloud_api_secret = var.confluent_cloud_api_secret # optionally use CONFLUENT_CLOUD_API_SECRET env var
}
```

**Comment by linouk23** [comment]
Feel free to reopen if the issue persists.

**Comment by maheshbhole** [comment]
@linouk23 
Hello ,
These server did not exist as they were deleted manually from portal.
Terraform does not know it and keep referencing those .
I think error should be correct that server is reachable etc.

**Comment by linouk23** [comment]
Could you add more details to the message above? Do you mean that ksqlDB clusters were deleted manually but you've been getting 401 errors still?
