### ISSUE TITLE
Error trying deploy confluent_kafka_acl confluent_connector resources

### ISSUE THREAD

**Issue by javiervelamindcurv** [confluentinc/terraform-provider-confluent#142]
Hello,

Since yesterday (2022/11/17), I'm getting the error The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

I updated from 1.7.0 to 1.14.0 version and now the error is: Error: 401 Unauthorized: <invalid reflect.Value>

Before yesterday the code was working correctly.

Any idea?

Thanks and best regards,

**Comment by linouk23** [comment]
Thanks for reporting @javiervelamindcurv!

Could you share your TF configuration? Also could you try `1.13.0` and see whether it works still?

**Comment by linouk23** [comment]
By the way, I just run [basic-kafka-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/basic-kafka-acls) using `1.14.0` and it seems to work fine 🤔

**Comment by javiervelamindcurv** [comment]
Hello @linouk23 !

Using 1.13.0, I got same error: 401 Unauthorized: <invalid reflect.Value>

Also I opened a support ticket,

**Comment by linouk23** [comment]
I see, could you double check that you're passing Cloud API Keys?

See https://registry.terraform.io/providers/confluentinc/confluent/latest/docs#example-usage

**Comment by javiervelamindcurv** [comment]
I'm assigning ACL to an existing service account.  I wrote an example.

Are needed Cloud API keys?  - the code was working before 2022/11/16

resource "confluent_kafka_acl" "app-producer-write-on-topic" {
  kafka_cluster {
    id = var.cluster_id
  }
  resource_type = "TOPIC"
  resource_name = var.topic_name
  pattern_type  = "LITERAL"
  principal     = "User:${var.sa_id}"
  host          = "*"
  operation     = "WRITE"
  permission    = "ALLOW"
  rest_endpoint = var.cluster_rest_endpoint
  credentials {
    key    = var.key
    secret = var.secret
  }
}

**Comment by linouk23** [comment]
> Are needed Cloud API keys? - the code was working before 2022/11/16

Correct, Cloud API Key are necessary for performing resourceID -> intID (`sa-abc123` -> `44421`) until we release a new version of our APIs.

**Comment by javiervelamindcurv** [comment]
Crazy... do you when are you going to release a new version of your API?

**Comment by linouk23** [comment]
It's on the roadmap but I can't share any timelines publicly.

**Comment by linouk23** [comment]
FWIW I feel like we added this behavior back in `0.7.0` (pre-GA `1.0.0`) or something.
