### ISSUE TITLE
Topic is getting recreated/replaced with new topic by terraform

### ISSUE THREAD

**Issue by maheshbhole** [confluentinc/terraform-provider-confluent#144]
Hello,

We are facing issue where we created topic with terraform but to attach schema it needs to be modified from portal. (This can't be done via terraform for now)
But when we rerun terraform , It detects existing topic is diffrent (since it is modified outside terraform) and recreates that topic.
This is issue because we will loose data in that topic.
Do you have any workaround for this.

Thx,
Mahesh

**Comment by linouk23** [comment]
Thanks for creating an issue!

Could you share more details about what topic details are changed via the portal / output of `terraform plan` that causes a recreation of a topic?

**Comment by linouk23** [comment]
cc @maheshbhole

**Comment by maheshbhole** [comment]
Here is terraform plan output

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.shared-cluster.confluent_kafka_topic.likp has changed
  ~ resource "confluent_kafka_topic" "likp" {
      ~ config           = {
          + "cleanup.policy"                      = "delete"
          + "delete.retention.ms"                 = "86400000"
          + "max.compaction.lag.ms"               = "9223372036854775[807](https://github.com/kesko-dev/k-confluent-infra/actions/runs/3520333045/jobs/5901151910#step:7:808)"
          + "max.message.bytes"                   = "2097164"
          + "message.timestamp.difference.max.ms" = "9223372036854775807"
          + "message.timestamp.type"              = "CreateTime"
          + "min.compaction.lag.ms"               = "0"
          + "min.insync.replicas"                 = "2"
          + "retention.bytes"                     = "-1"
          + "retention.ms"                        = "31536000000"
          + "segment.bytes"                       = "104857600"
          + "segment.ms"                          = "604800000"
        }
        id               = "lkc-pgd93k/com.kesko.gt.scm.sap.source.LIKP"
        # (3 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

  # module.shared-cluster.confluent_kafka_topic.lips has changed
  ~ resource "confluent_kafka_topic" "lips" {
      ~ config           = {
          + "cleanup.policy"                      = "delete"
          + "delete.retention.ms"                 = "86400000"
          + "max.compaction.lag.ms"               = "9223372036854775807"
          + "max.message.bytes"                   = "2097164"
          + "message.timestamp.difference.max.ms" = "9223372036854775807"
          + "message.timestamp.type"              = "CreateTime"
          + "min.compaction.lag.ms"               = "0"
          + "min.insync.replicas"                 = "2"
          + "retention.bytes"                     = "-1"
          + "retention.ms"                        = "31536000000"
          + "segment.bytes"                       = "104857600"
          + "segment.ms"                          = "604800000"
        }
        id               = "lkc-pgd93k/com.kesko.gt.scm.sap.source.LIPS"
        # (3 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

  # module.shared-cluster.confluent_kafka_topic.pickupdelivery-models has been deleted
        }

      - kafka_cluster {
          - id = "lkc-pgd93k" -> null
        }
    }

  # module.shared-cluster.confluent_kafka_topic.receipts will be created
  + resource "confluent_kafka_topic" "receipts" {
      + config           = (known after apply)
      + id               = (known after apply)
      + partitions_count = 1
      + rest_endpoint    = "[https://pkc-1wvvj.westeurope.azure.confluent.cloud:443](https://pkc-1wvvj.westeurope.azure.confluent.cloud/)"
      + topic_name       = "com.kesko.gt.receipts"

      + credentials {
          + key    = (sensitive value)
          + secret = (sensitive value)
        }

      + kafka_cluster {
          + id = "lkc-pgd93k"
        }
    }

Plan: 23 to add, 0 to change, 7 to destroy.

**Comment by linouk23** [comment]
I'll try to take a look at it early this week, thanks!

**Comment by linouk23** [comment]
Thanks for waiting @maheshbhole!

Did you consider [re-importing](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#import) a topic? That's probably the most common workaround for this use case.
