### ISSUE TITLE
confluent_api_key should support creating a key for Schema Registry clusters

### ISSUE THREAD

**Issue by linouk23** [confluentinc/terraform-provider-confluent#146]
### What

Currently [confluent_api_key](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_api_key) resource only supports creating Cloud and Kafka API Keys but it should also support Schema Registry API Keys as well.

**Comment by tbublik** [comment]
```
Error: expected managed_resource.0.api_version to be one of [cmk/v2], got srcm/v2
```

**Comment by linouk23** [comment]
@tbublik that looks accurate to me, SR Keys are not supported yet unfortunately (both in TF & backend).

**Comment by serhiimakogon** [comment]
ksql keys creation are not supported as well

**Comment by linouk23** [comment]
@serhiimakogon created https://github.com/confluentinc/terraform-provider-confluent/issues/151 👍

**Comment by serhiimakogon** [comment]
maybe someone knows what are the other ways to automate the creation of keys?
because `confluent-cli` requires login via oauth2 flow

**Comment by S1M0NM** [comment]
Is there a rough planned release date for the support of schema-registry keys?

**Comment by linouk23** [comment]
@tbublik @serhiimakogon @S1M0NM the [latest release](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1220-december-15-2022) resolves this issue. See 

* [multiple-event-types-avro-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-avro-schema)
* [multiple-event-types-proto-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-proto-schema)
* [single-event-types-avro-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/single-event-types-avro-schema)
* [single-event-types-proto-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/single-event-types-proto-schema)

to see how to create Schema Registry API Keys via `confluent_api_key` resource.
