### ISSUE TITLE
Possible rate limit issue on https://api.confluent.cloud/service_accounts

### ISSUE THREAD

**Issue by alukic** [confluentinc/terraform-provider-confluent#148]
Our pipelines are consistently failing on the same call to https://api.confluent.cloud/service_accounts
We have large number of ACLs which might be a problem if there are rate limits on this REST API endpoint
```
 Error: error reading Kafka ACLs: Get "https://api.confluent.cloud/service_accounts": GET https://api.confluent.cloud/service_accounts giving up after 5 attempt(s)
│ 
│  
.....
.....
│ Error: error reading Kafka ACLs: Get "https://api.confluent.cloud/service_accounts": GET https://api.confluent.cloud/service_accounts giving up after 5 attempt(s)
│ 
.....
│ 
```

**Comment by linouk23** [comment]
@alukic thanks for reporting an issue!

TF Provider for Confluent retries 5 times on 5xx & 429 errors which doesn't seem sufficient for your use case. Did you try to use 
```
terraform plan -parallelism=1
terraform apply -parallelism=1
```
to see whether it mitigates the issue?

**Comment by linouk23** [comment]
@alukic that's exactly right! Let me know whether it helps.

**Comment by VipulZopSmart** [comment]
@linouk23 facing the same issue and we're running this through Github actions.
<img width="887" alt="Screenshot 2023-08-07 at 4 21 09 PM" src="https://github.com/confluentinc/terraform-provider-confluent/assets/77278140/ffd61b2e-2bce-428e-b4b3-b2a4b44982e1">

**Comment by linouk23** [comment]
👋 @VipulZopSmart please update to at least version `1.47.0` of TF Provider that eliminates API calls to `service_accounts` completely, thanks!
