### ISSUE TITLE
Can't update topics setup with another API key

### ISSUE THREAD

**Issue by javiervelamindcurv** [confluentinc/terraform-provider-confluent#149]
Hello,

I can't update topics setup using another API key

1. Create an API key
2. Create several topics using the API key created
3. Delete the API key
4. Create another API and try to change the setup of any topics or try delete the topics, you got an error (Now I don't remember if 401 or 403) 

The module should support this scenario.

Best regards,

**Comment by linouk23** [comment]
Thanks for reporting the issue @javiervelamindcurv!

Sounds like you're talking about the disaster recovery. That [note](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic) might be helpful: 
![image](https://user-images.githubusercontent.com/5459870/204768769-58ed4fd5-2f6a-4123-9312-d856f6c02eeb.png)

Feel free to reopen if you run into any issues.
