### ISSUE TITLE
The document of confluent_ksql_cluster is maybe wrong

### ISSUE THREAD

**Issue by yusaito01** [confluentinc/terraform-provider-confluent#150]
According to the document of `confluent_ksql_cluster`, we have to deploy `confluent_stream_governance_cluster`, but this resource is already deplicated.
https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_ksql_cluster

I guess it is wrong documentation and we have to deploy `confluent_schema_registry_cluster` instead. Is it correct?

**Comment by linouk23** [comment]
> I guess it is wrong documentation and we have to deploy confluent_schema_registry_cluster instead. Is it correct?

That's exactly right! Thanks for reporting this bug in documentation, we'll fix it in the next release!

**Comment by yusaito01** [comment]
@linouk23 thank you for your help!

**Comment by linouk23** [comment]
Updated the docs in our [latest release](https://github.com/confluentinc/terraform-provider-confluent/blob/v1.19.0/CHANGELOG.md#1190-december-1-2022).
