### ISSUE TITLE
confluent_kafka_acl resource does not allow use as principal "User:*"

### ISSUE THREAD

**Issue by rociomeras** [confluentinc/terraform-provider-confluent#152]
Hi,
I am trying to use confluent_kafka_acl resource to grant all the user read operation over a consumer group resource but i am getting an error that says the principal should follow the pattern "User:sa-" or "User:u-" or "User:pool-"

This is the code i am using the create the acl

```
resource "confluent_kafka_acl" "wildCard-consumer-group-describe" {
  kafka_cluster {
    id = data.confluent_kafka_cluster.cluster.id
  }
  resource_type = "GROUP"
  resource_name = "consumer_group_name"
  pattern_type  = "LITERAL"
  principal     = "User:*"
  host          = "*"
  operation     = "DESCRIBE"
  permission    = "ALLOW"
}
```

```
resource "confluent_kafka_acl" "wildCard-consumer-group-allow-read" {
  kafka_cluster {
    id = data.confluent_kafka_cluster.cluster.id
  }
  resource_type = "GROUP"
  resource_name = "consumer_group_name"
  pattern_type  = "LITERAL"
  principal     = "User:*"
  host          = "*"
  operation     = "READ"
  permission    = "ALLOW"
}
```

This is the error message i got
╷
│ Error: invalid value for principal (the principal must start with 'User:sa-' or 'User:u-' or 'User:pool-'.)
│ 
│   with confluent_kafka_acl.wildCard-consumer-group-describe,
│   on allow-all.tf line 49, in resource "confluent_kafka_acl" "wildCard-consumer-group-describe":
│   49:   principal     = "User:*"
│ 
╵

I want to grant all the users permission over that consumer group. I dont want to create a acl for each user.

**Comment by linouk23** [comment]
Thanks for creating this issue @rociomeras!

I'm afraid you might have to create an ACL for each users or you might also try `confluent_role_binding` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_role_binding).

**Comment by rociomeras** [comment]
The confluent_role_binding resource also does not allow use as principal "User:*"

The confluent API allow me to create the acl using "User:*" as principal. I can't think in a valid reason for not allow that form the terraform provider. At the end, the terraform provider is a wrapper for the confluent API

Example of the call that work

curl --location --request POST 'https:CLUSTER_ENDPOINT/kafka/v3/clusters/lkc-127zyj/acls' \
--header 'Authorization: Basic TOKEN' \
--header 'Content-Type: application/json' \
--data-raw '{
    "resource_type": "TRANSACTIONAL_ID",
    "resource_name": "*",
    "pattern_type": "LITERAL",
    "principal": "User:*",
    "host": "*",
    "operation": "ALL",
    "permission": "ALLOW"
}'

**Comment by linouk23** [comment]
@rociomeras I double checked with a team and I was told that currently the Admin Client allows such requests so your suggestion looks accurate to me and that's something that should be added to TF Provider.

**Comment by joshholl** [comment]
Hi, I too ran into an issue with this and submitted a PR #158  to address this. I have tested it out against my cluster and it seems to function well. But as I state in the PR I'm a novice with go and have no experience with wiremock so I imagine there is more I need to do to create a higher quality PR.

**Comment by linouk23** [comment]
Thanks for creating a PR! We merged a fix internally and hopefully we'll release it next week.

fyi @joshholl @rociomeras

**Comment by rociomeras** [comment]
thank for the PR @joshholl . I will be checking the new release when is ready

**Comment by linouk23** [comment]
I synced with my team and unfortunately we might have to wait until our internal code freeze is lifted (which is going to happen in 2023 😕).

**Comment by linouk23** [comment]
👋 @joshholl @rociomeras

The fix has been [released](https://github.com/confluentinc/terraform-provider-confluent/blob/v1.24.0/CHANGELOG.md#1240-january-5-2023) in our latest version of TF Provider.

**Comment by joshholl** [comment]
@linouk23 thank you for seeing this through!
