### ISSUE TITLE
Can I create destination-initiated cluster link without credentials block?

### ISSUE THREAD

**Issue by yusaito01** [confluentinc/terraform-provider-confluent#154]
Hello there,

We have an on-prem kafka cluster on our AWS VPC and a dedicated confluent cluster on private network. Both this private network and our VPC are attached to a same transit gateway so there is a connectivity between them.

Few days ago, I tried to create cluster linking as the on-prem kafka cluster is source and it was succeeded.
When I create cluster linking, the settings are as follows.
![image](https://user-images.githubusercontent.com/108614502/207038947-e18124de-a833-490a-bd39-b459a04c707a.png)

As you can see, "Source initiated connection" checkbox was unchecked, and "Security configuration" was blank.
It means, in my understanding, I created destination-initiated cluster linking without any credentials.

After that, I tried to create similar cluster linking using terraform, but it was failed. My terraform codes are below:
```
terraform {
  required_version = "~> 1.3.3"
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "~> 1.21.0"
    }
  }
}
...
resource "confluent_cluster_link" "destination-outbound" {
  link_name = "cluster-linking-creation-labo"

  source_kafka_cluster {
    id                 = "me2GGp7ORPGRrZJLpQsuyw"
    bootstrap_endpoint = "perf-kafka-app-2-7-0-0.perf2.paypay.ne.jp:9092"
  }

  destination_kafka_cluster {
    id = confluent_kafka_cluster.clusterlinkinglabo.id
    rest_endpoint = confluent_kafka_cluster.clusterlinkinglabo.rest_endpoint
    credentials {
      key = confluent_api_key.clusterlikinglabo-app-manager.id
      secret = confluent_api_key.clusterlikinglabo-app-manager.secret
    }
  }
}
```
And error message is below:
```
confluent_cluster_link.destination-outbound: Creating...
╷
│ Error: error creating Cluster Link: "credentials" must be specified for "source_kafka_cluster"
│ 
│   with confluent_cluster_link.destination-outbound,
│   on main.tf line 133, in resource "confluent_cluster_link" "destination-outbound":
│  133: resource "confluent_cluster_link" "destination-outbound" {
│ 
╵
```

I understood that credentials block is required in source_kafka_cluster block when I create destination-initiated cluster linking because I have been taught this in this PR: https://github.com/confluentinc/terraform-provider-confluent/issues/129
I thought there was some update that made it possible, but that does not seem to be the case.

Please tell me how to create this sort of cluster linking using terraform.

**Comment by yusaito01** [comment]
> confluent_cluster_link supports just Cloud <-> Cloud 😕, we'll update the docs to indicate it.

But according to some documents, cluster linking partially support linking between on-prem kafka and cloud. 
https://docs.confluent.io/cloud/current/multi-cloud/cluster-linking/private-networking.html#cluster-linking-with-private-networking-on-ccloud

> could you share the configuration that worked for you?

Sure, like these:
![image](https://user-images.githubusercontent.com/108614502/207227728-c46cef43-1d72-4b1c-901b-f05951eb1c95.png)
![image](https://user-images.githubusercontent.com/108614502/207227782-cb5c1c0c-d987-4661-a9fb-ed5db55fc2eb.png)
![image](https://user-images.githubusercontent.com/108614502/207227820-61f0e16a-1c93-460c-8a98-1bd6709ab219.png)
![image](https://user-images.githubusercontent.com/108614502/207227856-d54170bb-a650-4d51-8852-4ae7ae040220.png)
"Source initiated connection" checkbox was unchecked, and "Security configuration" was blank.

**Comment by linouk23** [comment]
Oh I see, what I meant by 

> confluent_cluster_link supports just Cloud <-> Cloud 😕,

is that TF's `confluent_cluster_link` supports just Cloud <-> Cloud 😕 but CLI / UI allows a user to manage on-prem Kafka - Cloud as you referenced.

**Comment by yusaito01** [comment]
> is that TF's confluent_cluster_link supports just Cloud <-> Cloud 😕 but CLI / UI allows a user to manage on-prem Kafka - Cloud as you referenced.

Hmm, so to sum up, I can create a cluster linking between on-prem and cloud using console, but cannot create/manage it using terraform. Is it correct?

**Comment by linouk23** [comment]
Correct (assuming "console" means both Confluent CLI and Confluent Cloud Console (UI)).

**Comment by yusaito01** [comment]
> That's accurate (assuming "console" means both Confluent CLI and Confluent Cloud Console (UI)).

OK, I got it. Thank you for your support. We look forward to confluent provider supporting this feature.
