### ISSUE TITLE
Support setting the RBAC for service accounts on the schema registry

### ISSUE THREAD

**Issue by lorelei-rupp-imprivata** [confluentinc/terraform-provider-confluent#160]
Schema Registry now requires RBAC in Dec 2022

How can we use the confluent_role_binding resource to add the role "ResourceOwner" to the service account against the Schema Registry

The scheme Registry doesn't appear to be an option here https://docs.confluent.io/cloud/current/api.html#section/Identifiers-and-URLs/Confluent-Resource-Names-(CRNs) for the "crn_pattern" that the role binding resource needs

How can we set this up with terraform, as you now require it in confluent cloud

**Comment by zhenli00** [comment]
@lorelei-rupp-imprivata 
Yeah right now we support RBAC on subjects, please see the example below:

resource "confluent_role_binding" "subject-example-rb" {
   principal   = "User:${confluent_service_account.test.id}"
   role_name   = "DeveloperRead"
   crn_pattern = "${confluent_schema_registry_cluster.example.resource_name}/subject=*"
 }

**Comment by lorelei-rupp-imprivata** [comment]
> @lorelei-rupp-imprivata Yeah right now we support RBAC on subjects, please see the example below:
> 
> resource "confluent_role_binding" "subject-example-rb" { principal = "User:${confluent_service_account.test.id}" role_name = "DeveloperRead" crn_pattern = "${confluent_schema_registry_cluster.example.resource_name}/subject=*" }

Oh Great, so I should be able to do this with the "ResourceOnwer" role_name then?
You should update your role_binding provider docs to add an example for this. I wasn't quite sure how to do it! I will try this out

**Comment by linouk23** [comment]
@lorelei-rupp-imprivata that's exactly right!

TF snippet ⬇️ 
```
resource "confluent_role_binding" "subject-example-rb" {
   principal = "User:${confluent_service_account.test.id}"
   role_name = "ResourceOwner"
   crn_pattern = "${data.confluent_schema_registry_cluster.example.resource_name}/subject=test"
}
```
results in
![image](https://user-images.githubusercontent.com/5459870/209892414-b453541d-577f-4b9b-b967-9d67fe102ef2.png)
