### ISSUE TITLE
Question about the role to assign to an API key to be used in Schema Registry

### ISSUE THREAD

**Issue by javiervelamindcurv** [confluentinc/terraform-provider-confluent#161]
Hello,

Since 1.22 release we are able to create an API key to be used in Schema Registry, we must assign the role **EnvironmentAdmin**.

From my point of view I think it's a role with many privileges to be used only to create schemas or check schemas in Schema Registry.

Do you plan create a new role with lower privileges. 

Thanks and best regards,

**Comment by linouk23** [comment]
Thanks for the question @javiervelamindcurv!

It sounds like you're interested in having a new role with lower privileges than `EnvironmentAdmin` that would allow creation of a Schema Registry API Key. Is that accurate?

**Comment by javiervelamindcurv** [comment]
Yes.

I would like have a role to be assigned to an API key, the role only allows interact with Schema Registry.

**Comment by javiervelamindcurv** [comment]
I just saw this: 

![image](https://user-images.githubusercontent.com/102152403/210764042-f998e7de-479d-487d-8f1a-05d35e000deb.png)

From the UI we can assign specific roles to manage schemas. Are supported by terraform module?

**Comment by linouk23** [comment]
Sure, for example you could do
```
resource "confluent_role_binding" "subject-example-rb" {
  principal   = "User:${confluent_service_account.example-sa.id}"
  role_name   = "DeveloperRead"
  crn_pattern = "${data.confluent_schema_registry_cluster.example.resource_name}/subject=test_*"
}
```
or
```
resource "confluent_role_binding" "subject-example-rb" {
  principal   = "User:${confluent_service_account.example-sa.id}"
  role_name   = "DeveloperRead"
  crn_pattern = "${data.confluent_schema_registry_cluster.example.resource_name}/subject=test"
}
```

Let me know whether it helps!

**Comment by linouk23** [comment]
cc @javiervelamindcurv

**Comment by javiervelamindcurv** [comment]
It worked.

Thanks @linouk23
