### ISSUE TITLE
Changing the credentials in confluent_kafka_acl can lead to unusable state

### ISSUE THREAD

**Issue by Noel-Jones** [confluentinc/terraform-provider-confluent#162]
As a bit of background, I wondered why I should not use the cloud API key that has Organisation Admin role to manage the ACLs. I mean, I can log on to the web and manage ACLs using my sign on, which only has Organisational Admin, so why do I need to create a service manager account with Cloud Admin role and an API key to then grant an ACL to itself? Apart from anything, it means that when I give the API key to the application, the application will have Cloud Admin rights, which I don't want to give it.

Anyway, this led me to try changing the credentials used in the acl resource from the service manager account to the terraform manager cloud account. The apply output for one of the acls resources was thus:

````
confluent_kafka_acl.cc_service_cg["SIT"]: Modifying... [id=lkc-xxxxx/GROUP#sit-od-cloud-apps-ohs-cg#LITERAL#User:sa-xxxxx#*#READ#ALLOW]
╷
│ Error: error reading Kafka ACLs: 401 Unauthorized: Unauthorized
│
````

Subsequently it was not possible to correct the credential since every access came back with 401 unauthorised. The ACL itself was still present and worked fine. The state appears to have been updated with the new credentials, while no change was made to the ACL. Crucially though, no check has been made that the credentials are adequate to subsequently read or manage the ACL. My only option was to delete all of the state entries and then terraform could recreate them.

I'm sure there is a sound technical reason for needing to pass credentials into the resource but this does not seem to me to be the way things are usually done in Terraform. The provider should give all of the access needed to do things. Yes I could pass in the kafka api values to the provider but this would mean I need a provider per cluster, which takes me back to needing another account per cluster in order to manage the cluster. It would all be much simpler if a Cloud API key with Organisation Admin role could manage ACLs on the clusters.

And failing this, when modifying credentials the resource should verify that the new credentials work before storing them.

**Comment by linouk23** [comment]
Thanks for creating this issue @Noel-Jones!

Sounds like there're quite a few questions:

> My only option was to delete all of the state entries and then terraform could recreate them.

There was another option that is described in our docs:
![image](https://user-images.githubusercontent.com/5459870/210579750-8ccecc68-5106-401c-a62c-e7548e3c0cba.png)
[link](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_acl)

> And failing this, when modifying credentials the resource should verify that the new credentials work before storing them.

That's a reasonable piece of advice, we'll try to add it to our roadmap 👍 . Alternatively, we could recommend managing resources via [managing-single-cluster](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/managing-single-cluster) that makes secrets rotation a little bit easier.

>  It would all be much simpler if a Cloud API key with Organisation Admin role could manage ACLs on the clusters.

That's right, unfortunately there're some technical challenges. On a related note, once / if we support [OAuth 2.0](https://docs.confluent.io/cloud/current/access-management/authenticate/oauth/overview.html#oauth-2-0-flow) with TF you should be able to manage all the resources without all the API Keys.

Let me know whether it helps.

**Comment by Noel-Jones** [comment]
Thanks for the response Kostya. I appreciate the pointer on how to avoid deleting the state entries. I hadn't realised that the refresh could be disabled and can see that would likely have got me out of the jam. I think I may head down the managing single clusters route. I'm going to refactor the codebase a bit so that I manage the clusters and create the necessary management accounts in one pipeline and then they will be available for the application pipelines to manage my existing application service accounts. I look forward to the  OAuth2.0 support which will I think make everything a little less complex and easier to understand. Your help is much appreciated.

**Comment by linouk23** [comment]
You're welcome!

> I think I may head down the managing single clusters route.

That's a super smart idea! In fact, we might be able to release a new version of TF Provider for Confluent that will include quite a few of new examples for this option.
