### ISSUE TITLE
how to return secret key after creation of kafka_api-key

### ISSUE THREAD

**Issue by Davinder2609** [confluentinc/terraform-provider-confluent#163]

**Comment by linouk23** [comment]
Thanks for creating an issue @Davinder2609!

Let's say your TF config looks like this:
```
resource "confluent_api_key" "app-manager-kafka-api-key" {
  display_name = "app-manager-kafka-api-key"
  description  = "Kafka API Key that is owned by 'app-manager' service account"
  owner {
    id          = confluent_service_account.app-manager.id
    api_version = confluent_service_account.app-manager.api_version
    kind        = confluent_service_account.app-manager.kind
  }

  managed_resource {
    id          = confluent_kafka_cluster.basic.id
    api_version = confluent_kafka_cluster.basic.api_version
    kind        = confluent_kafka_cluster.basic.kind

    environment {
      id = confluent_environment.staging.id
    }
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

then you could use
```
confluent_api_key.app-manager-kafka-api-key.secret
```

to reference its Secret part.

**Comment by Davinder2609** [comment]
@linouk23 
Its displaying like this-kafka_api_keys = <sensitive>
But I need value,that I need to use as input for other application

**Comment by linouk23** [comment]
```
resource "confluent_api_key" "app-manager-kafka-api-key" {
  display_name = "app-manager-kafka-api-key"
  description  = "Kafka API Key that is owned by 'app-manager' service account"
  owner {
    id          = confluent_service_account.app-manager.id
    api_version = confluent_service_account.app-manager.api_version
    kind        = confluent_service_account.app-manager.kind
  }

  managed_resource {
    id          = confluent_kafka_cluster.basic.id
    api_version = confluent_kafka_cluster.basic.api_version
    kind        = confluent_kafka_cluster.basic.kind

    environment {
      id = confluent_environment.staging.id
    }
  }

  lifecycle {
    prevent_destroy = true
  }
}

output "value" {
   value = confluent_api_key.app-manager-kafka-api-key.secret
}
```

by using `confluent_api_key.app-manager-kafka-api-key.secret` you'd be able to reference its value.

**Comment by Davinder2609** [comment]
@linouk23 
resource "confluent_service_account" "app-consumer" {
  display_name = "app-consumer"
  description  = "Service account to consume from 'orders' topic of 'inventory' Kafka cluster"
}

resource "confluent_api_key" "app-consumer-kafka-api-key" {
  display_name = "app-consumer-kafka-api-key"
  description  = "Kafka API Key that is owned by 'app-consumer' service account"
  owner {
    id          = confluent_service_account.app-consumer.id
    api_version = "iam/v2"
    kind        = "User"
  }

  managed_resource {
    id          = "*****"
    api_version = "cmk/v2"
    kind        = "Cluster"

    environment {
      id = "*****"
    }
  }
  lifecycle {
    prevent_destroy = true
  }
}


output "kafka_api_keys" {
  value = confluent_api_key.app-consumer-kafka-api-key.secret
  sensitive = true
}

**Comment by linouk23** [comment]
Cool, your code snippet looks reasonable to me. Is there something you want to improve with it?

Looks like `terraform output kafka_api_keys` should output the value of an API Key Secret.

**Comment by Davinder2609** [comment]
but I am getting output value like this
kafka_api_keys = sensitive
but not getting secret value.

**Comment by linouk23** [comment]
Ohh I see, what if you try `terraform output -json kafka_api_keys `? cc @Davinder2609

**Comment by Davinder2609** [comment]
Yes thanks.
