### ISSUE TITLE
Schema Registry ID is misleading / URL not provided as a parameter

### ISSUE THREAD

**Issue by FireDrunk** [confluentinc/terraform-provider-confluent#169]
The value provided by the confluent_schema_registry_cluster.id field does not represent the URL that the Schema Registry is available on. The actual URL contains a different ID that is not resolvable via any (known) parameter.

The object:
```terraform
"schema_registry_cluster" = {
    "api_version" = "srcm/v2"
    "display_name" = "Stream Governance Package"
    "environment" = tolist([
      {
        "id" = "env-*****"
      },
    ])
    "id" = "lsrc-*****"
    "kind" = "Cluster"
    "package" = "ESSENTIALS"
    "region" = tolist([
      {
        "id" = "sgreg-9"
      },
    ])
    "resource_name" = "crn://confluent.cloud/organization=*redacted*/environment=env-*****/schema-registry=lsrc-*****"
    "rest_endpoint" = "https://psrc-*****.westeurope.azure.confluent.cloud"
  }
```
I want to know the `psrc-*****` id, to add the URL to different configuration in other parts of Terraform.

My proposal: Add another field to represent the 'other' ID with a proper description.

**Comment by lzyLuke** [comment]
Seems this is the issue between physical id vs logical id. Usually, we do not show our physical id to our customers. But maybe I am wrong. @linouk23 may have more contexts here.

**Comment by linouk23** [comment]
@FireDrunk thanks for creating this issue! What's the use case for using `psrc` ID and not `lsrc-` ID?

**Comment by FireDrunk** [comment]
I need to know the psrc-id to add it to our Private DNS zone because the Schema Registry is in the same DNS zone as the private endpoints. Because of that, our Private DNS zone responds with an NXDOMAIN on the Schema Registry's URL. By manually adding the record, everything works again.

I know it's not the prettiest setup, but Confluent hosting both private and public endpoints in the same DNS Zone is giving us severe headaches.

**Comment by linouk23** [comment]
I see, we've got a pretty similar setup with Kafka cluster IDs (`lkc` vs `pkc`) so in order to be consistent we'd have to add `other` IDs there as well which sounds like a tall order. Let's say we'll support on-prem Kafka clusters -- `other` attribute won't be super relevant.

All that to say, our recommendation would be to use a regular expression to extract pkc ID from `rest_endpoint` 😕
