### ISSUE TITLE
Can't import existing api-keys

### ISSUE THREAD

**Issue by mallie-su** [confluentinc/terraform-provider-confluent#17]
Hello,

Switching from confluentcloud 0.5.0 went smoothly! Now I want to add support for api key generation.
The problem is: I don't want to recreate existing API keys, as the users of our clusters are actively using them.

The [doc](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_api_key) doesn't describe how to import the key in our tfstate.

Is there a way to do it? I suppose that's not possible atm, as the error message while trying to import one key is quiet descriptive:
`Error: resource confluent_api_key doesn't support import`

Is it possible for you to implement it? Or is it "by-design"?

**Comment by linouk23** [comment]
@mallie-su thanks for opening an issue! That's very exciting you've proactively migrated to `0.7.0` and it went smoothly for you!

We're thinking about adding an import functionality for `confluent_api_key` but it's not supported at the moment.

One hacky thing you could do right now is to _fake_ an import (I'll use Kafka API Key as an example) by:
1. Adding its config to your TF configuration file (`main.tf`):
```
# Adjust the variables
resource "confluent_api_key" "app-producer-kafka-api-key" {
  display_name = "app-producer-kafka-api-key"
  description  = "Kafka API Key that is owned by 'app-producer' service account"
  owner {
    id          = confluent_service_account.app-producer.id
    api_version = confluent_service_account.app-producer.api_version
    kind        = confluent_service_account.app-producer.kind
  }

  managed_resource {
    id          = confluent_kafka_cluster.basic.id
    api_version = confluent_kafka_cluster.basic.api_version
    kind        = confluent_kafka_cluster.basic.kind

    environment {
      id = confluent_environment.staging.id
    }
  }
}
```
2. Adding it to TF state file (`terraform.tfstate`):
```
{
      "mode": "managed",
      "type": "confluent_api_key",
      "name": "app-producer-kafka-api-key",
      "provider": "provider[\"registry.terraform.io/confluentinc/confluent\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "description": "Kafka API Key that is owned by 'app-producer' service account",
            "display_name": "app-producer-kafka-api-key",
            "id": "WI34H6UO111111111",
            "managed_resource": [
              {
                "api_version": "cmk/v2",
                "environment": [
                  {
                    "id": "env-abc-123"
                  }
                ],
                "id": "lkc-xyz123",
                "kind": "Cluster"
              }
            ],
            "owner": [
              {
                "api_version": "iam/v2",
                "id": "sa-abc123",
                "kind": "ServiceAccount"
              }
            ],
            "secret": "***REDACTED***"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "confluent_environment.staging",
            "confluent_kafka_cluster.basic",
            "confluent_service_account.app-producer"
          ]
        }
      ]
    },
```

and then run `terraform plan` 🤞 

Let me know if it helps!

**Comment by mallie-su** [comment]
The hacky way works like a charm! Not quiet user friendly, espcially with a remote state, but eh, it works!
But I do think that the feature to import the keys would be much easier 😉 

Thanks a lot @linouk23!

**Comment by linouk23** [comment]
That's great to hear!

> But I do think that the feature to import the keys would be much easier 😉

For sure, I'll keep this issue open until we add it.

**Comment by sc-alistairdeneys** [comment]
I'd like to +1 this feature request.

I'm in the process of migrating our Confluent configuration to Terraform and it would be great if we could manage all resources, including API keys, in Terraform.

**Comment by linouk23** [comment]
@mallie-su @sc-alistairdeneys my team discussed this issue internally and I'm happy to let you know that we'll add this functionality in our upcoming `0.8.0` release.

**Comment by linouk23** [comment]
@mallie-su @sc-alistairdeneys @Talgatele we're happy to let you know that we've implemented an import for `confluent_api_key` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_api_key#import) in our latest `0.8.0` [release](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#080-may-12-2022).

**Comment by sc-alistairdeneys** [comment]
Fantastic! Thanks for the notification @linouk23
