### ISSUE TITLE
how to get Account ID of service account 

### ISSUE THREAD

**Issue by Davinder2609** [confluentinc/terraform-provider-confluent#170]

**Comment by lzyLuke** [comment]
Hi, you could use our cloud API to get all of your service accounts.
https://docs.confluent.io/cloud/current/api.html#tag/Service-Accounts-(iamv2)/operation/listIamV2ServiceAccounts

**Comment by Davinder2609** [comment]
I am trying to get through terraform,I need Account ID as input for other application.below code retrive every information except Account ID
data "confluent_service_account" "example_using_id" {
  id = "sa-****"
}

output "example_using_id" {
  value = data.confluent_service_account.example_using_id
}

output -
example_using_id = {
      + api_version  = "iam/v2"
      + description  = "This for testing purpose."
      + display_name = "KAFKA-automation-1"
      + id           = "sa-*****"
      + kind         = "ServiceAccount"

**Comment by lzyLuke** [comment]
I am confused...
```
output -
example_using_id = {
+ api_version = "iam/v2"
+ description = "This for testing purpose."
+ display_name = "KAFKA-automation-1"
+ id = "sa-*****"
+ kind = "ServiceAccount"
```
"sa-****" is the service account id (resource id). Could you provide more details about your "account ID", do you mean the integer id?

**Comment by Davinder2609** [comment]
Owner  visualization
Account Type Service Account
Account ID 410071
Resource ID sa-***

**Comment by Davinder2609** [comment]
want to retrive Account ID 410071

**Comment by Davinder2609** [comment]
Thanks!

**Comment by ilian** [comment]
@linouk23 I added a related issue #242. My use-case is to create ACLs with a vendor-neutral Kafka provider.
