### ISSUE TITLE
Schema Reference - not adding reference to existing schemas

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluent#176]
I am trying to add existing schema references to a new schema that I am creating.  Below is the code

```
resource "confluent_schema" "topic-schema" {
  schema_registry_cluster {
    id = data.confluent_schema_registry_cluster.public.id
  }

  rest_endpoint = data.confluent_schema_registry_cluster.public.rest_endpoint
  subject_name  = var.subject_name
  format        = var.schema_format
  schema        = file(var.schema_file_name)

  schema_reference {
    name         = "test1"
    subject_name = "test1.proto"
    version      = 2
  }

  schema_reference {
    name         = "test2"
    subject_name = "test2.proto"
    version      = 1
  }


  credentials {
    key    = var.schema_registry_credentails["schema_registry_key"]
    secret = var.schema_registry_credentails["schema_registry_secret"]
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

After the schema gets created , I don't see the reference to the other schemas.  Both test1 and test2 are valid schema subjects that exist. 

---
![Screen Shot 2023-01-23 at 5 08 55 PM](https://user-images.githubusercontent.com/11997472/214172739-ba59db9d-17ab-4269-bdf5-0fe1c017c6a3.png)

**Comment by linouk23** [comment]
@bluedog13 thanks for creating an issue! It looks like there might be a typo in your config, could you try this one?

```
resource "confluent_schema" "topic-schema" {
  schema_registry_cluster {
    id = data.confluent_schema_registry_cluster.public.id
  }

  rest_endpoint = data.confluent_schema_registry_cluster.public.rest_endpoint
  subject_name  = var.subject_name
  format        = var.schema_format
  schema        = file(var.schema_file_name)

  schema_reference {
    name         = "test1.proto"
    subject_name = var.subject_name
    version      = 2
  }

  schema_reference {
    name         = "test2.proto"
    subject_name = var.subject_name
    version      = 1
  }


  credentials {
    key    = var.schema_registry_credentails["schema_registry_key"]
    secret = var.schema_registry_credentails["schema_registry_secret"]
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

You might also want to take a look at [multiple-event-types-proto-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-proto-schema) example.

Let me know if it helps!

**Comment by bluedog13** [comment]
Thanks.

Is the subject name in the child "schema_reference" block same as the subject_name in the "confluent_schema" block?

**Comment by bluedog13** [comment]
Yes, the above link is what I was referring too as well.  The subject names are different in the parent and child blocks.  The main one looks like the schema that is getting created and the child ones looks like the reference schema name blocks.

```
  subject_name = "customer-event-value"
  format = "PROTOBUF"
  schema = file("./schemas/proto/customer_event.proto")

  schema_reference {
    name         = "purchase.proto"
    subject_name = confluent_schema.purchase-v1.subject_name
    version      = confluent_schema.purchase-v1.version
  }
  schema_reference {
    name         = "page_view.proto"
    subject_name = confluent_schema.page-view-v1.subject_name
    version      = confluent_schema.page-view-v1.version
  }
```

**Comment by linouk23** [comment]
That's right! It's a subject name that referenced schema belongs to. Also you might want to use 

[Option #2: Manage a single Schema Registry cluster in the same Terraform workspace](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema#option-2-manage-a-single-schema-registry-cluster-in-the-same-terraform-workspace)

```
provider "confluent" {
  schema_registry_id            = var.schema_registry_id            # optionally use SCHEMA_REGISTRY_ID env var
  schema_registry_rest_endpoint = var.schema_registry_rest_endpoint # optionally use SCHEMA_REGISTRY_REST_ENDPOINT env var
  schema_registry_api_key       = var.schema_registry_api_key       # optionally use SCHEMA_REGISTRY_API_KEY env var
  schema_registry_api_secret    = var.schema_registry_api_secret    # optionally use SCHEMA_REGISTRY_API_SECRET env var
}

resource "confluent_schema" "avro-purchase-v1" {
  subject_name = "avro-purchase-value"
  format = "AVRO"
  schema = file("./schemas/avro/purchase.avsc")

  lifecycle {
    prevent_destroy = true
  }
}
```

**Comment by linouk23** [comment]
Let me know if it works now.

**Comment by bluedog13** [comment]
I am confused. 

The schema I am trying to create is:  var.subject_name = myschema.
The 2 reference schemas are 
1. test1.proto
2. test2.proto

So is the below not correct
```
resource "confluent_schema" "topic-schema" {
  schema_registry_cluster {
    id = data.confluent_schema_registry_cluster.public.id
  }

  rest_endpoint = data.confluent_schema_registry_cluster.public.rest_endpoint
  subject_name  = var.subject_name. # myschema
  format        = var.schema_format
  schema        = file(var.schema_file_name)

  schema_reference {
    name         = "test1.proto"
    subject_name = var.subject_name
    version      = 2
  }

  schema_reference {
    name         = "test2.proto"
    subject_name = var.subject_name
    version      = 1
  }


  credentials {
    key    = var.schema_registry_credentails["schema_registry_key"]
    secret = var.schema_registry_credentails["schema_registry_secret"]
  }

  lifecycle {
    prevent_destroy = true
  }
}

```

**Comment by linouk23** [comment]
OK what I'm saying is instead of

```
  schema_reference {
    name         = "test1"
    subject_name = "test1.proto"
    version      = 2
  }

  schema_reference {
    name         = "test2"
    subject_name = "test2.proto"
    version      = 1
  }
```

it should be something like
```
  schema_reference {
    name         = "test1.proto"
    subject_name = "bar"
    version      = 2
  }

  schema_reference {
    name         = "test2.proto"
    subject_name = "foo"
    version      = 1
  }
```

**Comment by bluedog13** [comment]
So the "name" and the "subject_name" should be different?

What actually does the "name" and subject_name" stand for in the schema_reference block?  Perhaps this is where the confusion is.

**Comment by linouk23** [comment]
See [the docs](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema):
![image](https://user-images.githubusercontent.com/5459870/214175896-45869864-54b9-45d2-aa84-bbd13ff8055e.png)

**Comment by bluedog13** [comment]
Thanks.
I did read this. I have gone through all the examples and documentation before implementing and creating this issue. 

Having "subject_name" twice in the same block parent,  do they mean the same thing or different is where I am confused.  If they are different,  can the explanation in the above documentation be made more clear?

**Comment by linouk23** [comment]
Oh seems like there's a typo in the docs, that should be the right version:

[schema_reference](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema#schema_reference) - (Optional List) The list of referenced schemas (see [Schema References](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#schema-references) for more details):
* [subject_name](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema#name) - (Required String) The name of the subject, representing the subject under which the referenced schema is registered.
* [name](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema#subject_name) - (Required String) The name for the reference. (For Avro Schema, the reference name is the fully qualified schema name, for JSON Schema it is a URL, and for Protobuf Schema, it is the name of another Protobuf file.)
* [version](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema#version) - (Required Integer) The version, representing the exact version of the schema under the registered subject.

**Comment by linouk23** [comment]
@bluedog13 does this doc make sense now?

**Comment by bluedog13** [comment]
For my example...... is this correct

I have 2 existing subjects. (below are the exact subject names)

1. Common.proto
2. Metadata.proto

I want to add them as reference.  Is the below correct?
```
schema_reference {
    name         = "Common"
    subject_name = "Common.proto"
    version      = 2
  }

  schema_reference {
    name         = "Metadata"
    subject_name = "Metadata.proto"
    version      = 1
  }

```

**Comment by linouk23** [comment]
I think you might want
```
schema_reference {
    subject_name = "Common"
    name = "Common.proto"
    version      = 2
  }

  schema_reference {
    subject_name  = "Metadata"
    name = "Metadata.proto"
    version      = 1
  }
```

instead.

**Comment by bluedog13** [comment]
I am very lost.  

Is "subject_name" just any random string?  If I am creating a new schema called "myschema-subject",  does this value need to be in the below block?

```
  schema_reference {
    subject_name  = "[Is this any random string/ what value should go here/ or myschema-subject]"
    name = "Metadata.proto"
    version      = 1
  }
```

**Comment by linouk23** [comment]
> [subject_name](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema#name) - (Required String) The name of the subject, representing the subject under which the referenced schema is registered.

**Comment by bluedog13** [comment]
It will help, if this can be explained using my example.  I am finding it very hard to understand the documentation and referring to the same documentation here as answer is not helping me.  

If we cannot continue the conversation using my example above - we can stop here.  Thanks for your time.

**Comment by linouk23** [comment]
Sure thing, based on your explanation, it seems like you should set `subject_name  = myschema-subject`.

Are there any other subjects in your SR cluster?

**Comment by linouk23** [comment]
cc @bluedog13

**Comment by bluedog13** [comment]
This is from the latest [example](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/multiple-event-types-proto-schema/main.tf)

<img width="827" alt="Screen Shot 2023-01-23 at 6 11 15 PM" src="https://user-images.githubusercontent.com/11997472/214180734-245372cc-f3ab-47ce-a925-e9ddefa6231b.png">

Observations
1. Lines 301 and 306 are not the same as line 296
2. page_view.proto and purchase.proto are file names, but the path to the file name is not given, just the file name (lines 301 and 306).  So are they just random string?

So in my case, below cannot be true
```
subject_name  = myschema-subject
```


Below is the screen shot
----
![Screen Shot 2023-01-23 at 6 13 37 PM](https://user-images.githubusercontent.com/11997472/214181017-71f59847-597a-438c-8f00-91b8511fb1f2.png)

**Comment by linouk23** [comment]
Oh I see, I didn't expect a subject called `Common.proto` (e.g., I feel like just `Common` / `common` are more popular).

OK in this case it might be a good idea to try:
```
schema_reference {
    subject_name = "Common.proto"
    name = "common.proto"
    version      = 2
  }

  schema_reference {
    subject_name  = "Metadata.proto"
    name = "metadata.proto"
    version      = 1
  }
```


> page_view.proto and purchase.proto are file names, but the path to the file name is not given, just the file name (lines 301 and 306).

You might find more details [here](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-protobuf.html#developer-notes) but AFAIK it's just the name of the file for proto schemas.

> Lines 301 and 306 are not the same as line 296

Correct, AFAIK it might be possible to reference schemas from different subjects which is why they're different.

Let me know if it helps!

**Comment by linouk23** [comment]
cc @bluedog13

**Comment by bluedog13** [comment]
It's not working for me yet.  I am in the process of creating new schemas and adding reference.

**Comment by linouk23** [comment]
Cool, I'd be interested to look at the example of your schema so I could reproduce / fix the problem.

**Comment by bluedog13** [comment]
This isn't working for me.  I tried a complete new example. 

Below is my workflow.

1. Created a new schema using the file ./schemas/proto/mytopic-value_v1.proto
2. A new schema by name (subject_name)  "mynamespace-myapp-mytopic-dev-private-value" was created using the above file  (works as expected)

3. Created a second schema that references the above schema (with subject_name as mynamespace-myapp-myothertopic-dev-private-value)
4.  The TF plan output shows the reference details in this new schema
```
+ schema_reference {
          + name         = "mytopic-value_v1.proto"
          + subject_name = "mynamespace-myapp-mytopic-dev-private-value"
          + version      = 6
        }
```
5. But the newly created schema does not seems to include the reference in the schema registry
<img width="999" alt="Screen Shot 2023-01-24 at 1 47 22 PM" src="https://user-images.githubusercontent.com/11997472/214393547-8c3c6a36-82f4-41d0-9b65-a2d28982d78e.png">

Not sure what I am missing.

**Comment by linouk23** [comment]
Thanks for including an example! I'll try to look a little bit later today / tomorrow.

**Comment by bluedog13** [comment]
If it helps, the contents of the 2 proto files are

1. $ cat mytopic-value_v1.proto
```
syntax = "proto3";

package io.confluent.developer.proto;
option java_outer_classname = "PurchaseProto";

message Purchase {
  string item = 1;
  double amount = 2;
  string customer_id = 3;
}
```

2. $ cat myothertopic-value_v1.proto
```
syntax = "proto3";

package io.confluent.developer.proto;
option java_outer_classname = "PaymentDetailsProto";

message PaymentDetails {
   bool credit = 1;
   bool in_person = 2;
}
```

**Comment by bluedog13** [comment]
Update
------

Even though the schema reference is not being shown in the file (as indicated above), when you try to destroy it without deleting the referenced schema first, one's see the below error (as expected)
```
##[error]╷
│ Error: error soft deleting Schema "lsrc-vkjz5/mynamespace-myapp-mytopic-dev-private-value/100642": 422 Unprocessable Entity: One or more references exist to the schema {magic=1,keytype=SCHEMA,subject=mynamespace-myapp-mytopic-dev-private-value,version=6}.
```

**My guess is - schema reference functionality is not updating the contents of the .proto file in the Schema Registry with references when it's getting deployed. This may be the issue on the Terraform side.**

**Comment by linouk23** [comment]
@bluedog13 thanks for the message? I'm currently a little bit busy with all the other issues but will try to take a look at this one soon.

**Comment by bluedog13** [comment]
In your updated examples you added the import statement in the .proto files.  This is what was missing. 

This confirms that adding schema reference in the Terraform is not the solution alone, but the "import" statement/s must also be added in the .proto file.

**Comment by linouk23** [comment]
Oh that's right, does it work when you add `imports`?

BTW there's also a somewhat relevant https://github.com/confluentinc/terraform-provider-confluent/issues/181#issuecomment-1422124935

**Comment by linouk23** [comment]
cc @bluedog13 feel free to close this issue if our updated examples work for you now 👌

**Comment by bluedog13** [comment]
Seems to work - because I was confused as to how without import statement in the protofile the schema reference was working earlier, and TF was not (or does not) add that as well. 

I'll close this because the confusion is now cleared.
