### ISSUE TITLE
EOF error when working with confluent_kafka_topic resource

### ISSUE THREAD

**Issue by antoncyrol** [confluentinc/terraform-provider-confluent#178]
I can't get a minimal example creating a new topic working due to an unclear EOF error even though I spent quite some time researching it. My `main.tf` file (simplified to a minimal example) looks as follows:
```terraform
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.25.0"
    }
  }
}

provider "confluent" {
  kafka_id            = var.kafka_id
  kafka_rest_endpoint = var.kafka_rest_endpoint
  kafka_api_key       = var.kafka_api_key
  kafka_api_secret    = var.kafka_api_secret
}

resource "confluent_kafka_topic" "my_terraform_topic" {
    topic_name       = "my_terraform_topic"
    partitions_count = 1
}
```

where 
`kafka_id` = `XXX-XXXXX`, and
`kafka_rest_endpoint` = `https://YYY-YYYYY.germanywestcentral.azure.confluent.cloud:9092`. 
`kafka_api_key` and `kafka_api_secret` are 16 and 64 character long strings, respectively.

Upon `terraform apply`, I get the following error:

> Error: error creating Kafka Topic: Post "https://YYY-YYYYY.germanywestcentral.azure.confluent.cloud:9092/kafka/v3/clusters/XXX-XXXXX/topics": POST https://YYY-YYYYY.germanywestcentral.azure.confluent.cloud:9092/kafka/v3/clusters/XXX-XXXXX/topics giving up after 5 attempt(s): Post "https://YYY-YYYYY.germanywestcentral.azure.confluent.cloud:9092/kafka/v3/clusters/XXX-XXXXX/topics": **EOF**
> │ 
> │   with confluent_kafka_topic.my_terraform_topic,
> │   on main.tf line 17, in resource "confluent_kafka_topic" "my_terraform_topic":
> │   17: resource "confluent_kafka_topic" "my_terraform_topic" {

**What is going on here?**

Some more information:

I also tried to set 
```terraform
  cloud_api_key    = var.kafka_api_key
  cloud_api_secret = var.kafka_api_secret
```
(which should only be necessary for confluent_kafka_acl resources according to the docs, but I am not sure where to get the cloud api keys if the are different from the kafka api keys), but to no avail.

On the other hand, setting credentials for the schema registry and deploying schemas is working (showing that the general setup is working?), but I left it out here as it seem irrelevant.

Terraform version:
```bash
terraform --version
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/confluentinc/confluent v1.25.0
```

**Comment by antoncyrol** [comment]
If I try to import an existing topic, I get the same error from the Get request.

**Comment by linouk23** [comment]
@antoncyrol thanks for creating this issue!

It's pretty rare but we've seen this issues a few times already.

Could you try to use
```
provider "confluent" {
   max_retries = 10 # defaults to 4; or any other number other than 10
}
```

also could you please share your cluster ID (`lkc-xxxxx`) to `cflt-tf-access@confluent.io` so we could investigate on our side (backend / proxy setup) it as well?

**Comment by linouk23** [comment]
Let me know if it helps!

**Comment by antoncyrol** [comment]
The retries didn't help and I don't have any proxy, VPN, etc. in place.

However, your hint with the ports directly yields the solution:
The `kafka_rest_endpoint` must not include the port, i.e., using 
`https://YYY-YYYYY.germanywestcentral.azure.confluent.cloud` instead of 
`https://YYY-YYYYY.germanywestcentral.azure.confluent.cloud:9092` 
works without any retries. 

When you create an API key via the browser, the bootstrap server in the downloaded file includes the port, which is probably the reason some people like me get it wrong. Libraries like kstreams or the Confluent Python Kafka client accept (need?) the bootstrap server with the port.

Thanks for the quick and useful answer!

**Comment by linouk23** [comment]
@antoncyrol that's a great catch!

That's smart fix! Was `:9092` displayed in the UI or something? I wonder where `:9092` come from in the first place.

**Comment by antoncyrol** [comment]
You must not overlook the difference between the bootstrap server and the REST endpoint (and, somewhat misleading, you are only provided the bootstrap server in the .txt file that you may download when you create an API key for use with TF):

![CleanShot 2023-01-26 at 16 45 38@2x](https://user-images.githubusercontent.com/18127599/214881657-1868798f-d7db-469e-95c5-09e8383e9bb1.png)

I think it could be worth validating the kafka_rest_endpoint in the Terraform provider (check that it starts with _https://_ and ends with no or the correct port) if it is easily possible.
