### ISSUE TITLE
Validation Bug - invalid value for network.0.id (the network ID must be of the form 'n-' when actual network id starts 'nr-'

### ISSUE THREAD

**Issue by Marcus-James-Adams** [confluentinc/terraform-provider-confluent#18]
**Overview**
Successfully imported an existing  cluster in Azure UK south that has an existing private network link to an Azure sub also in UK South,
The error seems to suggest that the validation code for the two resources only validates as good network id's that start `n-` and incorrectly fails network id's that start `nr-`

**Environment**
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.14.0
+ provider registry.terraform.io/confluentinc/confluent v0.7.1
+ provider registry.terraform.io/hashicorp/azuread v2.22.0
+ provider registry.terraform.io/hashicorp/azurerm v3.4.0
+ provider registry.terraform.io/hashicorp/random v3.1.3

**Error**
 on future plan or apply I get the messages
> confluent_environment.main: Refreshing state... [id=env-ok***]
> confluent_network.main: Refreshing state... [id=nr-4y***]
> confluent_kafka_cluster.main: Refreshing state... [id=lkc-qn***]
> confluent_private_link_access.main: Refreshing state... [id=pla-ew***]

>----------------------SNIP-------------------------------<

> │ Error: invalid value for network.0.id (the network ID must be of the form 'n-')
> │
> │   with confluent_kafka_cluster.main,
> │   on confluent.cloud.tf line 22, in resource "confluent_kafka_cluster" "main":
> │   22:             id =confluent_network.main.id
> │
> 
> │ Error: invalid value for network.0.id (the network ID must be of the form 'n-')
> │
> │   with confluent_private_link_access.main,
> │   on confluent.cloud.tf line 53, in resource "confluent_private_link_access" "main":
> │   53:     id = confluent_network.main.id

**Resources affected**

- confluent_kafka_cluster
- confluent_private_link_access

**Code Snippet**
```ebnf
resource "confluent_kafka_cluster" "main" {
  display_name = upper("${var.org_short}-${var.env_short}-${var.loc_short}-${var.service}")
  availability = var.confluent_cloud_cluster_avalability
  cloud        = "AZURE"
  region       = var.confluent_cloud_cluster_region
    dedicated {
    cku = var.confluent_cloud_cluster_cku
  }
    network {
	    id = confluent_network.main.id
    }
  environment {
    id = confluent_environment.main.id
  }
}

resource "confluent_network" "main" {
  display_name = "Private Link Network"
  cloud = "AZURE"
  region = var.confluent_cloud_cluster_region
  connection_types = ["PRIVATELINK"]
  environment {
    id = confluent_environment.main.id
  }
}

resource "confluent_private_link_access" "main" {
  display_name = "Azure Private Link Access"
  azure {
    subscription = var.subscription_id 
  }
  environment {
    id = confluent_environment.main.id
  }
  network {
    id = confluent_network.main.id
  }
}
```

**Comment by linouk23** [comment]
👋 @Marcus-James-Adams thanks for opening an issue!

That's indeed a bug that we'll address in our next release.

So there're 2 options:
1. Wait for the next release until we remove that validation.
2. If that's an option, create a new PL cluster (all _new_ networks will have `n-` prefix) and delete the existing one.

**Comment by Marcus-James-Adams** [comment]
@linouk23 This is affecting our clusters all the way through to prod, so removing the cluster is not an option, as our account manager knows we have been waiting for this for a long time. When is the next release due?  Could we get a 0.7.2 hotfix to pick it up.  Who does our account manager need to talk to in order to get it progressed?

**Comment by linouk23** [comment]
@Marcus-James-Adams ok so there're 2 problems:

1. Release `0.7.2` with removed validation -- that one is easy.
2. The other problem you might run into is https://github.com/confluentinc/terraform-provider-confluent/issues/14#issuecomment-1118588140.

As soon as 2 is resolved from our side, I'll notify you and we'll release `0.7.2.` accordingly.

Let me know if it helps.

**Comment by Marcus-James-Adams** [comment]
confirmed, if I delete and recreate the cluster via TF the new one comes with the correct network prefix "n-", however as you guessed we do hit #14 Which blocks us from using confluent under terraform.

**Comment by linouk23** [comment]
👍 , we merged the fix in the internal repo already and we'll see whether we'll be able to create a patch release early next week.

Speaking about this `http_endpoint` problem, let's continue talking about it in #14 👌, thanks!

**Comment by linouk23** [comment]
@Marcus-James-Adams we're happy to let you know that we've updated input validation for `confluent_private_link_access` and `confluent_kafka_cluster` resources in our latest `0.8.0` [release](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#080-may-12-2022).
