### ISSUE TITLE
Normalize schema before update

### ISSUE THREAD

**Issue by PSanetra** [confluentinc/terraform-provider-confluent#181]
Our schemas (migrating from Azure schema registry) contain a namespace in each nested record or enum. The confluent schema registry strips those nested namespace declarations. Therefore the terraform provider detects this as a change on every `terraform plan`.

## Example

Local schema:
```
{
  name: "MySchema",
  namespace: "com.example",
  type: "record",
  fields: [
    {
      name: "SomeField",
      type: "string"
    },
    {
      name: "SomeNestedRecord",
      type: {
        name: "MyNestedRecordName",
        namespace: "com.example",
        type: "record",
        fields: [
          {
            name: "MyNestedField",
            type: "string"
          }
        ]
      }
    }
  ]
}
```

Persisted schema (nested namespace is missing):
```
{
  name: "MySchema",
  namespace: "com.example",
  type: "record",
  fields: [
    {
      name: "SomeField",
      type: "string"
    },
    {
      name: "SomeNestedRecord",
      type: {
        name: "MyNestedRecordName",
        type: "record",
        fields: [
          {
            name: "MyNestedField",
            type: "string"
          }
        ]
      }
    }
  ]
}
```

## Discussion

I expect this is not a big issue anymore, when it was possible to not delete schemas anymore on update of the `schema` field of the `confluent_schema` resource (I assume the update would be a noop in that case without creating any new version). (See discussion in https://github.com/confluentinc/terraform-provider-confluent/issues/124)

As hard schema deletion may not be an option (e.g. in event sourcing scenarios) this might be a big issue as every `terraform apply` soft deletes the schema and adds a new version that counts against the schema count limit of the schema registry. (See https://github.com/confluentinc/terraform-provider-confluent/issues/179#issue-1556865092)

It would be nice if the terraform provider had an option to normalize the schema that would be send to the schema registry, to be comparable to the persisted schema, so that it does not detect schema differences as changes that would be normalized by the schema registry anyway. Otherwise there is the risk that such a difference is not noticed by developers and all the `terraform apply` executions fill up the schema limit over time.

**Comment by linouk23** [comment]
Thanks for creating an issue @PSanetra!

Actually there're some checks for schema comparison already but these checks are definitely not smart enough to ignore differences in namespaces.

We'll investigate it and try to figure out a way how we could address it.

**Comment by linouk23** [comment]
It looks like there's such an API already so it seems doable to add it to TF: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject) 👍

**Comment by FabioBatSilva** [comment]
Also running into something similar with PROTOBUF.

Comments gets stripe out and some format changes are different when the provider reads the schema from the registry.


Here i'm running a plan on the exact same schema file/playload.
 
```
  ~ update in-place

Terraform will perform the following actions:

  # module.kafka.confluent_schema.schemas["examples.v1alpha.person-value"] will be updated in-place
  ~ resource "confluent_schema" "schemas" {
        id                 = "xxxx-xxxxx/examples.v1alpha.person-value/latest"
      ~ schema             = <<-EOT
            syntax = "proto3";
          + 
            package examples.v1alpha;
            
            import "chesscom/proto_options/kafka/v1alpha/kafka_options.proto";
            
          + // Some proto message.
          + // v=3
            message Person {
          -   option (proto_options.kafka.v1alpha.kafka) = {
          -   };
          - 
              string name = 1;
          + 
          +   option (proto_options.kafka.v1alpha.kafka) = {};
            }
        EOT
        # (7 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

```

**Comment by linouk23** [comment]
@PSanetra @FabioBatSilva we're aware of the issue and we're trying to figure out a smart way to fix it 👌

**Comment by PSanetra** [comment]
@linouk23 thank you for looking into this! As this issue recently produced a lot of new versions and soft deleted (I guess) the previous schema versions, do you know if there is some way to hard delete those versions once (if possible via the UI)? Doing this is currently ok for us as we are not yet using those schemas in production.

**Comment by linouk23** [comment]
@PSanetra you might find this _[Hard delete a schema](https://docs.confluent.io/platform/current/schema-registry/schema-deletion-guidelines.html#hard-delete-a-schema)_ doc useful.

**Comment by linouk23** [comment]
@FabioBatSilva @PSanetra I'm happy to let you know that the [latest](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.29.0) version of TF Provider resolves this issue. It includes

> checks for semantic (rather than syntactic) equivalence of schemas to avoid occasional Terraform drift during schema updates (https://github.com/confluentinc/terraform-provider-confluent/issues/181).
