### ISSUE TITLE
confluent_kafka_cluster type cannot be injected as a variable

### ISSUE THREAD

**Issue by laurence-hubbard** [confluentinc/terraform-provider-confluent#182]
confluent_kafka_cluster Resource choice between basic, standard and dedicated is an Optional Configuration Block instead of a list of accepted values for a single key.

This means the type cannot be injected as a variable, such as wanting to have different types in different environments when working with terraform workspaces

**Comment by linouk23** [comment]
Thanks for creating an issue!

Your question seems to be a duplicate of [this resolved issue](https://github.com/confluentinc/terraform-provider-confluentcloud/issues/52#issuecomment-1066914650).

Let me know if it helps!

**Comment by linouk23** [comment]
cc @laurence-hubbard

**Comment by laurence-hubbard** [comment]
That works for me thanks! 🙏
