### ISSUE TITLE
Bug: Cannot set default quota

### ISSUE THREAD

**Issue by Redid** [confluentinc/terraform-provider-confluent#183]
# Steps to reproduce

1. Create confluent_kafka_client_quota resource from [example usage](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_client_quota)
2. Swap principal to `["default"]` (`["Default"]` isn't working either)

# Expected result

Default quota is created

# Actual result

400 from API and Terraform timeout after 5 attempts

**Comment by linouk23** [comment]
@Redid thanks for creating an issue!

There's a typo in the docs (it'll be fixed in the next release). You should be using `"<default>"` instead.

Let me know if it helps!
