### ISSUE TITLE
Issues with refreshing API keys used for creating topics

### ISSUE THREAD

**Issue by rekaparathalwar** [confluentinc/terraform-provider-confluent#187]
We are refreshing our API keys.

We are facing the following issue.
The topic terraform state has reference to the old api key and secret. The terraform state file has multiple topics in it.

The old api key and secret is deleted already. So when I am trying create a new topic , I am getting error as 401 since terraform is trying to fetch the existing topics in the state file which has old api key and secret.

I expected the previous topics to be updated with the new API key and secret. 
However, it fails because it is attempting to refresh the existing state, which contains the outdated API keys.

How can we update the existing state file with new keys ( without manual updation). We have many state files for the topics. It will be very tedious and error prone to manually update the api key and secrets.

Any help will be appreciated since its impacting our production topics as well.

**Error message**
Error: 401 Unauthorized: Unauthorized

  with confluent_kafka_topic.topics["topic-1"],
  on main.tf line 22, in resource "confluent_kafka_topic" "topics":
  22: resource "confluent_kafka_topic" "topics" {

**Comment by linouk23** [comment]
Thanks for creating the issue @rekaparathalwar!

See [this doc](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic): ![image](https://user-images.githubusercontent.com/5459870/216118783-9a3ffcbf-11dd-4953-ad58-15ca058e6cb3.png) and let me know whether it helps.
