### ISSUE TITLE
how to use Terraform import in shell script.

### ISSUE THREAD

**Issue by Davinder2609** [confluentinc/terraform-provider-confluent#188]
We are trying below code,After terraform plan its prompt for variable values-
terraform init 
echo "Creating terraform plan....."
# Creation of terraform plan
terraform plan -var "confluent_kafka_cloud_api_key=$CONFLUENT_KAFKA_CLOUD_API_KEY" \              
-var "confluent_kafka_cloud_api_secret=$CONFLUENT_KAFKA_CLOUD_API_secret" \              
-var "confluent_kafka_env_id=$CONFLUENT_KAFKA_ENV_ID" \              
-var "confluent_kafka_cluster_id=$CONFLUENT_KAFKA_CLUSTER_ID" \              
-var "confluent_schema_cluster_id=$CONFLUENT_SCHEMA_CLUSTER_ID" \              
-var "confluent_kafka_cluster_rest_end_point=$CONFLUENT_KAFKA_CLUSTER_REST_END_POINT" \              
-var "confluent_kafka_service_account_name=kafka-automation-testing" \             
 -var "confluent_kafka_service_account_description=This is for testing purpose." \             
 -out output.terraform
echo "Execution of terraform main plan module to create service account and schema registry keys is completed."
sleep 5
# Importing service accont id.
terraform import confluent_service_account.ServiceAccount sa-****

**Comment by linouk23** [comment]
@Davinder2609 could you share your `main.tf` too?

**Comment by Davinder2609** [comment]
@linouk23, please find below for the main.tf file. I'm having problem in sending variables as command line arguments while creating terraform plan. This only occurs if i add the "terraform import confluent_service_account.ServiceAccount sa-****". I have added it before creating the plan. My end goal is to invoke the plan dynamically after adding the import so that i don't have to enter the variables manually.

shell script:

terraform init
echo "Creating terraform plan....."
# Importing service accont id.
terraform import confluent_service_account.ServiceAccount sa****
# Creation of terraform plan
terraform plan -var "confluent_kafka_cloud_api_key=$CONFLUENT_KAFKA_CLOUD_API_KEY" \              
-var "confluent_kafka_cloud_api_secret=$CONFLUENT_KAFKA_CLOUD_API_secret" \              
-var "confluent_kafka_env_id=$CONFLUENT_KAFKA_ENV_ID" \              
-var "confluent_kafka_cluster_id=$CONFLUENT_KAFKA_CLUSTER_ID" \              
-var "confluent_schema_cluster_id=$CONFLUENT_SCHEMA_CLUSTER_ID" \              
-var "confluent_kafka_cluster_rest_end_point=$CONFLUENT_KAFKA_CLUSTER_REST_END_POINT" \              
-var "confluent_kafka_service_account_name=testing" \              
-var "confluent_kafka_service_account_description=This is for testing purpose." \              
-out output.terraform
echo "Execution of terraform main plan module to create service account and schema registry keys is completed."
sleep 5


main.tf:

terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.22.0"
    }
  }
}

provider "confluent" {
  cloud_api_key    = var.confluent_kafka_cloud_api_key
  cloud_api_secret = var.confluent_kafka_cloud_api_secret
}

resource "confluent_service_account" "ServiceAccount" {
  display_name = var.confluent_kafka_service_account_name
  description  = var.confluent_kafka_service_account_description
}

resource "confluent_api_key" "kafka-cluster-api-key" {
  display_name = var.confluent_kafka_service_account_name
  description  = var.confluent_kafka_service_account_description
  owner {
    id          = confluent_service_account.ServiceAccount.id
    api_version = confluent_service_account.ServiceAccount.api_version
    kind        = "User"
  }

  managed_resource {
    id          = var.confluent_kafka_cluster_id
    api_version = "cmk/v2"
    kind        = "Cluster"

    environment {
      id = var.confluent_kafka_env_id
    }
  }
  lifecycle {
    prevent_destroy = true
  }
}

resource "confluent_api_key" "schema-registry-api-key" {
  display_name = var.confluent_kafka_service_account_name
  description  = var.confluent_kafka_service_account_description
  owner {
    id          = confluent_service_account.ServiceAccount.id
    api_version = confluent_service_account.ServiceAccount.api_version
    kind        = "User"
  }

  managed_resource {
    id          = var.confluent_schema_cluster_id
    api_version = "srcm/v2"
    kind        = "Cluster"

    environment {
      id = var.confluent_kafka_env_id
    }
  }

  lifecycle {
    prevent_destroy = true
  }
}

**Comment by linouk23** [comment]
Did you try using option #2 from [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#option-2-manage-a-single-kafka-cluster-in-the-same-terraform-workspace) or [here](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/basic-kafka-acls-with-alias)? This way you might not have to pass all these env vars @Davinder2609?

**Comment by linouk23** [comment]
Seems like my previous comment should help to resolve the issue but feel free to reopen it.
