### ISSUE TITLE
Error: error creating Kafka ACLs: 403 Forbidden

### ISSUE THREAD

**Issue by tocy1** [confluentinc/terraform-provider-confluent#189]
Unable to create acls or topic using CloudClusterAdmin Role on dedicated  cluster
```

╷
│ Error: error creating Kafka Topic: 403 Forbidden
│ 
│   with confluent_kafka_topic.orders,
│   on modules/confluent-kafka/main.tf line 132, in resource "confluent_kafka_topic" "orders":
│  132: resource "confluent_kafka_topic" "orders" {
│ 
╵
╷
│ Error: error creating Kafka ACLs: 403 Forbidden
│ 
│   with confluent_kafka_acl.app-connector-describe-on-cluster,
│   on modules/confluent-kafka/main.tf line 150, in resource "confluent_kafka_acl" "app-connector-describe-on-cluster":
│  150: resource "confluent_kafka_acl" "app-connector-describe-on-cluster" {
```
`[ dedicated-vpc-peering-aws-kafka-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-vpc-peering-aws-kafka-acls)` is the culprit here

**Comment by linouk23** [comment]
Thanks for creating an issue @tocy1!

Could you confirm you were running `dedicated-vpc-peering-aws-kafka-acls` when you run into this issue?

It seems like [role binding](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/dedicated-vpc-peering-aws-kafka-acls/main.tf#L95) wasn't synced (it might have taken too long or something -- as of now TF Provider waits for [90 seconds](https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/resource_role_binding.go#L35)). Could you rerun `terraform apply` and see whether it helps? FWIW there's `depends_on` [block](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/dedicated-vpc-peering-aws-kafka-acls/main.tf#L124-L130) already.

**Comment by linouk23** [comment]
That's interesting, could you 

1. Share the output of `terraform state list` command;
2. See whether CloudClusterAdmin role binding was created for a target service account?

cc @tocy1

**Comment by tocy1** [comment]
@linouk23 
data.aws_route_tables.rts
data.aws_vpc_peering_connection.accepter
data.confluent_schema_registry_region.essentials
aws_route.r["rtb-00fcdcfb34ee4c5d4"]
aws_route.r["rtb-02142e51a545b50c2"]
aws_route.r["rtb-049c605b5efc0cd3b"]
aws_route.r["rtb-0804a101fd1c6ce7e"]
aws_route.r["rtb-089540d6b3b374516"]
aws_route.r["rtb-0f6b225f353a31796"]
aws_vpc_peering_connection_accepter.peer
confluent_api_key.app-consumer-kafka-api-key
confluent_api_key.app-manager-kafka-api-key
confluent_api_key.app-producer-kafka-api-key
confluent_environment.staging
confluent_kafka_cluster.dedicated
confluent_network.peering
confluent_peering.aws
confluent_role_binding.app-manager-kafka-cluster-admin
confluent_schema_registry_cluster.essentials
confluent_service_account.app-consumer
confluent_service_account.app-manager
confluent_service_account.app-producer

**Comment by tocy1** [comment]
@linouk23  The state file for the role looks below
   {
      "mode": "managed",
      "type": "confluent_role_binding",
      "name": "app-manager-kafka-cluster-admin",
      "provider": "provider[\"registry.terraform.io/confluentinc/confluent\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "crn_pattern": "****",
            "id": "****",
            "principal": "User:sa-6wj0y8",
            "role_name": "CloudClusterAdmin"
          },
          "sensitive_attributes": [],
          "private": "****",
          "dependencies": [
            "confluent_environment.staging",
            "confluent_kafka_cluster.dedicated",
            "confluent_network.peering",
            "confluent_service_account.app-manager"
          ]
        }
      ]
    }

**Comment by linouk23** [comment]
Could you also attach the output of `terraform plan`?

**Comment by tocy1** [comment]
No changes for the confluent_role_binding.app-manager-kafka-cluster-admin

**Comment by tocy1** [comment]
@linouk23  I create a service account manually without any ACL for the `sa-**0y8`  on the cluster, then tried creating a topic using the API but the response is 403, see below

```
{
    "error_code": 403,
    "message": "API key 'C5******' is not allowed to access provided cluster ID 'lkc*****'"
} 
```

**Comment by tocy1** [comment]
+++

**Comment by linouk23** [comment]
Thanks, could you share

* service account ID
* target cluster ID where you tried to create a topic

to `cflt-tf-access@confluent.io`? @tocy1

**Comment by cdespona** [comment]
@tocy1 @linouk23 we had the same problem yesterday, not sure if something was changed on the provider (v1.28.0) or if it was a matter of time (which from my point of view would be really awful) but we are now able to create both topics and ACLs.

**Comment by linouk23** [comment]
@cdespona could you share your service account / Kafka API Key ID / target cluster ID with `cflt-tf-access@confluent.io`?

**Comment by tocy1** [comment]
@linouk23  This is the error now 
{
    "error_code": 40301,
    "message": "Authorization failed."
}

**Comment by linouk23** [comment]
Thanks, could you share

* service account ID
* target cluster ID where you tried to create a topic

to `cflt-tf-access@confluent.io`? @tocy1

**Comment by tocy1** [comment]
sure

**Comment by tocy1** [comment]
@linouk23 I have sent it
