### ISSUE TITLE
Getting POST errors while running tf scripts

### ISSUE THREAD

**Issue by VipulZopSmart** [confluentinc/terraform-provider-confluent#19]
I'm trying to run tf scripts for topic provisioing, service accounts with acls, those failds with this error.

```
Error: Post "https://api.confluent.cloud/iam/v2/service-accounts": POST https://api.confluent.cloud/iam/v2/service-accounts giving up after 5 attempt(s)
```

**Comment by linouk23** [comment]
@VipulZopSmart could you enable [debug logs](https://www.terraform.io/internals/debugging) and share them with us at `cflt-tf-access@confluent.io`? For example:

```
export TF_LOG_PATH="./logs.txt"
export TF_LOG=trace
terraform apply --auto-approve
```

Rerunning might also help since it looks like either `429 / 5**` error.

**Comment by linouk23** [comment]
@VipulZopSmart reported via email that

> There was some issue I encountered calling that endpoint, but after that it was working fine.

so I'm closing the issue.

**Comment by linouk23** [comment]
@VipulZopSmart reported via email that

> There was some issue I encountered calling that endpoint, but after that it was working fine.

so I'm closing the issue.
