### ISSUE TITLE
Error customizing diff Schema: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by FabioBatSilva** [confluentinc/terraform-provider-confluent#196]
I started seeing this error `customizing diff Schema: 422 Unprocessable Entity` after upgrading to 
https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.29.0

I a proto file that looks like this:
```protobuf
syntax = "proto3";

package examples.v1alpha;

import "proto_options/kafka/v1alpha/kafka_options.proto";

// Some proto message.
// v=3
message Person {
  string name = 1;

  option (proto_options.kafka.v1alpha.kafka) = {};
}
``` 

And a custom options that looks like this:
```protobuf
syntax = "proto3";

import "google/protobuf/descriptor.proto";

package proto_options.kafka.v1alpha;

message KafkaOptions {
  map<string, string> config = 2;
}

extend google.protobuf.MessageOptions {
  repeated KafkaOptions kafka = 80000;
}
```

After applying a change to a comment in the schema file:
```diff
  // Some proto message.
-// v=3
+// v=4
 message Person {
   string name = 1;
```

I get this error:
```
╷
│ Error: error customizing diff Schema: 422 Unprocessable Entity
│ 
│   with module.kafka.confluent_schema.schemas["examples.v1alpha.person-value"],
│   on .terraform/modules/kafka/modules/kafka-topic/main.tf line 69, in resource "confluent_schema" "schemas":
│   69: resource "confluent_schema" "schemas" {
│ 

```

debug logs logs
```
[DEBUG] provider.terraform-provider-confluent_1.29.0: Finished reading Schema "xxx-xxxxx/examples.v1alpha.person-value/latest": schema_id=xxx-xxxxx/examples.v1alpha.person-value/latest tf_provider_addr=provider @caller=src/github.com/confluentinc/terraform-provider-confluent/internal/provider/resource_schema.go:373 @module=provider tf_resource_type=confluent_schema tf_rpc=ReadResource tf_req_id=b9f5d916-0a5f-d670-9522-91adc1d755be timestamp=2023-02-09T15:47:27.976-0500
[DEBUG] provider.terraform-provider-confluent_1.29.0: Customizing diff new Schema: {"references":[],"schema":"syntax = \"proto3\";\n\npackage examples.v1alpha;\n\nimport \"proto_options/kafka/v1alpha/kafka_options.proto\";\n\n// Some proto message.\n// v=4\nmessage Person {\n  string name = 1;\n\n  option (proto_options.kafka.v1alpha.kafka) = {};\n}","schemaType":"PROTOBUF"}: @module=provider tf_provider_addr=provider @caller=src/github.com/confluentinc/terraform-provider-confluent/internal/provider/resource_schema.go:209 tf_req_id=b6f0b108-c337-6f90-5d75-6a71a46d9fb6 tf_resource_type=confluent_schema tf_rpc=PlanResourceChange timestamp=2023-02-09T15:47:27.980-0500
[DEBUG] provider.terraform-provider-confluent_1.29.0: 2023/02/09 15:47:27 [DEBUG] POST https://xxx-xxxxx.us-central1.gcp.confluent.cloud/subjects/examples.v1alpha.person-value?normalize=true
[ERROR] vertex "module.kafka.confluent_schema.schemas[\"examples.v1alpha.person-value\"]" error: error customizing diff Schema: 422 Unprocessable Entity
[ERROR] vertex "module.kafka.confluent_schema.schemas (expand)" error: error customizing diff Schema: 422 Unprocessable Entity
module.kafka.data.confluent_kafka_cluster.cluster: Read complete after 1s [id=xxx-xxxxx]

```

**Comment by FabioBatSilva** [comment]
It looks like removing the option will cause the error to stop. :thinking:  
```
  # module.kafka.confluent_schema.schemas["examples.v1alpha.person-value"] will be updated in-place
  ~ resource "confluent_schema" "schemas" {
        id                 = "xxxx-xxxx/examples.v1alpha.person-value/latest"
      ~ schema             = <<-EOT
            syntax = "proto3";
            
            package examples.v1alpha;
            
            import "proto_options/kafka/v1alpha/kafka_options.proto";
            
            // Some proto message.
          - // v=3
          + // v=4
            message Person {
              string name = 1;
          - 
          -   option (proto_options.kafka.v1alpha.kafka) = {};
            }
        EOT
        # (7 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

**Comment by linouk23** [comment]
Could you share the contents of 
```
"proto_options/kafka/v1alpha/kafka_options.proto"
```
or replace it with something else?

**Comment by FabioBatSilva** [comment]
@linouk23 Thanks for looking into it..

Updated the description to include the custom option

**Comment by linouk23** [comment]
@FabioBatSilva thanks! Did you also try to evolve the schema in the same way via the UI? It looks like an API problem to me 🤔

**Comment by FabioBatSilva** [comment]
Via the UI the comments gets removed when the first version is saved..

But i'm able to evolve if a add a new field..

```protobuf
syntax = "proto3";
package examples.v1alpha;

import "proto_options/kafka/v1alpha/kafka_options.proto";

message Person {
  option (proto_options.kafka.v1alpha.kafka) = {
  };

  string name = 1;
  string name2 = 2;
}
```
Doing the same via TF also triggers the error..

**Comment by FabioBatSilva** [comment]
To clarify..

It looks like it happens to any change where I have the option in place.. 

For instance:
```diff
 message Person {
   string name = 1;
+  string name2 = 2;
 
   option (chesscom.proto_options.kafka.v1alpha.kafka) = {};
 }
```

If i also remove the option it plan works.
```diff
 message Person {
   string name = 1;
-
-  option (chesscom.proto_options.kafka.v1alpha.kafka) = {};
+  string name2 = 2;
 }

```

```terraform
  ~ resource "confluent_schema" "schemas" {
        id                 = "xxxx-xxx/examples.v1alpha.person-value/latest"
      ~ schema             = <<-EOT
            syntax = "proto3";
            
            package chesscom.examples.v1alpha;
            
            import "proto_options/kafka/v1alpha/kafka_options.proto";
            
            // Some proto message.
            // v=3
            message Person {
              string name = 1;
          - 
          -   option (proto_options.kafka.v1alpha.kafka) = {};
          +   string name2 = 2;
            }
        EOT
    }
```

But when using the UI i'm able to evolve the schema when the option is present..

**Comment by linouk23** [comment]
@FabioBatSilva I can confirm we're able to reproduce the issue and identified a fix. Thanks again for reporting this issue!

**Comment by linouk23** [comment]
update: if we use `normalize=false` for your test case in [this query](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)) [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/resource_schema.go#L211) it seems to work but then it fails when shuffling attributes in a proto message (whereas the current `normalize=true` works for this scenario but fails for yours). 

At this point the only hack I might think about it is to send both requests (with normalize = false and normalize = true) and show 0 TF drift if at least one succeeded 🤔

**Comment by FabioBatSilva** [comment]
Thanks again for looking into this..

Without the `normalize=true` we go back the the behavior  on https://github.com/confluentinc/terraform-provider-confluent/issues/181 right ?

I think that is better then the current error..
But maybe something that needs to be fixed in the API then 🤔

You don't have a way to parse to proto files locally right ?
Something like:

```golang
oldFds := &descriptorpb.FileDescriptorSet{}
newFds := &descriptorpb.FileDescriptorSet{}

proto.Unmarshal(oldSchema, oldFds)
proto.Unmarshal(newSchema, newFds )
```

https://pkg.go.dev/google.golang.org/protobuf/types/descriptorpb#FileDescriptorSet.String

Then compare the parsed representation of the old and new schemas
```golang
if err := diff.SetNew(oldFds.String(), newFds.String()); err != nil {

}
```

**Comment by linouk23** [comment]
Yeah that's a great idea and I think that's something that might be implemented on a backend already.

Actually I talked to one of the teams at Confluent and they suggested to use `normalize=true` for both _register (create)_ and _lookup_ to avoid these issues so that's something I'll test soon.

**Comment by linouk23** [comment]
@FabioBatSilva could you check whether the latest version of TF Provider ([1.31.0](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1310-february-14-2023)) fixes this issue? I believe we've added a patch for this bug.

**Comment by FabioBatSilva** [comment]
@linouk23 Awesome.. 
You guys are fast.. :chart_with_upwards_trend: 

Thanks again for looking into it..

I think it fixed the update issue..
I can confirm that i'm able to update a existing record.. :+1: 

But i'm seeing a new error if I try to run a plan on new resources..
I can only run a plan after the schema for ` "proto_options/kafka/v1alpha/kafka_options.proto"` is created..

If I try to create ` "proto_options/kafka/v1alpha/kafka_options.proto"` and use that as a reference.. 
I get the same `Error: error customizing diff Schema: error looking up Schema: 422 Unprocessable Entity`

If i split this into 2 tf runs where first  `kafka_options` is created then another where i add the references it seem to work..

I think the issue happens only when kafka_options is not defined in confluent yet.
Meaning it only exists as part of the current plan and another resources depends on it..

I believe the expected plan would be something like this:
```
 # module.kafka.confluent_schema.schemas[kafka_options] will be created
  ~ resource "confluent_schema" "schema[kafka_options] " {
        name = "examples.kafka.v1alpha.kafka_options"
      ~ schema             = <<-EOT
          # ...
        EOT
    }
    
 # module.kafka.confluent_schema.schemas[other_record]  will be updated in-place
  ~ resource "confluent_schema" "schema[other_record] " {
      ~ schema             = <<-EOT
      
          + import "proto_options/kafka/v1alpha/kafka_options.proto";          
          
          # ...
        EOT
        
         + schema_reference {
          + name         = "proto_options/kafka/v1alpha/kafka_options.proto""
          + subject_name = "examples.kafka.v1alpha.kafka_options"
          + version      = (known after apply)
        }
    }
```

But I get :
```
│ Error: error customizing diff Schema: error looking up Schema: 422 Unprocessable Entity
│ 
│   with module.kafka.confluent_schema.schemas[other_record] ,
│   on ../../modules/kafka-topic/main.tf line 107, in resource "confluent_schema" "schemas[other_record]":
│  107: resource "confluent_schema" "schemas[other_record]" {
│ 
```

**Comment by linouk23** [comment]
Hmm interesting, could you share your proto definitions?

**Comment by linouk23** [comment]
cc @FabioBatSilva

**Comment by FabioBatSilva** [comment]
Sure..
Using the same as the one in the description..

I'm isolate the resources for clarity.. 
Might have copy/pasted the wrong names.. 

I'v updated the previous message to match the names i used in the description..
Let me know if it is not clear i can put together a better example

**Comment by linouk23** [comment]
@FabioBatSilva thanks for updating the messages! It'd be great if you could share the exact TF configs + proto files such that we could recreate the issue.

**Comment by FabioBatSilva** [comment]
No prob..

I think this did it ..

Before:

```terraform
resource "confluent_schema" "person" {
  #... 

  rest_endpoint      = data.confluent_schema_registry_cluster.registry.rest_endpoint
  subject_name       = "terraform.examples.v1alpha.person"
  format             = "PROTOBUF"
  recreate_on_update = false

  schema             = <<-EOT
    syntax = "proto3";

    package examples.v1alpha;

    message Person {
      string name = 1;
    }
  EOT
}

```

After:
```terraform
resource "confluent_schema" "kafka_options" {

  #... 


  subject_name       = "terraform.proto_options.kafka.v1alpha.kafka_options"
  format             = "PROTOBUF"
  recreate_on_update = false
  schema             = <<-EOT
    syntax = "proto3";

    import "google/protobuf/descriptor.proto";

    package proto_options.kafka.v1alpha;

    message KafkaOptions {
      map<string, string> config = 2;
    }

    extend google.protobuf.MessageOptions {
      repeated KafkaOptions kafka = 80000;
    }
  EOT
}

resource "confluent_schema" "person" {
  
  #... 


  subject_name       = "terraform.examples.v1alpha.person"
  format             = "PROTOBUF"
  recreate_on_update = false
  schema             = <<-EOT
    syntax = "proto3";

    package examples.v1alpha;

    import "proto_options/kafka/v1alpha/kafka_options.proto";

    message Person {
      string name = 1;

      option (proto_options.kafka.v1alpha.kafka) = {};
    }
  EOT

  schema_reference {
    name         = "proto_options/kafka/v1alpha/kafka_options.proto"
    subject_name = confluent_schema.kafka_options.subject_name
    version      = confluent_schema.kafka_options.version
  }
}
```

It seems to happens only when the state changes from the `Before` to the `After` version.

Running a fresh install on the `After` version seems to work fine..

**Comment by linouk23** [comment]
@FabioBatSilva btw I'd recommend using [Option #2](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema#option-2-manage-a-single-schema-registry-cluster-in-the-same-terraform-workspace).

**Comment by FabioBatSilva** [comment]
@linouk23 Thanks..

Will look into it :+1:
