### ISSUE TITLE
Bug: KsqlAdmin role for ksqldb doesn't work

### ISSUE THREAD

**Issue by Asvor** [confluentinc/terraform-provider-confluent#198]
### Steps to reproduce

1. Use this example for create ksql cluster - > https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/ksql-acls/main.tf
2. Connect to Ksql with "app-manager-kafka-api-key" key-secret
`$CONFLUENT_HOME/bin/ksql -u $KSQL_API_KEY -p $KSQL_API_SECRET https://pksqlc-<ID>.eu-central-1.aws.confluent.cloud:443`
4. Check streams:
 `list streams;`

### Expected result
```
ksql> list streams;

 Stream Name         | Kafka Topic                 | Key Format | Value Format | Windowed
------------------------------------------------------------------------------------------
 KSQL_PROCESSING_LOG | pksqlc-<ID>-processing-log | KAFKA      | JSON         | false
------------------------------------------------------------------------------------------
```

### Actual result

```
ksql> list streams;
You are forbidden from using this cluster.

```
If you check GUi you will see that this role map to the ksql cluster id:
![Screenshot 2023-02-10 at 10 51 13](https://user-images.githubusercontent.com/37143259/218407814-f20826d6-3020-4c66-aa97-d9fe17b92fdd.png)

In the [documentation](https://docs.confluent.io/cloud/current/ksqldb/ksqldb-ccloud-rbac.html#grant-the-ksqladmin-role-to-a-user) it connects to the cluster name.

When you add this role in GUI by hand all work.

**Comment by S1M0NM** [comment]
If I understand you correctly, it's probably because you're using the wrong API key.
The `app-manager-kafka-api-key` belongs to the `app-manager` service account.

The `KsqlAdmin` role, however, is assigned to the `app-ksql` service account, which in turn gets the `app-ksqldb-api-key` created. This key can then be used for the KSQL cluster.

**Comment by linouk23** [comment]
Thanks for creating this issue @Asvor!

Could you take a look at Simon's comment above and see whether it helps?

**Comment by S1M0NM** [comment]
I also ran the example from above once and get the same error.

The service account has been assigned the `KsqlAdmin` role, but is not allowed to perform any actions on the Ksql cluster.

```cmd
ksql> SHOW streams;
You are forbidden from using this cluster.
```
---

@linouk23 your example uses `confluent_ksql_cluster.main.id` but it seems like it has to be `confluent_ksql_cluster.main.display_name` since thats what you select when using the confluent cloud ui. After creating a KsqlAdmin role-assignment with display_name it worked :)

@Asvor could you try 

current example:
```terraform
resource "confluent_role_binding" "app-ksql-ksql-admin" {
  principal   = "User:${confluent_service_account.app-ksql.id}"
  role_name   = "KsqlAdmin"
  crn_pattern = "${confluent_kafka_cluster.standard.rbac_crn}/ksql=${confluent_ksql_cluster.main.id}"
}
```
@Asvor could you test the version below for the role-binding?
fixed:
```terraform
resource "confluent_role_binding" "app-ksql-ksql-admin" {
  principal   = "User:${confluent_service_account.app-ksql.id}"
  role_name   = "KsqlAdmin"
  crn_pattern = "${confluent_kafka_cluster.standard.rbac_crn}/ksql=${confluent_ksql_cluster.main.display_name}"
}
```

**Comment by S1M0NM** [comment]
Edit: receiving a 403 error when using resource_name 
```
confluent_role_binding.app-ksql-ksql-admin: Creating...

Error: error creating Role Binding: 403 Forbidden: Forbidden Access
```

**Comment by pgaref** [comment]
Hey @linouk23  this seems to be the typical issue of ksql_ids vs ksql_names on role-binding granting.
resource.name should be the correct value here, at least until we actually support both types on our middleware.
Thoughts?

**Comment by linouk23** [comment]
@S1M0NM that's a great catch!

Could you confirm that
```
resource "confluent_role_binding" "app-ksql-ksql-admin" {
  principal   = "User:${confluent_service_account.app-ksql.id}"
  role_name   = "KsqlAdmin"
  crn_pattern = confluent_ksql_cluster.main.resource_name
}
```
worked for you? I was a bit confused by your message later:
![image](https://user-images.githubusercontent.com/5459870/219122221-4a6d373a-6369-4103-8c26-0f2c48c52afa.png)

**Comment by pgaref** [comment]
Btw, @S1M0NM / @Asvor another way to verify this would be to list the user role-bindings after TF runs (with the old and new role-binding snippet) like `confluent iam rbac role-binding list --principal User:<user>` 

I am pretty sure the `confluent_ksql_cluster.main.id` crn would not result in new role bindings while the `resource_name` will.

**Comment by pgaref** [comment]
@S1M0NM  did you also try the full crn pattern?
`crn_pattern = "${confluent_kafka_cluster.standard.rbac_crn}/ksql=${confluent_ksql_cluster.main.resource_name}" `

**Comment by S1M0NM** [comment]
> @S1M0NM did you also try the full crn pattern? `crn_pattern = "${confluent_kafka_cluster.standard.rbac_crn}/ksql=${confluent_ksql_cluster.main.resource_name}" `

I tried it just now because i wasnt sure, and it also doesnt work:

```terraform
Terraform will perform the following actions:

  # confluent_role_binding.app-ksql-ksql-admin will be created
  + resource "confluent_role_binding" "app-ksql-ksql-admin" {
      + crn_pattern = "crn://confluent.cloud/organization=<org-id>/environment=env-<id>/cloud-cluster=lkc-<id>/ksql=crn://confluent.cloud/organization=<org-id>/environment=env-<id>/cloud-cluster=lkc-<id>/ksql=ksql_cluster_0"
      + id          = (known after apply)
      + principal   = "User:sa-<id>"
      + role_name   = "KsqlAdmin"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

The used crn pattern doesn't look right.. and also results in a failure:

```terraform
https://api.confluent.cloud/iam/v2/role-bindings giving up after 5 attempt(s)
│
│   with confluent_role_binding.app-ksql-ksql-admin,
│   on main.tf line 364, in resource "confluent_role_binding" "app-ksql-ksql-admin":
│  364: resource "confluent_role_binding" "app-ksql-ksql-admin" {
│
```

**Comment by linouk23** [comment]
Same for me:
after
![image](https://user-images.githubusercontent.com/5459870/219146276-dd3950b2-de33-4135-93f9-1f06f615c8bc.png)
I can see
```
confluent_api_key.app-ksqldb-api-key: Still creating... [5m0s elapsed]
confluent_api_key.app-ksqldb-api-key: Creation complete after 5m1s [id=B7LOOR2E4JDSL3XR]
╷
│ Error: error creating Role Binding: 403 Forbidden: Forbidden Access
│ 
│   with confluent_role_binding.app-ksql-ksql-admin,
│   on main.tf line 359, in resource "confluent_role_binding" "app-ksql-ksql-admin":
│  359: resource "confluent_role_binding" "app-ksql-ksql-admin" {

@pgaref @luca-filipponi @tolgadur wdyt?
```

**Comment by linouk23** [comment]
@pgaref @luca-filipponi @tolgadur wdyt?

**Comment by linouk23** [comment]
update: @Asvor @S1M0NM we're working on a fix.

**Comment by linouk23** [comment]
@Asvor @S1M0NM could you try again with
![image](https://user-images.githubusercontent.com/5459870/219513309-07a66a0d-09e0-4fca-821f-5c04e266c067.png)

It seems to work now (after we released a backend fix).

**Comment by JeffSBailey** [comment]
@linouk23  Does this backend fix apply just to ksql-rbac?  I experience the same behavior trying to set a confluent_role_binding to a service account which has the organizationadmin role.  Trying to assign EnvironmentAdmin to an environment crn_pattern using resource_name.  I am using version 1.65.0.  Happy to open a separate issue if needed.  

```
resource "confluent_role_binding" "admin_users" {
  for_each    = toset(var.environment_admin_users)
  role_name   = "EnvironmentAdmin"
  crn_pattern = data.confluent_environment.env.resource_name
  principal   = "User:${confluent_invitation.admin_users[each.value].id}"
}
```
Error: error creating Role Binding: 403 Forbidden: Forbidden Access

**Comment by linouk23** [comment]
> Happy to open a separate issue if needed.

@JeffSBailey it would be great, thanks!
