### ISSUE TITLE
Postgres CDC Source Connector never finishes provisioning

### ISSUE THREAD

**Issue by burkematthew** [confluentinc/terraform-provider-confluent#199]
## Description

I am attempting to provision a new Postgres CDC Source Connector in Confluent Cloud.  However, when applying the plan that implements the new connector resource, the Connector stays in the provisioning state and never errors out or completes.  I tried to apply it earlier this morning and let it run for 2 hours with no error or completion.  Terraform then timed out and cancelled the run.  I deleted the Connector that was in the provisioning state in Confluent cloud.  I then kicked off another plan apply and it still stays in this "provisioning" state longer than I'd anticipate.  Lastly, we've checked our database logs and find no evidence of the Connector connecting to our database or trying to do anything within the database (i.e. no new publication, nothing in the replication slot, etc.).

## Details

* Confluent Provider Version: 1.28.0
* Connection Type: We are using an AWS Peering Connection for our database that lives in AWS.  We verified that the VPCs can connect to each other.
* Resource Type: `confluent_connector`
* Connector Class: `PostgresCdcSource`
* Example used as reference: https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/connectors/postgre-sql-cdc-debezium-source-connector
* Since we are still working on our staging environment, all of our resources have lifecycle `prevent_destroy` explicitly set to false.

If there are any other details that I can provide to help troubleshoot, please let me know.  Thanks in advance!

**Comment by linouk23** [comment]
@burkematthew thanks for creating the issue! Could you share your TF config (without sensitive variables) here or send it to `cflt-tf-access@confluent.io` so our team could try to reproduce the issue? Thanks!

**Comment by burkematthew** [comment]
Hi @linouk23 , thanks for the prompt reply!  I'll go ahead and send the config over to the email provided.  I'll do that momentarily and will confirm when the email is sent.  Thanks again!

**Comment by burkematthew** [comment]
@linouk23 I just sent the email with the requested configs.  Please let me know if you need anything else from me!

**Comment by linouk23** [comment]
I've got one more quick question @burkematthew: can you reproduce the same issue when using UI instead of TF?

**Comment by burkematthew** [comment]
@linouk23 I haven't let the attempt in the UI run quite as long as I did in TF, but it does appear so.

**Comment by linouk23** [comment]
@burkematthew could you verify you can see the same in the UI? This way we'd be able to tag backend team to investigate.

**Comment by burkematthew** [comment]
@linouk23 I have a UI-initiated connector still provisioning at the moment.  I'll let it continue to provision for a bit and see if anything further happens.  After an hour or two, I'll provide an update on whether we were successful or not.

I'll also email the connector and env IDs.  Thanks!

**Comment by burkematthew** [comment]
@linouk23 that information has been emailed now.  I'll post an update here in an hour or two.

**Comment by burkematthew** [comment]
Hi @linouk23 , just following up here, confirming that the connector is in fact still provisioning.  I assume that it'd be best to leave the connector alone until we isolate the issue?

**Comment by burkematthew** [comment]
Okay, the connector failed timed out\failed with the following result:

```
Unable to validate configuration. If an update was made to the configuration, this means that the configuration was invalid, and the connector continues to operate on a previous configuration that passed validation. Errors:
database.hostname: Error while validating connector config: The connection attempt failed.
database.port: Error while validating connector config: The connection attempt failed.
database.user: Error while validating connector config: The connection attempt failed.
database.password: Error while validating connector config: The connection attempt failed.
database.dbname: Error while validating connector config: The connection attempt failed.
database.server.name: Error while validating connector config: The connection attempt failed.
```

This typically doesn't take multiple hours to fail while attempting.  In my experience, these database failures will pop up pretty quickly if there's a database configuration issue.

**Comment by linouk23** [comment]
Nice! Do you want to fix "The connection attempt failed." and then try again?

**Comment by linouk23** [comment]
cc @burkematthew

**Comment by burkematthew** [comment]
@linouk23 is there any other information accessible as to why this connection failed? Are there more robust logging mechanisms I can leverage?

**Comment by linouk23** [comment]
I'm not a connector expert unfortunately, I'd recommend reaching out to our [support team](https://www.confluent.io/confluent-cloud/support/).

**Comment by burkematthew** [comment]
@linouk23 yup, understood. Makes sense to switch over to that route at this point. I really appreciate all your guidance here.

**Comment by zhenli00** [comment]
Looks like there's an incident today that "All Connector provisioning/deprovisioning has been delayed.". Can you please try again? https://status.confluent.cloud/incidents/y72ql4p0db3q

**Comment by burkematthew** [comment]
@zhenli00 thanks for that info!  We're retrying our provisioning this morning and trying to troubleshoot again.  If we still have no luck, I'll reach out to the Support team to get some assistance.

**Comment by mengtong-personal** [comment]
Hi @burkematthew would you mind sharing how did you / confluent team eventually resolve the issue? I'm hitting the same issue (Postgres CDC source connector stuck provisioning) and there is little debugging information. Thanks!

**Comment by burkematthew** [comment]
@mengtong-personal it turns out that we were trying to provision our connector in a basic cluster with network peering connections, which are only available in dedicated clusters.  At the time, that fact was unbeknownst to me.  We've been working towards implementing dedicated clusters so that this isn't an issue anymore.  To be honest, though, I haven't actually revisited the Terraform implementation yet as we're still working on moving forward with our relevant project.

**Comment by mengtong-personal** [comment]
> @mengtong-personal it turns out that we were trying to provision our connector in a basic cluster with network peering connections, which are only available in dedicated clusters. At the time, that fact was unbeknownst to me. We've been working towards implementing dedicated clusters so that this isn't an issue anymore. To be honest, though, I haven't actually revisited the Terraform implementation yet as we're still working on moving forward with our relevant project.

Hi @burkematthew Thank you for your quick reply! I'm actually hitting this issue with an dedicated cluster. I saw you mentioned above that "We verified that the VPCs can connect to each other.", may I know how did you verify that? I thought one of the VPC belongs to confluent and I don't have access, not sure how to test the connection other than verifying the state from my AWS console is active for the peering connection.
