### ISSUE TITLE
Retrieve resource_name for an org

### ISSUE THREAD

**Issue by vweckerle** [confluentinc/terraform-provider-confluent#20]
Hi guys,

from the current documentation of the confluent_role_binding resource it is not clear how a role binding of a role on organization level can be done.

I was expecting something like this:
```
resource "confluent_role_binding" "some-role-binding" {
  principal   = "User:${confluent_service_account.some-service-account.id}"
  role_name   = "MetricsViewer"
}
```

But crn_pattern is a required attribute.

It would be great if you could add an example to the documentation which shows how to use the confluent_role_binding for such a scenario.

Btw. as a mitigation I tried to bind the role on environment level instead, but this is giving me an `Error: error creating Role Binding: 400 Bad Request` error:
```
resource "confluent_role_binding" "some-role-binding" {
  principal   = "User:${confluent_service_account.some-service-account.id}"
  role_name   = "MetricsViewer"
  crn_pattern = confluent_environment.some-env.resource_name
}
```
Is this supposed to work?

Greetings
Valentin

**Comment by linouk23** [comment]
Thanks for reporting the issue @vweckerle! 

Just opened https://github.com/confluentinc/terraform-provider-confluent/issues/21 to address your second concern and TLDR the error is:
```
{"error_code":40002,"message":"Role MetricsViewer must be bound at scope organization, but was bound at environment"}
```

For a quick and hacky workaround we'd suggest something like:
```
resource "confluent_role_binding" "environment-example-rb" {
  principal   = "User:${confluent_service_account.app-manager.id}"
  role_name   = "MetricsViewer"
  crn_pattern = substr(confluent_environment.staging.resource_name, 0, local.org_name_length)
}

locals {
   org_name_length = 71
}
```

But I'll keep this issue open to address it in a non-hacky way 👌

**Comment by vweckerle** [comment]
Hi @linouk23, thanks for the quick reply. It is interesting to see that the API and the confluent CLI seem to behave differently in this case. Via confluent CLI it is possible to assign the MetricsViewer role for an environment:
```
$ confluent iam rbac role-binding create --role MetricsViewer --principal User:sa-xxx --environment env-aaa
+-----------+----------------+
| Principal | User:sa-xxx |
| Role      | MetricsViewer  |
+-----------+----------------+
$ confluent iam rbac role-binding list --principal User:sa-xxx
    Principal    | Email |     Role      | Environment | Cloud Cluster | Cluster Type | Logical Cluster | Resource Type | Name | Pattern Type
-----------------+-------+---------------+-------------+---------------+--------------+-----------------+---------------+------+---------------
  User:sa-xxx |       | MetricsViewer | env-aaa   |               |              |                 |               |      |
```
So I was assuming this is a valid use case (but in our scenario, we want to set it globally anyway so it is not critical for us).

Greetings
Valentin

**Comment by linouk23** [comment]
@vweckerle thanks for asking! It does look a bit suspicious so I pinged our CLI team and they'll investigate it.

**Comment by MuweiHe** [comment]
From the admin dashboard, `MetricsViewer` created with an env specified will be created as a `EnvironmentMetricsViewer`, but when calling `list` api it returns as just `MetricsViewer` so that's the confusion. If we only want to support org level metrics viewers, we might need to change the api, but cli can do a temp fix to disallow creating with env.

**Comment by linouk23** [comment]
@vweckerle there's an update regarding

> It does look a bit suspicious so I pinged our CLI team and they'll investigate it.

The role is being displayed as `MetricsViewer` and not `EnvironmentMetricsViewer` because CLI isn't using the latest version of our internal APIs (once CLI starts using the latest version, the role will be displayed as `EnvironmentMetricsViewer`).

**Comment by linouk23** [comment]
@vweckerle we're happy to let you know that we shipped `confluent_organization` [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_organization) in our latest `0.8.0` [release](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#080-may-12-2022) so now you can do:
```
resource "confluent_role_binding" "org-example-rb" {
  principal   = "User:${confluent_service_account.test.id}"
  role_name   = "MetricsViewer"
  crn_pattern = data.confluent_organization.demo.resource_name
}
```
