### ISSUE TITLE
follow semantic versioning

### ISSUE THREAD

**Issue by justrp** [confluentinc/terraform-provider-confluent#204]
Please follow [semantic versioning](https://semver.org/)

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY also include minor and patch level changes. Patch and minor versions MUST be reset to 0 when major version is incremented.

It means that once you do breaking changes, you increment *major* version, not the *minor* one

[1.32.0](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.32.0) includes breaking changes that could lead to necessity to re-import schemas

Usually people specify major version (e.g. `version = "~> 1.23"`) in terraform code. It's safe enough to expect new features coming there as well as bugfixes, but a breaking change will bump the major version (`2.0.0` in this example), so it won't affect already working code.

**Comment by linouk23** [comment]
@justrp thanks for creating an issue!

Your comment definitely makes sense and it applies for all resources that are in [Generally Available lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy) however it's acceptable to make breaking changes for resources in [Early Access / Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy) which we try to call out in our docs:

![image](https://user-images.githubusercontent.com/5459870/219508995-e5565caa-be52-498b-9867-130baa406bec.png)

![image](https://user-images.githubusercontent.com/5459870/219509060-f58936ca-403a-4ac4-9785-b716b2d4c649.png)


All that said, we do try to avoid breaking changes even for resources in [Early Access / Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy).

Thanks for using our TF Provider!

**Comment by justrp** [comment]
@linouk23 , got it, thanks. Got wrong impression looking at `1` as major version.
