### ISSUE TITLE
Display detailed error when getting 400 for confluent_role_binding

### ISSUE THREAD

**Issue by linouk23** [confluentinc/terraform-provider-confluent#21]
### What
Sample configuration
```
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "0.7.0"
    }
  }
}

provider "confluent" {
  api_key    = var.confluent_cloud_api_key
  api_secret = var.confluent_cloud_api_secret
}

resource "confluent_environment" "staging" {
  display_name = "Staging"
}

resource "confluent_service_account" "app-manager" {
  display_name = "app-manager"
  description  = "Service account to manage 'inventory' Kafka cluster"
}

resource "confluent_role_binding" "environment-example-rb" {
  principal   = "User:${confluent_service_account.app-manager.id}"
  role_name   = "MetricsViewer"
  crn_pattern = confluent_environment.staging.resource_name
}
```

During `apply` one can see:
```
Error: error creating Role Binding: 400 Bad Request

  on main.tf line 24, in resource "confluent_role_binding" "environment-example-rb":
  24: resource "confluent_role_binding" "environment-example-rb" {
```
which is not very descriptive.

When doing the same request via the API we can see a more descriptive error though
```
{"error_code":40002,"message":"Role MetricsViewer must be bound at scope organization, but was bound at environment"
```

**Comment by m-kruth** [comment]
I've also experienced this when attempting to create role-bindings for topics that are longer than 79 characters long. The Terraform Provider returns an `Error: 400 Bad Request` message and references the relevant role-binding block but provides no further detail on what the error is. The Confluent CLI returns a full error message detailing the exact problem (`Error: metadata service backend error: Invalid resource pattern: resource name should not be longer than 249 bytes`).

**Comment by vweckerle** [comment]
+1
This would be very helpful indeed! Currently, whenever there I get such a 400 error, I always need to rebuild the same request via confluent CLI first to then get a useful error message to then fix the issue in my TF code. It would save a lot of time, if TF would already return a useful error message.

**Comment by linouk23** [comment]
Update: I can confirm that I still can see this issue.

The corresponding backend team has this ticket in their backlog but it hasn't been fixed yet.

**Comment by linouk23** [comment]
Update: our backend team has identified and resolved this issue. 


*Before*:
```
confluent_role_binding.subject-with-prefix: Creating...
╷
│ Error: error creating Role Binding: 400 Bad Request
│ 
│   with confluent_role_binding.subject-with-prefix,
│   on main.tf line 19, in resource "confluent_role_binding" "subject-with-prefix":
│   19: resource "confluent_role_binding" "subject-with-prefix" {
```

*After*:
```
confluent_role_binding.subject-with-prefix: Creating...
╷
│ Error: error creating Role Binding: 400 Bad Request: Invalid role name : EnvironmentAdmin2
│ 
│   with confluent_role_binding.subject-with-prefix,
│   on main.tf line 19, in resource "confluent_role_binding" "subject-with-prefix":
│   19: resource "confluent_role_binding" "subject-with-prefix" {
```
