### ISSUE TITLE
cleanup.policy change should show as destroy/add in confluent_kafka_topic resource

### ISSUE THREAD

**Issue by laurence-hubbard** [confluentinc/terraform-provider-confluent#216]
I've changed the value of `cleanup.policy` which shows up as a change in the plan but fails in the apply.

Since this is a destructive change if actually implemented it should be prevented and this prevention should be made clear in the plan.

This is obviously an edge case, but thought worth raising anyway. I can see in the source code that the config is `schema.TypeMap` and you can't set `ForceNew: true` for an element within a map ([ref](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-types#aggregate-types)) so it would need to be pulled out of the map and made an optional top level parameter similar to `paramPartitionsCount`.
 
 Current behvaiour:
```terraform
  # module.testing.confluent_kafka_topic.topic will be updated in-place
  ~ resource "confluent_kafka_topic" "topic" {
      ~ config           = {
          ~ "cleanup.policy"                      = "delete" -> "compact"
            # (11 unchanged elements hidden)
        }
        id               = "lkc-12xnr6/testing.testing.123"
        # (3 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

Expected behaviour:
```terraform
Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by linouk23** [comment]
👋 @laurence-hubbard thanks for creating this issue!

I think the way TF Provider works in this specific scenario is it'll display a runtime error that will say that 
```
"cleanup.policy" can't be updated from "delete" to "compact"
```

See [this code pointer](https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/resource_kafka_topic.go#L565).

Let me know if that helps.

**Comment by laurence-hubbard** [comment]
@linouk23 it's a shame that this can't be seen when running `terraform plan` - I have a similar issue now with schemas which fail compatibility checks. Would prefer to be able to run `terraform plan` when a PR is raised against a project and be able to approve/reject the PR based on the output of the plan to prevent failing code from being merged / applied.

Currently adding custom lifecycle preconditions and hitting the Confluent REST API using terraform http data objects.
