### ISSUE TITLE
Can we use TopicRecordNameStrategy in terraform

### ISSUE THREAD

**Issue by Davinder2609** [confluentinc/terraform-provider-confluent#220]

**Comment by linouk23** [comment]
Thanks for creating the issue @Davinder2609! Do you want to add more details to your request?

**Comment by Davinder2609** [comment]
@linouk23  Like we have multiple schemas for one topic

**Comment by linouk23** [comment]
@Davinder2609 did you look at

* [multiple-event-types-avro-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-avro-schema)
* [multiple-event-types-proto-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-proto-schema)

already?
