### ISSUE TITLE
confluent_private_link_access Resource to support tags? 

### ISSUE THREAD

**Issue by brant4test** [confluentinc/terraform-provider-confluent#222]
Quick check, confluent_private_link_access Resource to support tags? Thanks!
https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_private_link_access

**Comment by linouk23** [comment]
@brant4test thanks for creating the issue!

Our backend APIs don't support tagging yet and it might not be on the roadmap so I'm closing this issue for now.
