### ISSUE TITLE
Terraform Apply failes when trying to update confluent_schema but State File gets updated

### ISSUE THREAD

**Issue by S1M0NM** [confluentinc/terraform-provider-confluent#226]
Hi, we stumbled across an interesting bug today.

We wanted to update one of our schemas, but the Terraform Run failed in the Apply step because the schemas were not compatible.
Interestingly, in the next plan step, this schema no longer showed up as a resource to update.
When looking at the Terraform State, it was noticed that the new, incompatible scheme is already stored there for the resource.

Here we would expect that the old schema would remain in the state file and that the resource would reappear as a resource to be updated in the next Terraform plan. Especially since this was not updated in the registry at all.

First run:

`Plan: 0 to add, 1 to change, 0 to destroy.`

```
╷
│ Error: error creating Schema: error validating a schema: Compatibility check on the schema has failed against one or more versions in the subject, depending on how the compatibility is set.
│ See https://docs.confluent.io/platform/current/schema-registry/avro.html#sr-compatibility-types for details.
│ For example, if compatibility on the subject is set to BACKWARD, FORWARD, or FULL, the compatibility check is against the latest version.
│ If compatibility is set to one of the TRANSITIVE types, the check is against all previous versions.
│ 
│   with module.<module_name>.confluent_schema.schema["<subject>"],
│   on .terraform/modules/<module_name>/schema.tf line 1, in resource "confluent_schema" "schema":
│    1: resource "confluent_schema" "schema" {
│ 
╵
```

Second run:

`Plan: 0 to add, 0 to change, 0 to destroy.`

**Comment by linouk23** [comment]
@S1M0NM we've just released a new version of TF Provider for Confluent ([1.43.0](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.43.0)) that includes a fix for this issue.

Let us know if you're able to reproduce it when using [the latest version](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.43.0) of TF Provider!
