### ISSUE TITLE
Question: Schema registry resource

### ISSUE THREAD

**Issue by VipulZopSmart** [confluentinc/terraform-provider-confluent#227]
Team,
As of now, we use CLI to register, update, and evolve the schemas, but we want to migrate to the terraform resource for doing that not manually. I was going through the documentation and got to know there we would need to pass schema registry cluster id:
```

provider "confluent" {
  cloud_api_key    = var.confluent_cloud_api_key    # optionally use CONFLUENT_CLOUD_API_KEY env var
  cloud_api_secret = var.confluent_cloud_api_secret # optionally use CONFLUENT_CLOUD_API_SECRET env var
}

resource "confluent_schema" "avro-purchase" {
  schema_registry_cluster {
    id = confluent_schema_registry_cluster.essentials.id
  }
  rest_endpoint = confluent_schema_registry_cluster.essentials.rest_endpoint
  subject_name = "avro-purchase-value"
  format = "AVRO"
  schema = file("./schemas/avro/purchase.avsc")
  credentials {
    key    = "<Schema Registry API Key for confluent_schema_registry_cluster.essentials>"
    secret = "<Schema Registry API Secret for confluent_schema_registry_cluster.essentials>"
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

In Confluent UI, I don't see any schema registry Id - I do have schema registry API keys and secrets. 
Question 1: Where will I get this schema registry id?
Question 2: Will I able to link the existing schema by using the above confluent resource?
Question 3: We use a number of union schemas, how we can do that by using the terraform resource(please help us with some good examples).

Thanks in Advance

**Comment by linouk23** [comment]
Thanks for creating the issue @VipulZopSmart!

1. That's right that UI doesn't expose SR Cluster ID at the moment. You might have to use CLI / Developer Tools Tab to find SR Cluster ID.

2. That's exactly right, you can [import](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema#import) schemas.

3. It is supported, see
* [multiple-event-types-avro-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-avro-schema)
* [multiple-event-types-proto-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-proto-schema)

**Comment by VipulZopSmart** [comment]
`You might have to use CLI / Developer Tools Tab to find SR Cluster ID.`
@linouk23 Please help me with the command.

**Comment by linouk23** [comment]
@VipulZopSmart 

```
confluent schema-registry cluster describe --environment env-o11111
+-------------------------+--------------------------------------------------+
| Name                    | Stream Governance Package                        |
| Cluster ID              | lsrc-abc123                                      |
```
