### ISSUE TITLE
Add display_name as an attribute to confluent_service_account

### ISSUE THREAD

**Issue by afireinside09** [confluentinc/terraform-provider-confluent#228]
We have a need to retrieve the actual `display_name` from the `confluent_service_account` resource in order to map service account principal ids to our respective application.

As of now, the `display_name` is created as part of a loop over a list that can't easily be extracted. We would prefer to have the actual `display_name` be an attribute to the resource so that we're not trying to map 2 unrelated resources together.

This is our `confluent_service_account` resource block:
```
resource "confluent_service_account" "team_application" {
  for_each = { for project in var.project_list : project.name => project.topic_list }

  # We have same application/service name used by different teams, to overcome this and to make the Service Account
  # unique, we need to add team_name to Confluent Service Account display name.
  # Max char allowed for Service Account display name is 64 characters, so we need to trim the generated name to
  # 64 characters. Need to also make sure that the name doesn't endwith `-` after truncation
  display_name = trimsuffix(substr("${var.cell_name}-${each.key}-${var.team_name}", 0, 63), "-")
  description  = "Service account for the ${var.cell_name},${var.team_name}-${each.key} application"
}
```

**Comment by linouk23** [comment]
👋 @afireinside09,

Could you share an example where your `display_name` is different from `display_name` attribute?
![image](https://user-images.githubusercontent.com/5459870/228005239-e4ecfee9-456d-4598-826f-6cfdcb8df91d.png)

Alternatively, you could use its `id` attribute (e.g., `sa-123abc`) which is unique across the organization.

**Comment by afireinside09** [comment]
Hey @linouk23 , I was mostly looking at the attributes reference and didn't see `display_name` listed. I'm guessing it is available? 
![Screenshot 2023-03-27 at 9 33 42 AM](https://user-images.githubusercontent.com/4553203/228006141-672cdd4c-5767-409f-a7d4-394ce18639c2.png)

**Comment by linouk23** [comment]
Oh I see, yeah basically you should be looking at a union of these 2 sections instead:

![image](https://user-images.githubusercontent.com/5459870/228006620-7d670a4f-7ce4-4040-87dc-bfc85c756083.png)

> I'm guessing it is available?

That's exactly right!

**Comment by afireinside09** [comment]
ACK - thank you!
