### ISSUE TITLE
Allow for SUFFIXED in confluent_kafka_acl

### ISSUE THREAD

**Issue by afireinside09** [confluentinc/terraform-provider-confluent#229]
We have a need to support wildcarding and suffixes when creating `confluent_kafka_acl`s.
We've tested using `*_some_suffix` using the `PREFIXED` pattern type but that doesn't work.

We have about 21 topics that already have a suffix that we'd like to key off of, changing them to using PREFIX doesn't seem prudent if there's support for SUFFIX.

**Comment by esquare666** [comment]
Not sure whether the acl can given based on regular expression?

**Comment by linouk23** [comment]
👋 it seems like the question more about Kafka REST API and not about TF Provider for Confluent.

That said, based on

* https://stackoverflow.com/questions/54864129/kafka-acl-wildcard-suffixed-topic-name-support
* https://kafka.apache.org/21/javadoc/org/apache/kafka/common/resource/PatternType.html

It looks like the answer is `SUFFIXED`  / using a similar wildcard `abc_*` this is not supported - `MATCH` is only for listing ACLs and the only modes available for creating them are "LITERAL" and "PREFIXED":

![image](https://user-images.githubusercontent.com/5459870/230891429-1f595945-cebc-4f51-8b9a-6f2f11e3b4a6.png)
