### ISSUE TITLE
Ksqldb integration

### ISSUE THREAD

**Issue by OldWarrior3000** [confluentinc/terraform-provider-confluent#23]
Hi all,

is it planned to incorperate the provisioning of Ksqldb in the near future?

Thanks

Kind regards

**Comment by linouk23** [comment]
👋 @OldWarrior3000,

We are aware of the this ask (see #3) and it is on our roadmap but I can't give a timeline for when it will be delivered.

**Comment by OldWarrior3000** [comment]
Great, thanks @linouk23 . I will close the issue
