### ISSUE TITLE
Error: Failed to install provider

### ISSUE THREAD

**Issue by selgit** [confluentinc/terraform-provider-confluent#230]
Error while installing hashicorp/confluentcloud: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/confluentcloud.

# provider.tf

### Configure AWS provider
provider "aws" {
    region  = var.region
    profile = var.profile
 }

### Configure the Confluent Provider
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.38.0"
    }
  }
}

provider "confluent" {
  cloud_api_key         = local.ccloud_credentials.cloud_apikey
  cloud_api_secret      = local.ccloud_credentials.cloud_apikey_secret
  kafka_id              = var.cc_kafka_cluster_id
  kafka_rest_endpoint   = var.confluent_kafka_cluster_rest_endpoint
  kafka_api_key         = local.cluster_credentials.cluster_apikey
  kafka_api_secret      = local.cluster_credentials.cluster_apisecret
}

# Output with error

$ terraform init

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/aws v4.61.0
- Finding confluentinc/confluent versions matching "1.38.0"...
- Finding latest version of hashicorp/confluentcloud...
- Installing confluentinc/confluent v1.38.0...
- Installed confluentinc/confluent v1.38.0 (signed by a HashiCorp partner, key ID D4A2B1EDB0EC0C8E)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to install provider

Error while installing hashicorp/confluentcloud: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/confluentcloud

**Comment by linouk23** [comment]
Thanks for creating the issue @selgit!

Do you want to double check that you're using `source = "confluentinc/confluent"` and not `source = "confluentinc/confluentcloud" which your error message implies?

> Error while installing hashicorp/confluentcloud: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/confluentcloud.


For the context, https://registry.terraform.io/providers/confluentinc/confluentcloud/latest was deprecated in favor of https://registry.terraform.io/providers/confluentinc/confluent/latest more than a year ago.

**Comment by selgit** [comment]
@linouk23 
Following the doc - https://registry.terraform.io/providers/confluentinc/confluent/1.38.0/docs#example-usage.

**Comment by linouk23** [comment]
I see, could you double check your *.tf files and `.terraform.lock.hcl` not to include `confluentcloud` substring?

Alternatively you might want to run `grep -r "confluentcloud"` or something

**Comment by linouk23** [comment]
cc @selgit

**Comment by linouk23** [comment]
Feel free to reopen this issue of my previous piece of advice doesn't help.
