### ISSUE TITLE
Unable register subject with name containing slashes

### ISSUE THREAD

**Issue by FabioBatSilva** [confluentinc/terraform-provider-confluent#236]
The provider currently fails to [extract the schema identifier](https://github.com/confluentinc/terraform-provider-confluent/blob/546060af2b695ae67602b767f1217c94e0369b57/internal/provider/resource_schema.go#L452-L470) if the subject name contains a `/`

For instance the subject name `topic_message/v1alpha/platform_user.proto`
causes :
```
│ Error: error reading Schema "xx-xxxx/topic_message/v1alpha/platform_user.proto/latest": error extracting Schema Identifier from Resource ID: invalid format: expected '<Schema Registry cluster ID>/<subject name>/<schema identifier>'
```

Using the import/path as the subject name is supported in the UI and the default behaviour for serializers such as :

https://github.com/confluentinc/schema-registry/blob/master/schema-serializer/src/main/java/io/confluent/kafka/serializers/subject/DefaultReferenceSubjectNameStrategy.java#L36

**Comment by linouk23** [comment]
@FabioBatSilva we resolved this issue in the latest [release](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1420-may-9-2023) (1.42.0) of TF Provider for Confluent.
