### ISSUE TITLE
Fix a minor error in the example to create a confluent_ksql_cluster resource 

### ISSUE THREAD

**Issue by kasher-confluent** [confluentinc/terraform-provider-confluent#239]
This is from the [documentation to create a confluent_ksql_cluster resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_ksql_cluster#example-usage).

<img width="528" alt="Screenshot 2023-04-20 at 11 22 56 AM" src="https://user-images.githubusercontent.com/126028752/233454384-6516e1fe-26e9-4399-ab4c-b46f05117013.png">

- The confluent_role_binding created for the CloudClusterAdmin is named as 'app-ksql-kafka-cluster-admin'
- However, it is referenced as 'app-manager-kafka-cluster-admin' in the depends_on section while creating the confluent_ksql_cluster resource

Running the above file returns the following error.

<img width="1229" alt="Screenshot 2023-04-20 at 11 20 20 AM" src="https://user-images.githubusercontent.com/126028752/233453802-a4738bef-da6f-415f-9ba4-7bbee8b3a8a3.png">

Should 'app-manager-kafka-cluster-admin' be changed to 'app-ksql-kafka-cluster-admin' in the depends_on section while creating the confluent_ksql_cluster resource? I tried making the change and it worked after that.

**Comment by linouk23** [comment]
Thanks for reporting a bug @kasher-confluent!

We'll fix it in our next release of TF Provider!

By the way, even though our docs are usually accurate we'd recommend using our e2e [examples](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_ksql_cluster#getting-started) instead:

* [ksql-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/ksql-acls)
* [ksql-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/ksql-rbac)

**Comment by linouk23** [comment]
@kasher-confluent this issue was [resolved](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1400-april-26-2023) in our latest 1.40.0 release, thanks!
