### ISSUE TITLE
Attach RBAC and ACLs to the identity pool with TF

### ISSUE THREAD

**Issue by ajfc84** [confluentinc/terraform-provider-confluent#241]
On the Confluent Console is very easy to attach RBAC and ACLs but it is not so clear on the Terraform provider about
how this is achieved.
On GCP for example they attach to the identity pool a Service Account that can in turn be attached with the permissions.
On Confluent do I use the pool-xxxx id on the principal field of the RBAC or ACL or is there also a missing feature here?

**Comment by linouk23** [comment]
Thanks for asking @ajfc84!

> On Confluent do I use the pool-xxxx id on the principal field

That's exactly right! For example,
```
resource "confluent_kafka_acl" "app-producer-write-on-topic" {
  provider = confluent.kafka

  resource_type = "TOPIC"
  resource_name = confluent_kafka_topic.orders.topic_name
  pattern_type  = "LITERAL"
  principal     = "User:${confluent_identity_pool.this.id}"
  host          = "*"
  operation     = "WRITE"
  permission    = "ALLOW"
}
```
and
```
resource "confluent_role_binding" "environment-example-rb" {
  principal   = "User:${confluent_identity_pool.this.id}"
  role_name   = "EnvironmentAdmin"
  crn_pattern = confluent_environment.stag.resource_name
}
```

Let me know whether it helps!

**Comment by ajfc84** [comment]
Awesome, thanks a lot!
