### ISSUE TITLE
The configuration for provider["registry.terraform.io/confluentinc/confluent"] depends on values that cannot be determined until apply.

### ISSUE THREAD

**Issue by selgit** [confluentinc/terraform-provider-confluent#244]
My provider.tf

```
# Configure AWS provider
provider "aws" {
    region  = var.region
    profile = var.profile
 }

# Configure the Confluent Provider
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.38.0"
    }
  }
}

provider "confluent" {
  cloud_api_key            = jsondecode(data.aws_secretsmanager_secret_version.ccloud_credentials.secret_string)["cloud_apikey"]
  cloud_api_secret        = jsondecode(data.aws_secretsmanager_secret_version.ccloud_credentials.secret_string)["cloud_apikey_secret"]
  kafka_id                     = var.cc_kafka_cluster_id
  kafka_rest_endpoint  = var.confluent_kafka_cluster_rest_endpoint
  kafka_api_key           = jsondecode(data.aws_secretsmanager_secret_version.cluster_credentials.secret_string)["cluster_apikey"]
  kafka_api_secret      = jsondecode(data.aws_secretsmanager_secret_version.cluster_credentials.secret_string)["cluster_apisecret"]
}
```
Trying to import existing service account to module

`$ terraform import module.service_account.confluent_service_account.sa sa-1234` shows below error.

```
Error: Invalid provider configuration

  on /home/user/github/inf-ter-confluent-cloud/environments/test/service-accounts/service-account-1/provider.tf line 17:
  17: provider "confluent" {

The configuration for provider["registry.terraform.io/confluentinc/confluent"]
depends on values that cannot be determined until apply.
```
I know about export credentials variables.

Am I missing some options?

**Comment by linouk23** [comment]
@selgit thanks for the question!

I'm not sure whether it's possible to reference unresolved values like `jsondecode(data.aws_secretsmanager_secret_version.ccloud_credentials.secret_string)["cloud_apikey"]` during `terraform import`. Could you try to export them as env vars instead as described [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs)?

**Comment by linouk23** [comment]
> But it would be a good feature if the credentials can be read from data sources.

Thanks @selgit, I might need to experiment with it a little bit, it might be the case that it's a more broadTF limitation because of the difference between `terraform plan` and `terraform import` and not a limitation of this TF Provider.

**Comment by selgit** [comment]
@linouk23 

The issue was with one of the depends_on resources in my tf code. When I changed that, now I can run `terraform apply` with the above provider config, https://github.com/confluentinc/terraform-provider-confluent/issues/244#issue-1688373430, for new resource creation. Currently, the error occurs while importing existing resources to terraform module and I have a workaround for the same.

Thank you for your time.
