### ISSUE TITLE
I want to import rolebindings from Confluent Cloud. Where do I find the rolebindings id?

### ISSUE THREAD

**Issue by diedeck** [confluentinc/terraform-provider-confluent#245]
We created service accounts and corresponding rolebindings by Confluent CLI and are now switching over to terraform. We could import service accounts and see there is also an import for rolebindings. Documentations says:

$ export CONFLUENT_CLOUD_API_KEY="<cloud_api_key>"
$ export CONFLUENT_CLOUD_API_SECRET="<cloud_api_secret>"
$ terraform import confluent_role_binding.my_rb rb-f3a90de

Where do I find that rolebinding id? Here: rb-f3a90de
Can I list in in Confluent CLI or somewhere in The Confluent Control Center UI?

Regards 
Dietmar

**Comment by linouk23** [comment]
@diedeck thanks for asking!

That's a great question! I think for now you might have to use RBAC API's [List Role Bindings request](https://docs.confluent.io/cloud/current/api.html#tag/Role-Bindings-(iamv2)/operation/listIamV2RoleBindings).
