### ISSUE TITLE
confluent terraform importer

### ISSUE THREAD

**Issue by YaseenHassanLiberty** [confluentinc/terraform-provider-confluent#246]
Hi,

Just tried to make use of the importer functionality, upon adding resources:
resources = ["confluent_service_account", "confluent_environment", "confluent_kafka_cluster", "confluent_kafka_acl", "confluent_kafka_topic"]

I get the message:
Error: cloud and kafka resources can't be imported simultaneously. Remove "resources" attribute from 'confluent_tf_importer' resource in your Terraform configuration to use the default set of resources for a given importer mode or specify just Cloud or just Kafka resources for "resources"

I also noticed that when just importing ACL's or Topic's it does not pull any of the infrastructure for these.
Lastly is there any reason why the Connectors are not part of the importer? I think this would be extremely beneficial.

**Comment by YaseenHassanLiberty** [comment]
Hi @linouk23 

Thanks for the response. I see now that for ACL and Topics you would need to include the Kafka credentials within the provider and as you have mentioned it should be a separate import.

`terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.40.0"
    }
  }
}

provider "confluent" {
  cloud_api_key    = var.confluent_cloud_api_key
  cloud_api_secret = var.confluent_cloud_api_secret

  kafka_id            = var.confluent_kafka_Id
  kafka_rest_endpoint = var.confluent_kafka_rest_endpoint_url
  kafka_api_key       = var.confluent_kafka_api_key         
  kafka_api_secret    = var.confluent_kafka_api_secret
}

resource "confluent_tf_importer" "importer_test" {
  resources = ["confluent_kafka_topic"]
}
`

This seemed to have worked however I have reached another issue where while pulling my Topics I get the following error:
 Error: failed to run terraform CLI command: "terraform state replace-provider registry.terraform.io/-/confluent registry.terraform.io/confluentinc/confluent". Please run it manually in ./imported_confluent_infrastructure.
│
│   with confluent_tf_importer.importer_test,
│   on main.tf line 20, in resource "confluent_tf_importer" "importer_test":
│   20: resource "confluent_tf_importer" "importer_test" {

Please provide some insight as to what this issue is about?

Really looking forward to getting the confluent_connector as part of the import functionality.

**Comment by linouk23** [comment]
@YaseenHassanLiberty created a separate issue to track `confluent_connector`: https://github.com/confluentinc/terraform-provider-confluent/issues/248

Regarding

> Error: failed to run terraform CLI command: "terraform state replace-provider registry.terraform.io/-/confluent registry.terraform.io/confluentinc/confluent". Please run it manually in ./imported_confluent_infrastructure.

As the error message suggests, you should be able to fix it via
```
terraform state replace-provider registry.terraform.io/-/confluent registry.terraform.io/confluentinc/confluent
```
In general, it seems like TF Provider for Confluent didn't manage to locate your `terraform CLI` [binary](https://developer.hashicorp.com/terraform/downloads), did you [install](https://github.com/tfutils/tfenv) it already? What happens if you run `terraform version`?

**Comment by YaseenHassanLiberty** [comment]
@linouk23 
Running Terraform version shows me that I am running the latest version.
```
terraform version
Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/confluentinc/confluent v1.40.0
```
Note that the above imports Topics (not sure if it imports them all) but after approximately 22 minutes of running the import it gives me that above error message.

**Comment by linouk23** [comment]
@YaseenHassanLiberty thanks for waiting!

That's kinda OK if the script exits here, did you try following the error message and running
```
"terraform state replace-provider registry.terraform.io/-/confluent registry.terraform.io/confluentinc/confluent"
```
in `./imported_confluent_infrastructure` manually and complete the rest of [the doc](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/experimental-resource-importer) as usual?

BTW we also merged a support for `confluent_connector` in our internal repository and it'll be included in our next release.

**Comment by linouk23** [comment]
@YaseenHassanLiberty see the latest release (`1.42.0`) of TF Provider where we resolved https://github.com/confluentinc/terraform-provider-confluent/issues/248

**Comment by linouk23** [comment]
cc @YaseenHassanLiberty

**Comment by YaseenHassanLiberty** [comment]
@linouk23 Thanks for the insight!
I am happy to close this ticket, if I find that it has not imported all topics then I will reach out again.

Oh iv also tested the importing of connectors, all is working well so thanks for that as well!
