### ISSUE TITLE
Check for correctness of the tag names during "terraform plan"

### ISSUE THREAD

**Issue by S1M0NM** [confluentinc/terraform-provider-confluent#249]
See: https://github.com/confluentinc/terraform-provider-confluent/issues/174#issuecomment-1538746998

**Comment by zhenli00** [comment]
<img width="1203" alt="image" src="https://github.com/confluentinc/terraform-provider-confluent/assets/120421969/aefa6bdd-f79d-4292-a71c-501142ce7d0b">
The latest release includes this feature, please upgrade to 1.42.0 confluent provider.
