### ISSUE TITLE
Use DataSteward over EnvironmentAdmin in the example

### ISSUE THREAD

**Issue by S1M0NM** [confluentinc/terraform-provider-confluent#250]
Use DataSteward over EnvironmentAdmin in the [example](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/stream-catalog)

Based on the RBAC documentation, [DataSteward](https://docs.confluent.io/cloud/current/access-management/access-control/cloud-rbac.html#datasteward) should also be sufficient in this case.

**Comment by zhenli00** [comment]
we have updated the example with DataSteward, please check it out!
