### ISSUE TITLE
Unable to create confluent_kafka_cluster_config

### ISSUE THREAD

**Issue by nelisSpotOn** [confluentinc/terraform-provider-confluent#251]
Hello.

I am unable to create a `confluent_kafka_cluster_config` resource. I always get the following error when I try:

`error creating Kafka Config: 400 Bad Request: Altering resources of type BROKER is not permitted`

Here is an example of what I am trying to do:

```
terraform {
  required_providers {
    # ...
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.41.0"
    }
  }
}

provider "confluent" {
}

resource "confluent_environment" "development" {
  display_name = "Development"
}

resource "confluent_kafka_cluster" "basic" {
  display_name = "basic_kafka_cluster"
  availability = "SINGLE_ZONE"
  cloud        = "AWS"
  region       = "us-east-1"
  basic {}

  environment {
    id = confluent_environment.development.id
  }
}

resource "confluent_service_account" "app-manager" {
  display_name = "kafka-app-manager-service-account"
  description  = "Service Account to manage kafka cluster"
}

resource "confluent_role_binding" "app-manager" {
  principal   = "User:${confluent_service_account.app-manager.id}"
#  role_name   = "CloudClusterAdmin"
#  crn_pattern = confluent_kafka_cluster.basic.rbac_crn
  role_name   = "EnvironmentAdmin"
  crn_pattern = confluent_environment.development.resource_name
}

resource "confluent_api_key" "app-manager-kafka-api-key" {
  display_name = "kafka-cluster-api-key"
  description  = "Kafka API Key for cluster"
  owner {
    id          = confluent_service_account.app-manager.id
    api_version = confluent_service_account.app-manager.api_version
    kind        = confluent_service_account.app-manager.kind
  }

  managed_resource {
    id          = confluent_kafka_cluster.basic.id
    api_version = confluent_kafka_cluster.basic.api_version
    kind        = confluent_kafka_cluster.basic.kind

    environment {
      id = confluent_environment.development.id
    }
  }

  depends_on = [
    confluent_role_binding.app-manager
  ]
}

resource "confluent_kafka_cluster_config" "basic-config" {
  kafka_cluster {
    id = confluent_kafka_cluster.basic.id
  }
  rest_endpoint = confluent_kafka_cluster.basic.rest_endpoint
  config = {
    "auto.create.topics.enable" = "true"
    "log.retention.ms" = "604800123"
  }
  credentials {
    key    = confluent_api_key.app-manager-kafka-api-key.id
    secret = confluent_api_key.app-manager-kafka-api-key.secret
  }
}

```

Note, I am setting the CONFLUENT_CLOUD_API_KEY and CONFLUENT_CLOUD_API_SECRET environment variables.

**Comment by linouk23** [comment]
Thanks for creating the issue @nelisSpotOn!

It seems like you're using a basic Kafka cluster:
```
resource "confluent_kafka_cluster" "basic" {
  ...
  basic {}
  ...
}
```
but `auto.create.topics.enable` is only supported for dedicated Kafka clusters:
![image](https://user-images.githubusercontent.com/5459870/236922800-6f3ee468-f315-41d0-9849-98f6752cd237.png)

Let me know whether it helps.

**Comment by nelisSpotOn** [comment]
I still get this error if I only try to set the `log.retention.ms`. Is that option not allowed for `basic` either? Can you share a link to where this is documented?

Thanks.

**Comment by linouk23** [comment]
Sorry about that, here's a [link](https://docs.confluent.io/cloud/current/clusters/broker-config.html) to that doc.

> Is that option not allowed for basic either? 

That's right!

![image](https://user-images.githubusercontent.com/5459870/236955763-3c195470-14a7-4e5b-99e0-5b590854e262.png)

**Comment by linouk23** [comment]
@nelisSpotOn also see the description of `confluent_kafka_cluster_config` resource:
![image](https://user-images.githubusercontent.com/5459870/236957198-2586c30e-45c3-4a52-a954-99fb1eee3e5b.png)

**Comment by nelisSpotOn** [comment]
Thanks guys. I didn't notice that `confluent_kafka_cluster_config` was just for `Dedicated` clusters. According to the documentation `max.message.bytes` can be set on a `basic` cluster (to a max of 8388608). If `confluent_kafka_cluster_config` is only for `Dedicated` clusters, how do I set this value for a `basic` cluster?

**Comment by linouk23** [comment]
It looks like editing cluster settings is not supported for Basic / Standard clusters at all and you might have to set topic settings for each topic separately.

**Comment by linouk23** [comment]
cc @nelisSpotOn
