### ISSUE TITLE
API Key creation timeout on dedicated cluster

### ISSUE THREAD

**Issue by mallie-su** [confluentinc/terraform-provider-confluent#26]
Hello there!

We've encountered an issue while trying to create API keys on our new and only dedicated cluster for our production platform.
The error is the following :
```
Error: error waiting for Kafka API Key "[REDACTED]" to sync: error listing Kafka Topics using Kafka API Key "[REDACTED]": Get "[https://[REDACTED].europe-west1.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-[REDACTED]/topics](https://[REDACTED].europe-west1.gcp.confluent.cloud/kafka/v3/clusters/lkc-[REDACTED]/topics)": GET [https://[REDACTED].europe-west1.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-[REDACTED]/topics](https://[REDACTED].europe-west1.gcp.confluent.cloud/kafka/v3/clusters/lkc-[REDACTED]/topics) giving up after 5 attempt(s): Get "[https://[REDACTED].europe-west1.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-[REDACTED]/topics](https://[REDACTED].europe-west1.gcp.confluent.cloud/kafka/v3/clusters/lkc-[REDACTED]/topics)": net/http: TLS handshake timeout
```

The key is created and can be seen in the confluent website.
If we launch again the terraform script, as expected, a new key is created, and the same error appears.

Is it possible to increase the timeout? I didn't find anything in the documentation in this regard.

Thanks in the advance!

**Comment by linouk23** [comment]
👋 @mallie-su thanks for opening an issue!

Could you confirm the type of your dedicated cluster? If it's PL / Peering, make sure you run terraform within its VPC -- I suspect TF could not reach that endpoint at all.

**Comment by mallie-su** [comment]
Thank you a lot @linouk23, it's exactly our issue.
Our dedicated cluster is in peering with our VPC on GCP, and therefore not accessible though internet!
