### ISSUE TITLE
Error with HTTP Sink connector

### ISSUE THREAD

**Issue by VipulZopSmart** [confluentinc/terraform-provider-confluent#275]
I'm trying to provision the HTTP Sink connector by using the confluent_connector resource. I'm using a private endpoint(deployed in some particular VPC in some AWS account). I"m getting this error while provisioning the connector. Could you please help me in resolving this issue? and let me know what can i do to use this connector.
` Error: error waiting for Connector "http-sink-connector" to provision: connector "display_name"="http-sink-connector" provisioning status is "FAILED": Unable to validate the configuration. If an update was made to the configuration, this means that the configuration was invalid, and the connector continues to operate on a previous configuration that passed validation. Errors:
│ http.api.url: Connections to the resolved IP address(es) are not allowed`

**Comment by linouk23** [comment]
@VipulZopSmart thanks for creating this issue! Is it related to https://github.com/confluentinc/terraform-provider-confluent/issues/277?

**Comment by zhenli00** [comment]
Hi @VipulZopSmart , we got answer from our connect team:

```
the HTTP Sink Connector is expected to work with private endpoints that are in a customer's VPC if the connector is created in a VPC Peered or Transit Gateway attached Confluent Cloud network. The error that the user is seeing - Connections to the resolved IP address(es) are not allowed indicates that one of the above conditions isn't true - i.e. they're trying this on a public or PrivateLink Confluent Cloud network or else their configured IP isn't in their VPC's CIDR range.
```
