### ISSUE TITLE
Cannot seem to create ACLs on cluster named other than "kafka-cluster"

### ISSUE THREAD

**Issue by christiaanhoogendoorn** [confluentinc/terraform-provider-confluent#283]
Hi,

I am following these instructions to create ALCs with terraform on a cluster called **demo_basic_kafka_cluster**. (see terraform config below)
https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_acl

However, I get this error: _"Error: error creating Kafka ACLs: 400 Bad Request: The only valid name for the CLUSTER resource has to be "kafka-cluster"_ 

If I were to add an ACL manually to said Service Account via Confluent Cloud web UI in the demo_basic_kafka_cluster, I do not even have the option to choose "kafka-cluster" (Confluent Cloud UI automatically chooses "demo_basic_kafka_cluster" (see screenshot). So also Confluent Cloud "wants" to set the clustername to "demo_basic_kafka_cluster" as well. But Terraform does not allow me to do it, throwing the error above error.

Of course there are very likely to be be (multiple) clusters with names other then "kafka-cluster". I may be doing something wrong, but so far this seems like a bug?

```resource "confluent_kafka_acl" "describe-basic-cluster" {
  kafka_cluster {
    id = confluent_kafka_cluster.basic.id
  }
  resource_type = "CLUSTER"
  resource_name = "demo_basic_kafka_cluster"
  pattern_type  = "LITERAL"
  principal     = "User:sa-SOMEUSERPRINCIPAL"
  host          = "*"
  operation     = "DESCRIBE"
  permission    = "ALLOW"
  rest_endpoint = "<SOME RESTENDPOINT>"
  credentials {
    key    = "SOME KEY"
    secret = "SOME SECTET"      
  }

  lifecycle {
    prevent_destroy = false
  }
}

![ccloud](https://github.com/confluentinc/terraform-provider-confluent/assets/15835521/277c7c4f-b0db-4904-8af7-5f269fd21cef)

**Comment by linouk23** [comment]
Thanks for creating this issue @christiaanhoogendoorn!

When creating ACLs for Kafka cluster a user has to hardcode both attributes (resource type and resource name):
```
resource_type = "CLUSTER"
resource_name = "kafka-cluster"
```

and the backend is able to identify a cluster by looking at `kafka_cluster { id }` instead.

Thanks!
