### ISSUE TITLE
confluent_role_binding wildcard encoding causes plan to replace every time

### ISSUE THREAD

**Issue by pwmcintyre** [confluentinc/terraform-provider-confluent#285]
when using wildcards in `confluent_role_binding`, you will find terraform will attempt to replace the resource every time

here's my resource

```terraform
resource "confluent_role_binding" "schema_registry" {
  for_each    = var.topics
  principal   = "User:${confluent_service_account.account.id}"
  role_name   = "DeveloperRead"
  crn_pattern = join("/", [
    "crn://confluent.cloud"
    , "organization=${ var.confluent_organisation_id }"
    , "environment=${ var.confluent_environment_id }"
    , "schema-registry=${ var.confluent_schema_registry_id }"
    , "subject=${ each.key }-value"
  ])
}
```

and here's the log ... every time:

```
  # module.apps["data-backbone-databases"].confluent_role_binding.schema_registry["rtl-lifecycle.dev.public.*"] must be replaced
-/+ resource "confluent_role_binding" "schema_registry" {
      ~ crn_pattern = "crn://confluent.cloud/organization=03cd3b65-18ea-4118-af96-5bd8554ac7ca/environment=env-k5372/schema-registry=lsrc-9kw3nm/subject=rtl-lifecycle.dev.public.%2A-value" -> "crn://confluent.cloud/organization=____/environment=env-k5372/schema-registry=____/subject=rtl-lifecycle.dev.public.*-value" # forces replacement
      ~ id          = "rb-romZq" -> (known after apply)
        # (2 unchanged attributes hidden)
    }
```

you can see how something is encoding the `*` to `%2A`, which is causing issues with the change detection

**Comment by linouk23** [comment]
Thanks for creating this issue @pwmcintyre!

Could you share a super simple example that could help us to reproduce this issue? Thanks!

**Comment by pwmcintyre** [comment]
Through experimentation, I have found that you can't have `*` in the middle of a string, only the end.

As in, only "wildcard **_prefixes_**" are valid.

So while I don't know what is causing this issue, it is not a valid configuration anyway.

Ideally, something somewhere would throw an error, but probably the confluent API should 🤔

**Comment by linouk23** [comment]
That's a great point! Could you share a role binding definition where  you had`*` in the middle of the string and the creation was successful? Thanks! cc @pwmcintyre

**Comment by pwmcintyre** [comment]
@linouk23 sorry i supplied the wrong resource in my original comment, updated now ... maybe you can see now how i could end up with a wildcard in the middle of the subject name

i've updated my terraform to better detect wildcards and ensure i don't get any in the middle of a string:

```terraform
resource "confluent_role_binding" "schema_registry" {
  for_each    = var.topics
  principal   = "User:${confluent_service_account.account.id}"
  role_name   = "DeveloperRead"
  crn_pattern = join("/", [
    "crn://confluent.cloud"
    , "organization=${ var.confluent_organisation_id }"
    , "environment=${ var.confluent_environment_id }"
    , "schema-registry=${ var.confluent_schema_registry_id }"
    , "subject=${ each.key }${ endswith( each.key, "*" ) ? "" : "-value" }"
  ])
}
```

**Comment by linouk23** [comment]
> i've updated my terraform to better detect wildcards and ensure i don't get any in the middle of a string

That sounds great @pwmcintyre!

Is there anything else we can help you with here?
