### ISSUE TITLE
(schema-registry): Invalid Version Exception: 0

### ISSUE THREAD

**Issue by liveFreeOrCode** [confluentinc/terraform-provider-confluent#286]
:wave: I am trying to follow this example: https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-proto-schema

## The code

My own code is basically this: (don't mind the non-prd stuff, need duplicates of everything for "prevent_destroy" 😢)

```terraform
resource "confluent_schema" "non_prd_billing_common" {
  format       = "PROTOBUF"
  schema       = file("../../../private/billing/common/common.proto")
  subject_name = "private/billing/common/common.proto"

  lifecycle {
    prevent_destroy = false
  }
}

data "confluent_schema" "non_prd_billing_common" {
  subject_name      = confluent_schema.non_prd_billing_common.subject_name
  schema_identifier = confluent_schema.non_prd_billing_common.schema_identifier
}

resource "confluent_schema" "non_prd_billing_customers_value" {
  format       = "PROTOBUF"
  schema       = file("../../../private/billing/customers/value-schema.proto")
  subject_name = format("%s.%s", var.environment, "private.billing.customers-value")

  schema_reference {
    name         = "private/billing/common/common.proto"
    subject_name = confluent_schema.non_prd_billing_common.subject_name
    version      = data.confluent_schema.non_prd_billing_common.version
  }

  lifecycle {
    prevent_destroy = false
  }
}
```

## Plan

When I run `terraform plan`, I get the following error:

```sh
Error: error validating Schema: error validating a schema: [Invalid schema {subject=lsrc-81kzjq_stg.private.billing.customers-value,version=0,id=-1,schemaType=PROTOBUF,references=[{name='private/billing/common/common.proto', subject='private/billing/common/common.proto', version=0}],metadata=null,ruleSet=null,schema=syntax = "proto3";
│
│ ... proto redacted
│
│ } with refs [{name='private/billing/common/common.proto', subject='private/billing/common/common.proto', version=0}] of type PROTOBUF, details: io.confluent.kafka.schemaregistry.exceptions.InvalidVersionException: 0]
│
│   with module.schemas.confluent_schema.non_prd_billing_customers_value,
│   on ../modules/schemas/main.tf line 175, in resource "confluent_schema" "non_prd_billing_customers_value":
│  175: resource "confluent_schema" "non_prd_billing_customers_value" {
```

**Comment by linouk23** [comment]
@liveFreeOrCode could you confirm you're able to create your [schema](https://docs.confluent.io/cloud/current/sr/schema_registry_ccloud_tutorial.html#viewing-schemas-in-sr) via UI and it passes its validation?

**Comment by liveFreeOrCode** [comment]
I can try that, but here is my assumption:

- The _common_ schema does not exist in Confluent yet, and so it's trying to validate a schema that needs to use that common/shared proto definition and it's failing

Some other information I've uncovered while troubleshooting:

I modified the schema_reference.name to be `format("%#v", confluent_schema.non_prd_billing_common.version)`, and that prints out a UUID.  `version` from `data.confluent_schema` is noted as a _number_

Also, when I hardcode the version:

- `1`: It says InvalidVersionException: 0 (it does not acknowledge 1)
- `10`: It says InvalidVersionException: 10 (it does acknowledge 10)

**Comment by linouk23** [comment]
Thanks for the investigation!

On a high level, it might be helpful to figure out whether it's a TF / backend issue first (by trying out schema creation in UI) and then we could route this request to a relevant team (TF or SR backend team) to figure out what exactly has failed.

**Comment by linouk23** [comment]
cc @liveFreeOrCode

**Comment by linouk23** [comment]
Please let us know whether schema creation works via the UI, @liveFreeOrCode, so that we can route this issue accordingly. It would also be helpful if you could share the schema itself (with all sensitive information redacted). Thank you!

**Comment by bengesoff** [comment]
@linouk23 I've got the same issue in the Terraform provider and the UI. I've got one protobuf schema (schema A) that imports a message from another schema (schema B). I can successfully add schema B via the UI, but when I try to add schema A, I get the error message with "invalid version exception: 0".

The process is similar with Terraform except I can explicitly set `schema_reference`s (like the example), though the same exception happens when applying a plan with both schemas.

**Comment by bengesoff** [comment]
To add to this - I've managed to successfully create the schemas by correcting the `subject_name` (which I may have specified wrongly originally) and then targetting the resources in order using `terraform apply -target='module.xyz.confluent_schema.xyz'`.

My theory is the problem could be that there's a schema validation check during the [resource's `CustomizeDiff`](https://github.com/confluentinc/terraform-provider-confluent/blob/0fbb2353c6d75dcbf6a84764d8cce350469bfcc5/internal/provider/resource_schema.go#L159), which fails when the dependent schemas don't exist yet. Given that this `CustomizeDiff` runs during the "plan" stage, rather than the "apply" stage, there's no way that the `schema_reference` can contain a valid schema version, as it will always run before the referenced schemas exist. In this case, I think the fix would be something like skipping the validation check if the schema is new, or if it contains references that don't exist (e.g. maybe version=0 implies that it hasn't been computed yet, or `diff.NewValueKnown()` is `false`).

In the plan, it shows up as `version = (known after apply)` so maybe the validation check needs to be done during the resource creation/update function instead, so it happens as per Terraform's DAG walk when the dependencies have been created, rather than the planning stage.

I only skimmed the code for a minute so I may be wrong!

**Comment by zerogee00** [comment]
I am having the exact same issue and I can only fix it by downgrading to 1.42.0. Is there a fix in the works so we don't need to be locked to an older version?

**Comment by ekozynin** [comment]
I am facing the same issue, and can confirm that downgrading from 1.61.0 to 1.42.0 makes it work.

**Comment by nikolai-fra** [comment]
We're facing the same issue. 
Seperating the plan/apply step for the first schema and the second schema (referencing the first one) is our workaround.
Overriding the version to 1, when creating both schemas in one step, isn't working as said before in the comment [above](https://github.com/confluentinc/terraform-provider-confluent/issues/286#issuecomment-1632914713)

**Comment by bogdanaioanei** [comment]
We have also tested with downgrading to 1.42.0 and that works but in the end we're gonna go with the same solution @nikolai-fra went with. It would be great if the validation wouldn't be part of the `plan` phase and let people rely on the terraform dependency graph (with or without setting `depends_on`) to get the schemas properly created in the `apply` phase

**Comment by linouk23** [comment]
Addressing this issue is on our roadmap for sure!

> @linouk23 I reverted the provider to version 1.42.0 (before [your change adding the schema validation to the CustomizeDiff](https://github.com/confluentinc/terraform-provider-confluent/commit/b12fe6e80216b4547c737c14357f0af89c602498)) and the code worked without any resource targetting. Do you think you might be able to have a look? I haven't tried running the official examples with the latest version of the provider, but maybe they have the same issue? @liveFreeOrCode not sure if you're still having the same issue, but a temporary workaround could be to downgrade the version of the provider

We'll likely implement this option or add an optional `skip_validation` boolean flag or something, thanks for waiting!

**Comment by linouk23** [comment]
@liveFreeOrCode @bogdanaioanei @nikolai-fra we've got a quick question: could one of you please share a minimal reproducible example? It would make it easier for us to verify the fix.

**Comment by channingdong** [comment]
@liveFreeOrCode @bogdanaioanei @nikolai-fra 
Thank you for the patience and please use the latest version v1.79.0 to validate the fix.

You just need to set:
`skip_validation_during_plan = true`
in your configuration file to address your specific cases, please note that the schema validation will still be executed during `terraform apply` even if you skip it for plan, but it won't run into the exception issue anymore during `terraform apply`.

**Comment by channingdong** [comment]
In the top most example, it should look like this:

```
resource "confluent_schema" "non_prd_billing_customers_value" {
  format       = "PROTOBUF"
  schema       = file("../../../private/billing/customers/value-schema.proto")
  subject_name = format("%s.%s", var.environment, "private.billing.customers-value")
  skip_validation_during_plan = true

  schema_reference {
    name         = "private/billing/common/common.proto"
    subject_name = confluent_schema.non_prd_billing_common.subject_name
    version      = data.confluent_schema.non_prd_billing_common.version
  }

  lifecycle {
    prevent_destroy = false
  }
}
```

**Comment by channingdong** [comment]
You can also refer to the official document about how to use this flag:
https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema#skip_validation_during_plan
