### ISSUE TITLE
can't create confluent_cluster_link between a private cluster and public cluster

### ISSUE THREAD

**Issue by javiervelamindcurv** [confluentinc/terraform-provider-confluent#287]
Hello,

- I deployed one dedicated Kafka cluster (private) and a dedicated Kafka clusuter (public)
- I created two API keys (one per each cluster) and I assigned the role `CloudClusterAdmin`

I try to create a `confluent_cluster_link`  between both cluster (private is the source and public is the destination) I get the error 

`Error: error creating Cluster Link: 401 Unauthorized: Not authorized: the authenticated user didn't have the right access to the resource: Cluster authorization failed.`

How can I know where the problem is? - the error doesn't help.

thanks,

**Comment by linouk23** [comment]
👋 @javiervelamindcurv thanks for creating this issue!

It seems like your setup is [supported](https://docs.confluent.io/cloud/current/multi-cloud/cluster-linking/private-networking.html#cluster-linking-private-to-public): 
![image](https://github.com/confluentinc/terraform-provider-confluent/assets/5459870/b77f114c-a532-46a2-a3d3-d2e94e91973c).

Could you confirm you used [this example](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/source-initiated-cluster-link-rbac) and it didn't work?

**Comment by javiervelamindcurv** [comment]
I'm checking my code. the example works.

thanks @linouk23
