### ISSUE TITLE
How to :  Substitute user-id for a given user email

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluent#29]
To assign RBAC roles (DeveloperRead as example), is there a way to automate the process in terraform for extracting the user-id for a given user email address?

Currently,  the CLI command I use to find the user id for an email is as follows
```
confluent iam user list \                                                                        
    -o json \
| jq '.[] | select(.email == "first.last@company.com") | .id'
```

It would be nice to have some block in terraform that took the email id and could output the user id that can be used in the RBAC block. 

Thanks

**Comment by linouk23** [comment]
👋 , thanks for opening an issue @bluedog13!

You could leverage `confluent_user` [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_user) as well:
```
data "confluent_user" "example_using_email" {
  email = "test123@gmail.com"
}

resource "confluent_role_binding" "test-role-binding" {
  principal   = "User:${data.confluent_user.example_using_email.id}"
  role_name   = "CloudClusterAdmin"
  crn_pattern = confluent_kafka_cluster.standard-cluster-on-aws.rbac_crn 
}
```

It also supports other inputs like `full_name / id`, find more details [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_user).

There's also a matching data source for a service account too:
```
data "confluent_service_account" "example_using_name" {
  display_name = "test_sa"
}

resource "confluent_role_binding" "test-role-binding" {
  principal   = "User:${data.confluent_service_account.example_using_name.id}"
  role_name   = "CloudClusterAdmin"
  crn_pattern = confluent_kafka_cluster.standard-cluster-on-aws.rbac_crn 
}
```

Let me know if it helps!

**Comment by bluedog13** [comment]
Thank you so much.  This is exactly what I was looking for (confluent_user block).
