### ISSUE TITLE
KsqlDB app creation with terraform ?

### ISSUE THREAD

**Issue by sourabhkrishna** [confluentinc/terraform-provider-confluent#3]
Is there a plan for tf providers for working with KSQLDB app be available ?

**Comment by SebaLG** [comment]
Any details about it? Thanks!

**Comment by tfindlay-au** [comment]
So excited for this. I'm happy to build the provider from source and beta test anything.

**Comment by linouk23** [comment]
We've just [released](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#130-august-29-2022) version `1.3.0` of TF Provider where we added new 

* `confluent_ksql_cluster` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_ksql_cluster)
* `confluent_ksql_cluster` [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_ksql_cluster)

in an [Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy).

We'll be very excited to hear your feedback about it!

cc @tfindlay-au @SebaLG @sourabhkrishna @mattyev87 @ssemyonov @javiervelamindcurv @AlexVasiukov  @simonschmidt @miguelaferreira @de1et3d

**Comment by tfindlay-au** [comment]
This worked perfectly for me. It does take time to provision KSQL, in my case Terraform took 9m29s
```
module.ksql_cluster.confluent_ksql_cluster.ksql-cluster: Creation complete after 9m29s [id=lksqlc-12o5zj]
```
... but aside from the time, it works perfectly. Thank you so much.

**Comment by ConfluentSpencer** [comment]
@tfindlay-au would you be open to sharing more about your use cases and why the KSQL resource is important for you? Would love to have a discussion on our community slack channel:
https://confluentcommunity.slack.com/archives/C02JJ23HZD3

**Comment by tfindlay-au** [comment]
Just one thought - after creation, there seems to be no data block/output variable to determine the cluster endpoint ?
eg. https://pksqlc-d0gw1.ap-southeast-2.aws.confluent.cloud

This does appear in the state file as `http_endpoint`, but does not seem to be available to use ?
```
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "api_version": "ksqldbcm/v2",
        "credential_identity": [
          {
            "id": "sa-<account>>"
          }
        ],
        "csu": 1,
        "display_name": "InputToOutput",
        "environment": [
          {
            "id": "env-<environment>"
          }
        ],
        "http_endpoint": "https://pksqlc-d0gw1.ap-southeast-2.aws.confluent.cloud:443",
        "id": "lksqlc-81jj3m",
        "kafka_cluster": [
          {
            "id": "lkc-<cluster>"
          }
        ]
      }
    }
  ]
```
I think this might be useful to have available ?

**Comment by linouk23** [comment]
I'm not sure I got the question right. `http_endpoint` is a computed attribute: 
![image](https://user-images.githubusercontent.com/5459870/187817275-89c4a019-1854-4f8f-a117-0d84c8753356.png)
that you can reference as `confluent_ksql_cluster.example.http_endpoint` or
```
output "foo" {
  value = confluent_ksql_cluster.example.http_endpoint
}
```

**Comment by tfindlay-au** [comment]
Thanks for following up, I did see it in the documentation, but it just shows as red in IntelliJ, I think its just an IDE issue.
![image](https://user-images.githubusercontent.com/9065936/187822600-086ebb4d-514f-41d1-8ae1-6be6010a32ea.png)

I confirmed the output is indeed populated when running in terraform.

**Comment by linouk23** [comment]
That's right, I don't think IntelliJ "recognizes" computed property by default 😕
