### ISSUE TITLE
Output Egress IPs for connectors

### ISSUE THREAD

**Issue by ecukuroglu** [confluentinc/terraform-provider-confluent#300]
It is possible to get Egress IPs with Confluent Cloud APIs as the link below.
https://docs.confluent.io/cloud/current/api.html#tag/IP-Addresses-(networkingv1)/operation/listNetworkingV1IpAddresses

Can we include this into the terraform outputs?

Thanks

**Comment by linouk23** [comment]
In other words, looks like the ask here is to add a new data source for `IP Addresses` resource.

**Comment by fol-angkas** [comment]
Either via data source or part of the resource applied metadata so it will be shown during

`terraform state show confluent_kafka_cluster.my_cluster`

**Comment by kabraham13** [comment]
@linouk23 any sense of when you all will be able to get to this?

**Comment by linouk23** [comment]
@kabraham13 we're trying to prioritize it for Q4.

**Comment by linouk23** [comment]
@ecukuroglu @kabraham13 we have released a data source for Egress IPs in the latest [version](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.55.0) 1.55.0:

![image](https://github.com/confluentinc/terraform-provider-confluent/assets/5459870/14e7e274-681c-4a27-92fe-c7eb11fc2fff)
