### ISSUE TITLE
RBAC to control center

### ISSUE THREAD

**Issue by Davinder2609** [confluentinc/terraform-provider-confluent#304]
I need to provide DeveloperRead Access to user in control center
Any documentation !

**Comment by linouk23** [comment]
@Davinder2609 thanks for creating this issue!

You might want to take a look at:

* https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_role_binding
* https://docs.confluent.io/cloud/current/access-management/access-control/rbac/predefined-rbac-roles.html
