### ISSUE TITLE
RBAC for Control Center

### ISSUE THREAD

**Issue by Davinder2609** [confluentinc/terraform-provider-confluent#305]
How we can provide DeveloperRead Access Schema in Control Center

**Comment by linouk23** [comment]
👋 thanks for creating this issue @Davinder2609 !

As of right now, TF Provider for Confluent only supports Confluent Cloud. Does that answer your question?

**Comment by Davinder2609** [comment]
@linouk23  Yes! Thanks !

**Comment by linouk23** [comment]
Feel free to subscribe to https://github.com/confluentinc/terraform-provider-confluent/issues/145's updates too.
