### ISSUE TITLE
Confluent Invitation/Confluent User

### ISSUE THREAD

**Issue by harideveloper** [confluentinc/terraform-provider-confluent#313]
Hi Team,

I'm exploring the idea of managing users, user roles & permissions in terraform as a single source of truth. I've seen couple of issues related to this confluent user/confluent invitation resource, but i've not success following them. I'd appreciate if the below questions could be clarified , thanks

**Question 1 :** 

I'd like to create multiple role binding for multiple users, essential an email group or group of email ids.

```
E.g : If i'd to create 2 users , i'd have to follow the below structure 

// Users

variable "users" {
  type = list(string)
  default = [
    "user1@gmail.com",
    "user2@gmail.com",
  ]
}

resource "confluent_invitation" "invite" {
  for_each  = toset(var.users)
  email     = each.value
  auth_type   = "AUTH_TYPE_LOCAL"
}

resource "confluent_role_binding" "env-admin-user1-rb" {
   principal   = "User:${confluent_invitation.invite[0].id}"
   role_name   = "EnvironmentAdmin"
   crn_pattern = confluent_environment.env.resource_name
   depends_on = [ confluent_invitation.invite-1 ]
 }

resource "confluent_role_binding" "env-admin-user2-rb" {
   principal   = "User:${confluent_invitation.invite[1].id}"
   role_name   = "EnvironmentAdmin"
   crn_pattern = confluent_environment.env.resource_name
   depends_on = [ confluent_invitation.invite-2 ]
 }
```

I was going to ask if the below is possible for the role binding to bind group of users.

```
resource "confluent_role_binding" "env-admin-users-rb" {
   principal   = "Users:${confluent_invitation.invite[key].id}" ---> Can it take an array ??
   role_name   = "EnvironmentAdmin"
   crn_pattern = confluent_environment.env.resource_name
   depends_on = [ confluent_invitation.invite-2 ]
 }
```

Question 2 : 

In the previous example let's say user 2 has accepted the invite but i'd to remove the user. I'd update the tf configs to remove the user , but i end with the error : unable to remove user with the error : 400 Bad Request: Bad Request. The invitation was already accepted. I've seen https://github.com/confluentinc/terraform-provider-confluent/issues/263 for similar issue but i'd like understand what is the way forward in these scenarios. Is the allow_deletion flag in use ?

Question 3 - Related to https://github.com/confluentinc/terraform-provider-confluent/issues/266

I've seen there was a request for documentation for confluent user & confluent invitation and the below link is shared. I'm unable to access the below link, I'd greatly appreciate it if it's possible to share the examples as comments. thanks

There's an example here -- https://confluent.slack.com/archives/CM04M1UF4/p1686329639663079?thread_ts=1679674587.247499&cid=CM04M1UF4

**Comment by linouk23** [comment]
👋 , thanks for asking @harideveloper!

Question 1:
```
I was going to ask if the below is possible for the role binding to bind group of users.

resource "confluent_role_binding" "env-admin-users-rb" {
   principal   = "Users:${confluent_invitation.invite[key].id}" ---> Can it take an array ??
   role_name   = "EnvironmentAdmin"
   crn_pattern = confluent_environment.env.resource_name
   depends_on = [ confluent_invitation.invite-2 ]
 }
```
It is not possible at the moment.

Question 2 :
That flag wasn't added yet, you might want to leave a comment in #263 so we could prioritize that issue.

Question 3:
Updated the link 👌 

Let us know if that helps!

**Comment by harideveloper** [comment]
Question 1 - Thanks for the feedback
Question 2 - Updated the comments in there, will follow on with comments on https://github.com/confluentinc/terraform-provider-confluent/issues/263

Question 3 - Thanks, Will follow up on issue: 266
