### ISSUE TITLE
schema content is not updated in state file during refresh

### ISSUE THREAD

**Issue by Noel-Jones** [confluentinc/terraform-provider-confluent#318]
Initially my state file showed "schema_identifier": 100121 and "version":13. I could also see an enumeration with 6 countries in the schema within the state. However, the schema has been updated on CC and the schema has 100+ countries in the enumeration now. 

I am seeing odd things:

1. If I supply the old version of the schema to Terraform then it errors because the schema validation does not like that the schema being supplied has missing enumerations. This is understandable, backward compatibility check failing.
2. If I suppy the new version of the schema to Terraform then it tells me that it will add around 100 values to the enumeration. **This is clearly wrong because on CC the enumeration already has them.**

Next I perform a terraform refresh. The state file now shows "schema_identifier": 100139 and "version": 15. (I'm not going to look into what version 14 was). However, the schema within the state file still only contains the 6 countries. During the refresh the schema held in the state is not updated. As a result I still see the same odd things - In case 2, Terraform telling me that the schema needs updating despite the fact that it doesn't.

**Comment by Noel-Jones** [comment]
I am working on a change. It is looking promising. It planned 6 additional changes that were previously unseen. One expected (as in the one that put me on to the issue). 3 appear to be down to field ordering, which as far as I can see should not be reported as a change. I'm trying to identify what the cause of this might be.

**Comment by linouk23** [comment]
https://github.com/confluentinc/terraform-provider-confluent/pull/322#issuecomment-1783307749

**Comment by Noel-Jones** [comment]
@linouk23 could I please get an update on this. I am still forced to use my developer override version of the provider to manage my schema which is not good and prevents me from maaging the schema in our CI/CD pipelines.

**Comment by linouk23** [comment]
@Noel-Jones 

update: we've merged your #322 in [version](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1700-april-9-2024) `1.70.0` of TF Provider. Thanks for contributing the fix, and let us know if that resolves this issue. Thanks again!

**Comment by Noel-Jones** [comment]
@linouk23 Yes, with the previous version (actually 1.61) terraform only detected one schema resource needed changing, with the new version it reports that there are two that need changing. Awesome, thank you.
