### ISSUE TITLE
PGP Keys are outdated

### ISSUE THREAD

**Issue by anfigueroa** [confluentinc/terraform-provider-confluent#319]
As of today we're getting the following error whenever trying to use the provider

![image](https://github.com/confluentinc/terraform-provider-confluent/assets/119603038/9e5a8cdf-ac82-424d-b164-ef7dda9536c3)

```
╷
│ Error: Failed to install provider
│ 
│ Error while installing confluentinc/confluent v1.[54](https://github.com/jucr-io/jucr-confluent-clusters-tf/actions/runs/6486132264/job/17613668218#step:6:55).0: error checking
│ signature: openpgp: key expired
╵
```

This is a blocker for our development process. Is there an ETA for a fix?

**Comment by linouk23** [comment]
Thanks for creating this one!

It seems to be a duplicate of https://github.com/confluentinc/terraform-provider-confluent/issues/315.
