### ISSUE TITLE
confluent_service_account : can't deal with manually deleted service accounts

### ISSUE THREAD

**Issue by neuweiler** [confluentinc/terraform-provider-confluent#32]
If you happen to delete a service account via CLI which was created via TerraForm, the provider is unable to deal with the fact that the service account is still in the TF-state but no longer on confluent cloud itself. The only way out at the moment is, to delete the TF-state and drop the affected environment (incl. cluster and topics). This is a major problem for in-production systems.
Other TF providers (like azurem) can update the TF-state to reflect externally deleted resources - as can confluent_kafka_topic.

I'm not sure about externally modified/deleted ACLs (confluent_kafka_acl), API-Keys (confluent_api_key) or role bindings (confluent_role_binding) and after cleaning up a dead-lock just now I'd rather not test it. But please also verify if these modules are able to cope with external midifications.

**Comment by linouk23** [comment]
Thanks for reporting an issue @neuweiler!

We'll investigate it and report back!

**Comment by linouk23** [comment]
@neuweiler could you confirm which version of TF Provider for Confluent you're using? I didn't manage to reproduce it for `0.8.0`:

1. Here's my TF configuration file
```
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "0.8.0"
    }
  }
}

provider "confluent" {
  api_key    = var.confluent_cloud_api_key
  api_secret = var.confluent_cloud_api_secret
}

resource "confluent_service_account" "test" {
  display_name = "orders-app-sa123"
  description  = "Service Account for orders app"
}
```

2. Run `terraform apply` to create a new service account.
3. Deleted it using CLI
```
➜  demo git:(master) ✗ confluent iam service-account delete sa-nvznxv
Deleted service account "sa-nvznxv".
```
4. When I run `terraform apply` (while deleted SA is still in TF state) I can see:
```
➜  demo git:(master) ✗ terraform plan                                
confluent_service_account.test: Refreshing state... [id=sa-v73xn5]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # confluent_service_account.test will be created
  + resource "confluent_service_account" "test" {
      + api_version  = (known after apply)
      + description  = "Service Account for orders app"
      + display_name = "orders-app-sa123"
      + id           = (known after apply)
      + kind         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```
5. When I run `terraform apply`, I can see 
```
confluent_service_account.test: Refreshing state... [id=sa-nvznxv]
confluent_service_account.test: Creating...
confluent_service_account.test: Creation complete after 1s [id=sa-v73xn5]
```
6. And the only SA in TF state has `sa-v73xn5` now.

Let me know if that makes sense.

**Comment by linouk23** [comment]
👋 @neuweiler, could you take a look at ⬆️ ?

**Comment by neuweiler** [comment]
I was using 0.7.0 - will need to re-test with 0.8.0 on a separate environment later - not feasible at the moment due to go-live. I'm fine if you say it works now. You can close the ticket.
