### ISSUE TITLE
Error deleting Role Binding roles. : giving up after 5 attempt(s)

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluent#33]
I am repeatedly getting error when trying to update/destroy a plan that involves Role Binding.  There is no problem creating one, but deletion or updates have not been possible today at all. 

Below is the error
```
│ Error: error deleting Role Binding "rb-*****": Delete "https://api.confluent.cloud/iam/v2/role-bindings/rb-*****": DELETE https://api.confluent.cloud/iam/v2/role-bindings/rb-***** giving up after 5 attempt(s)
```

All this worked fine till this am, but then....it's been Error all the time. 

Thanks

**Comment by linouk23** [comment]
Thanks for creating an issue, we're investigating it internally.

**Comment by linouk23** [comment]
Could you try again? We believe we've just deployed a fix.

**Comment by linouk23** [comment]
cc @bluedog13

**Comment by bluedog13** [comment]
Seems to work now.  

May I know what was causing this?  The reason for asking is, if we encounter something like this in PROD, how do we debug or try to figure out if the issue is TF related or Kafka cluster related?

**Comment by linouk23** [comment]
Hopefully it didn't block your team for too long, It was an issue related to our backend.

It might be a good idea to try to curl [corresponding API endpoint](https://docs.confluent.io/cloud/current/api.html#tag/Role-Bindings-(iamv2)) directly to figure out whether it's TF or API related.
