### ISSUE TITLE
RBAC support for "DataDiscovery" in Terraform

### ISSUE THREAD

**Issue by gautam-goudar** [confluentinc/terraform-provider-confluent#335]
Do we have support to add "DataDiscovery" RBAC in Terraform?

I went over the docs but did not find the required details to set the "crn_pattern" for the same
https://github.com/confluentinc/terraform-provider-confluent/blob/master/docs/resources/confluent_role_binding.md

Please help.

**Comment by linouk23** [comment]
Thanks for creating this issue @gautam-goudar and I'm not sure how I missed it 😕 

TF definitely supports `DataDiscovery` and the CRN pattern depends on the [scope](https://docs.confluent.io/cloud/current/access-management/access-control/rbac/predefined-rbac-roles.html#datadiscovery).

**Comment by gautam-goudar** [comment]
Can you share an example for the same?
