### ISSUE TITLE
Creating and managing user groups

### ISSUE THREAD

**Issue by S1M0NM** [confluentinc/terraform-provider-confluent#338]
Confluent Cloud has added the function of creating user groups and giving them role bindings.
This allows management of permissions across groups during SSO login (see: https://docs.confluent.io/cloud/current/api.html#tag/Group-Mappings-(iamv2sso))

It would be nice to be able to create and manage these user-groups using terraform and assign role bindings to them.

Attributes:
description (optional - Cloud UI sends empty string if not set)
display_name (required)
filter (required)

Exported Attributes:
id (e.g. "group-abCD")

```
resource "confluent_user_group" "example" {
  display_name = "My User Group" # required
  description "My User Group Description" # optional Cloud UI sends empty string
  filters = " \"user_group\" in groups " # required
}
```

```
data "confluent_user_group" "example" {
  id = "group-abCD"
}
```

**Comment by linouk23** [comment]
@S1M0NM thanks for creating this issue!

We hope we'll be able to release it next week 👍

**Comment by linouk23** [comment]
@S1M0NM @petrkarytka @oh-nathaniel-bobrick

Update: we

> Added new confluent_group_mapping [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_group_mapping) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_group_mapping) in a [General Availability lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy) (https://github.com/confluentinc/terraform-provider-confluent/issues/338).

in our latest [1.56.0](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1560-december-12-2023) version of TF Provider.
