### ISSUE TITLE
Question : What is the best practice to create "n" topics ( n>=100) in terraform

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluent#34]
This is more of seeking for input/guidance/best practices for creating a large number of topics in a given environment. 

Current, I am using one file per topic to declare the respective resource blocks 
1. Topic Name
2. Producers and Producer ACL's
3. Consumers and Consumer ACL's.

Most of the code is very similar and repetitive and follows the same pattern except for the names.

What is the suggested best practice to create topics and respective producer and consumers?
1. Declare each of them seperately
2. Use like a module and inject the names for each topic.
     - If this approach is possible, will be okay to **create resources inside a dynamic block and use for-each** and reach the input that contains the list of topics and respective producer and consumer names?
     

Thanks

**Comment by bluedog13** [comment]
Update
---
I was able to use "modules" to provision
(1) topics
(2) service accounts (with and without RBAC)

At this point, I am not sure if having dynamic block to iterate over inputs makes more sense than to have modules (which require the variables to be passed).  Either way, the amount of code in lines (config vs modules) tends to remain close.

I feel having modules is better tradeoff when it comes to understanding the code and the intent.

**Comment by linouk23** [comment]
👋 thanks for creating an issue!

I don't have a strong opinion about it, I'll keep this open to see if any of the users have any interesting ideas.

**Comment by krishnan-mani** [comment]
This is a very good question that I would also like to get some diverse opinions and suggestions for.

What comes to mind is: one can use modules that encapsulate repetitive terraform code for the topic resource, as well as organise the references to the module to create multiple topics into any number of files (each file groups related resources together, purely for human readability, and control). `terraform` merges together any number of valid configuration files in a given folder when considering the configuration
