### ISSUE TITLE
Request: allow export of API keys with confluent_tf_importer

### ISSUE THREAD

**Issue by rgraber** [confluentinc/terraform-provider-confluent#344]
We are trying to move a few medium-sized clusters into terraform. We originally created them in the Confluent Console UI, including several API keys for different services. Importing all these keys manually into terraform is a pain. It would be helpful if these could be imported as part of the confluent_tf_importer resources.

**Comment by linouk23** [comment]
@rgraber thanks for creating this issue!

We thought a bit about it before and we could see 2 scenarios:

1. Somehow Importer tool is able to infer API Keys' secrets automatically. Unfortunately, I don't think it's possible as API Key Mgmt API follows the best security practices and doesn't include secret in `GET` [request](https://docs.confluent.io/cloud/current/api.html#tag/API-Keys-(iamv2)/operation/getIamV2ApiKey).

2. Alternatively, a user could pass a list of API Keys' secrets in env vars / importer resources, but at this point it's very similar to importing them one by one.

Let me know whether it makes sense or there's a way we could improve the UX here!
