### ISSUE TITLE
confluent_kafka_topic attributes aren't exported, but doc says they are

### ISSUE THREAD

**Issue by greg-swift-yohana** [confluentinc/terraform-provider-confluent#351]
<img width="700" alt="image" src="https://github.com/confluentinc/terraform-provider-confluent/assets/139165156/09ab1ad7-28a0-47f4-a379-9609ba79b3d9">

As shown in the attached image, this [document](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#attributes-reference) states that the attributes are exported.  But they aren't.

```
Error: Unsupported attribute

  on .terraform/modules/pdp_dev.topics/confluent-kafka-topic/outputs.tf line 6, in output "name":
   6:   value = confluent_kafka_topic.main.name

This object has no argument, nested block, or exported attribute named
"name".

Error: Unsupported attribute

  on .terraform/modules/pdp_dev.topics/confluent-kafka-topic/outputs.tf line 10, in output "partition_count":
  10:   value = confluent_kafka_topic.main.partition_count

This object has no argument, nested block, or exported attribute named
"partition_count". Did you mean "partitions_count"?
```

Although, it does appear that `confluent_kafka_topic.config` is exported 🤷 

I don't know that I care if they do get exported, but would be good to have documentation match the behavior.

**Comment by linouk23** [comment]
@greg-swift-yohana thanks for the creating the issue!

Do you want to try `topic_name` instead of `name` to match [the docs](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic)?

**Comment by greg-swift-yohana** [comment]
and `partitions_count` instead of `partition_count` 🤦 

thanks :D
