### ISSUE TITLE
GCS connector resource

### ISSUE THREAD

**Issue by marcinkubica** [confluentinc/terraform-provider-confluent#354]
Hello

Not sure if I'm reading it wrong but there seem to be no GCS connector resource?
https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/connectors

Or perhaps there's another way to achieve it?

Thanks!
Marcin

**Comment by linouk23** [comment]
👋 @marcinkubica,

It seems like Confluent Cloud supports both fully managed connectors:

* [Google Cloud Storage Source connector for Confluent Cloud](https://docs.confluent.io/cloud/current/connectors/cc-gcs-source.html)
* [Google Cloud Storage Sink Connector for Confluent Cloud](https://docs.confluent.io/cloud/current/connectors/cc-gcs-sink.html)

The referenced folder contains a few selected connectors that we created examples for, but `confluent_connector` resource supports any fully managed connector on Confluent Cloud. In other words, you can use TF Provider for Confluent and its `confluent_connector` resource (use `connector.class` [attribute](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_connector) for specifying its class) to create both 


* [Google Cloud Storage Source connector for Confluent Cloud](https://docs.confluent.io/cloud/current/connectors/cc-gcs-source.html)
* [Google Cloud Storage Sink Connector for Confluent Cloud](https://docs.confluent.io/cloud/current/connectors/cc-gcs-sink.html).

See more details at https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_connector and let us know whether it helps!

**Comment by marcinkubica** [comment]
@linouk23 thanks!
