### ISSUE TITLE
GCP VPC Peering : mistake in the docs

### ISSUE THREAD

**Issue by mallie-su** [confluentinc/terraform-provider-confluent#36]
Hi there!

Little mistake in the [docs for the resource confluent_peering for GCP](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_peering#custom_routes).
The argument `custom_routes` should be `import_custom_routes` as expected [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/resource_peering.go#L40).

Thanks!

**Comment by linouk23** [comment]
Thanks for reporting it @mallie-su!

**Comment by linouk23** [comment]
@mallie-su we're happy to let you know we've just released `0.9.0` [version](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#090-may-25-2022) of TF Provider that fixes this issue in our docs.
