### ISSUE TITLE
Deprecated `schema_registry_region` without an alternative.

### ISSUE THREAD

**Issue by lra** [confluentinc/terraform-provider-confluent#373]
Hi,

Everytime we plan or apply we get those warnings:

```
╷
│ Warning: Deprecated Resource
│ 
│   with data.confluent_schema_registry_region.this,
│   on schema-registry.tf line 1, in data "confluent_schema_registry_region" "this":
│    1: data "confluent_schema_registry_region" "this" {
│ 
│ The "schema_registry_region" data source has been deprecated and will be removed in the next major version of the provider (2.0.0). Refer to the Upgrade Guide at
│ https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/version-2-upgrade for more details. The guide will be published once version 2.0.0 is released.
│ 
│ (and 6 more similar warnings elsewhere)
```

I get that `confluent_schema_registry_region` is deprecated, but with other providers, when we get those messages, we can use an alternative resource that's not deprecated so that the upgrade is smooth once the upgraded provider is released.

I can't find  what resource we need to use to replace the depredcated one.

**Comment by linouk23** [comment]
Thank you, @lra, for creating this issue. That's an excellent call-out!

We'll make sure to release the referenced https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/version-2-upgrade soon to make sure

>  the upgrade is smooth once the upgraded provider is released.

👍

**Comment by linouk23** [comment]
@lra FYI we added https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/version-2-upgrade that describes how to resolve warning messages. We'll update examples in future releases, thanks!

**Comment by AnitaErnszt** [comment]
I don't think the issue was that there's a warning, but rather the fact that moving forward there's no clear way to create schema registries via Terraform. Does it mean we have to create schema registries manually?!

This seems like a large step backwards when an organisation maintains their whole infrastructure via code IMO.

**Comment by AnitaErnszt** [comment]
@linouk23 Please kindly reopen the issue due to above

**Comment by linouk23** [comment]
@AnitaErnszt thanks for the question! 

> Does it mean we have to create schema registries manually?!

It doesn't. SR clusters will be created automatically once a user provisions their first Kafka cluster and we'll be updating our examples soon, thanks for waiting!
