### ISSUE TITLE
Confluent_Cluster_Linking conflicting with plan and apply asking for bootstrap_endpoint and rest_endpoint

### ISSUE THREAD

**Issue by Mohapatraabhishek-lab** [confluentinc/terraform-provider-confluent#376]
Below is my TF configuration for setting up a cluster linking resource 

resource "confluent_cluster_link" "dev_basic_to_dedicated" {
  link_name = "basic_to_dedicated"

  source_kafka_cluster {
    id                  = module.confluent_cloud.cluster.id
    bootstrap_endpoint  = module.confluent_cloud.cluster.bootstrap_endpoint
    credentials {
      key    = module.confluent_cloud.api_key.id
      secret = module.confluent_cloud.api_key.secret
    }
  }

  destination_kafka_cluster {
    id                 = module.confluent_cloud.cluster_dedicated[0].id
    bootstrap_endpoint = module.confluent_cloud.cluster_dedicated[0].bootstrap_endpoint
    credentials {
      key    = module.confluent_cloud.api_key_dedicated[0].id
      secret = module.confluent_cloud.api_key_dedicated[0].secret
    }
  }

  config = {
    "acl.sync.enable"                   = "true"
    "auto.create.mirror.topics.enable"  = "true"
    "consumer.offset.sync.enable"       = "true"
  }

  lifecycle {
    prevent_destroy = false
  }

  depends_on = [
    module.confluent_cloud
  ]
}

While doing a terraform apply it gives me the below error (screenshot attached)
![image](https://github.com/confluentinc/terraform-provider-confluent/assets/85798041/c1c24e61-e361-4700-957b-129ed4b44ee8)

After adding the rest_endpoint parameter it is saying that either boostrap_endpoint or the rest_endpoint is needed but not both.

![image](https://github.com/confluentinc/terraform-provider-confluent/assets/85798041/3e4b8052-2f24-44cc-b423-0523fecfd61d)

![image](https://github.com/confluentinc/terraform-provider-confluent/assets/85798041/89babe79-75cf-4c2e-b819-0ea77145d02e)

It is contradicting with the two consecutive terraform apply.
Please assist.

**Comment by linouk23** [comment]
Thanks for creating the issue @Mohapatraabhishek-lab!

Did you get a chance to look at the following end-to-end examples might help to get started with `confluent_cluster_link` resource:

* [destination-initiated-cluster-link-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/destination-initiated-cluster-link-rbac): An example of setting up a destination initiated cluster link with a mirror topic
* [source-initiated-cluster-link-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/source-initiated-cluster-link-rbac): An example of setting up a source initiated cluster link with a mirror topic
* [regular-bidirectional-cluster-link-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/regular-bidirectional-cluster-link-rbac): An example of setting up a bidirectional cluster link with 2 mirror topics
* [advanced-bidirectional-cluster-link-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/regular-bidirectional-cluster-link-rbac): An example of setting up a bidirectional cluster link with 2 mirror topics ([advanced option](https://docs.confluent.io/cloud/current/multi-cloud/cluster-linking/cluster-links-cc.html#create-a-cluster-link-in-bidirectional-mode))

You should be able to find the most relevant configuration there and copy it.

Let us know if that helps!
