### ISSUE TITLE
Kafka Connect Provisioning  - Can we hide sensitive variables in code?

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluent#38]
While provisioning connectors using terraform, how do we ensure the "sensitive" values are not checked in and are not visible to people viewing the code? Is there a way to inject the values through environment variables?

Referring to the sink documents in your example - I don't see an alternative to hide the secrets while provisioning connectors
```
resource "confluent_connector" "sink" {
    .......................
    config_sensitive = {
        "aws.access.key.id"     = "***REDACTED***"
        "aws.secret.access.key" = "***REDACTED***"
    }
 
   config_nonsensitive = {
         ......................
         "s3.bucket.name"       = "***REDACTED***"
          .....................
   }
   .....................
}
```

**Comment by linouk23** [comment]
The recommended workflow is to specify `config_sensitive` block, run `terraform apply` and then remove them from TF config (they're not being stored in TF state) by setting `config_sensitive = {}` as specified in the [docs](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_connector).

The idea is we wanted to avoid https://github.com/aiven/terraform-provider-aiven/issues/701, let me know if you think there's a better approach to implement it, thanks!

**Comment by bluedog13** [comment]
My concern is not the state file but the source control/code base that will have the sensitive information in the file history. 

Even though the information is not in the state file, anyone who has access to the code base will be able to view the sensitive information. This makes the code base impossible to share with teams to add their respective connector blocks in the solution.

Something like reading from an environment may help in this scenario.

**Comment by linouk23** [comment]
When I think about it, you could try introducing new variables and assign values to them using env vars: https://www.terraform.io/cli/config/environment-variables#tf_var_name

E.g., 
```
# main.tf
resource "confluent_connector" "sink" {
    .......................
    config_sensitive = {
        "aws.access.key.id"     = "***REDACTED***"
        "aws.secret.access.key" = "***REDACTED***"
    }
 
   config_nonsensitive = {
         ......................
         "s3.bucket.name"       = var.s3_bucket_name
          .....................
   }
   .....................
}

# variables.tf
variable "s3_bucket_name" {
  type        = string
  sensitive   = true
}

# run export
export TF_VAR_s3_bucket_name="***REDACTED***
```

**Comment by bluedog13** [comment]
Thank you.  This is what I was looking for.  I am will try this shortly and let you know.

**Comment by bluedog13** [comment]
This worked.  Thanks again.

**Comment by linouk23** [comment]
Cool, I think that's a pretty popular use case so we'll update our docs too.
