### ISSUE TITLE
Addition of a confluent_network data source.

### ISSUE THREAD

**Issue by AKrill91** [confluentinc/terraform-provider-confluent#39]
An additional feature I think would make sense is a confluent_network data source to look up pre-existing networks by name and/or id. We've got some pre-existing networks set up for private link and would love to stop hardcoding the private_link_endpoint_service by using a data source.

**Comment by linouk23** [comment]
@AKrill91 @mattm-zip we're happy to let you know we've just released [`0.9.0` version]((https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#090-may-25-2022)) of TF Provider that includes `confluent_network` [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_network).
