### ISSUE TITLE
Allow adding attributes in tags

### ISSUE THREAD

**Issue by mkazla** [confluentinc/terraform-provider-confluent#393]
Hi, 

I want to add the additional attributes to the tags by using this api [endpoint](https://docs.confluent.io/cloud/current/stream-governance/stream-catalog-rest-apis.html#update-a-tag-by-adding-attributes-key-value-pairs). But terraform does not allows to add additional attributes to the tags. 

Kindly help.

**Comment by mkazla** [comment]
Hey @zhenli00, Thanks for replying. Business metadata might not work in my case as the plan that our team is using does not support business metadata.

<img width="331" alt="image" src="https://github.com/confluentinc/terraform-provider-confluent/assets/99746350/4751ac50-af92-4b45-92c2-5b2eaa8005aa">

**Comment by ConfluentSpencer** [comment]
@mkazla we can't change the features available here unless the Data Governance team enables that with an API change. CC @rayokota.
I will close and will revisit when/if they make a change.
