### ISSUE TITLE
Add byok_key to an old cluster instead of encryption_key

### ISSUE THREAD

**Issue by petrkarytka** [confluentinc/terraform-provider-confluent#398]
We used an old version (<1.36.0) of the provider when deployed a couple of Confluent clusters initially. 

There was the argument ["encryption_key"](https://registry.terraform.io/providers/confluentinc/confluent/1.35.0/docs/resources/confluent_kafka_cluster#encryption_key) up to the version 1.36.0 under the configuration block "dedicated". Later, in 1.36.0 [a separate BYOK resource](https://registry.terraform.io/providers/confluentinc/confluent/1.36.0/docs/resources/confluent_byok_key) was introduced.

Is it possible to perform in-place update for the existing clusters by removing "encryption_key" from the code and adding the block "byok_key" that refers to a "confluent_byok_key" resource? We cannot reproduce it with a new temporary cluster to test before moving forward, the old argument is no longer available for new clusters according to the documentation:

> Warning:
> At the moment, using encryption_key for creating Kafka clusters is not available. See [this comment](https://github.com/confluentinc/terraform-provider-confluent/issues/65#issuecomment-1179194889) for more details.

I would appreciate any recommendations.

**Comment by linouk23** [comment]
@petrkarytka thanks for creating this issue!

Unfortunately, in-place updates are not supported in TF because they are not supported at the API level.

**Comment by linouk23** [comment]
@petrkarytka see https://github.com/confluentinc/terraform-provider-confluent/issues/400#issuecomment-2203934955 for additional context, namely,
> 1. Remove `encryption_key` attribute from `confluent_kafka_cluster` resource (you won't have to recreate a cluster but `confluent_kafka_cluster` resource definition might look a bit misleading as there'll be no references to encryption_key / byok_key.

**Comment by linouk23** [comment]
@petrkarytka there's an update from our side: we talked to the backend team, and we're considering reverting our deprecation change. More specifically:

> When creating **new** Kafka clusters, you should use the `byok_key[0].id` attribute instead of the `dedicated[0].encryption_key` attribute, since the latter is no longer supported in the [Confluent Cloud API](https://docs.confluent.io/cloud/current/api.html#tag/Clusters-(cmkv2))'s `POST cmk/v2/clusters` request.

> **However, for existing instances of the `confluent_kafka_cluster` resource, `dedicated[0].encryption_key` is still supported as a read-only attribute.**

In short, your existing instances of the `confluent_kafka_cluster` resource will not require any updates when using the `v2.0.0` version of the TF Provider, and you'll no longer see deprecation messages. Let us know if that helps!

**Comment by petrkarytka** [comment]
> In short, your existing instances of the `confluent_kafka_cluster` resource will not require any updates when using the `v2.0.0` version of the TF Provider, and you'll no longer see deprecation messages. Let us know if that helps!

@linouk23 thank you for the update, that's definitely better, although it doesn't resolve our issue completely because we are using Terraform modules and will have to support two versions of the module for Kafka cluster (one with encryption_key, one with byok_key). Unfortunately some clusters with the 'encryption_key' are already in production and cannot be redeployed.
