### ISSUE TITLE
How to select schema registry region on 2.0.0?

### ISSUE THREAD

**Issue by Israphel** [confluentinc/terraform-provider-confluent#399]
I was reading this guide: https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/version-2-upgrade

and with the **confluent_schema_registry_cluster** going away, I'm not sure how to create new environments with an specific config of schema registry cluster config (package, region).

This is part of my module:

```hcl
# Schema registry region
data "confluent_schema_registry_region" "schema_registry_region" {
  cloud   = var.schema_registry.cloud
  region  = var.schema_registry.region
  package = var.schema_registry.package
}

# Schema registry cluster
resource "confluent_schema_registry_cluster" "schema_registry_cluster" {
  package = data.confluent_schema_registry_region.schema_registry_region.package

  environment {
    id = confluent_environment.environment.id
  }

  region {
    id = data.confluent_schema_registry_region.schema_registry_region.id
  }
}
```

Without the resource, how can I tell confluent in which region to create the schema registry?

Having only the data means that we can't decide wether to create the schema registry cluster or not? and where?

**Comment by linouk23** [comment]
@Israphel thanks for creating the issue!

The [short answer](https://support.confluent.io/hc/en-us/articles/23668198983444-Stream-Governance-Essentials-is-being-enabled-in-Confluent-Cloud) is

> The Stream Governance cluster will be enabled in the same region as your first Kafka cluster within the environment.

We'll be releasing a new version of TF Provider with an updated code for `confluent_kafka_cluster` resource soon and we'll update docs & examples accordingly and we expect it to look as follows:
```
resource "confluent_environment" "prod" {
  display_name = "Production"

  stream_governance {
    package = "ESSENTIALS"
  }
}

resource "confluent_kafka_cluster" "prod" {
  ...
  region = "us-west-2"
}

data "confluent_schema_registry_cluster" "essentials" {
  environment {
    id = confluent_environment.prod.id
  }
  # region is going to be "us-west-2" as well
}
```

**Comment by Israphel** [comment]
but if I don't want that? my kafka clusters are us-east-1 and us-west-2, but my schema registry cluster is us-east-2

**Comment by ConfluentSpencer** [comment]
@Israphel , this is part of our Data Governance team moving customers away from managing Schema Registry Clusters in general. @akhileshm1 or @GunalKupta can comment more on details.

**Comment by Israphel** [comment]
we had to start with the schema registry in us-east-2 because us-east-1 had extra cost. What's the deal now? any region without extra cost?

**Comment by akhileshm1** [comment]
Schema Registry (SR) cluster will always be provisioned in the same region as the first Kafka cluster in the environment. given this, you can choose to deploy the Kafka cluster in the region that you prefer your SR cluster to be in. you can always choose to delete your Kafka cluster if you don't need it in that region. this will not delete your SR cluster. 
in the event you already created the first Kafka cluster in a region you don't want your SR to be in and you don't want to re-create your environment, please reach out to Confluent support and we'll delete and re-provision the SR cluster in the region of your choosing. 
hope that helps.

**Comment by Israphel** [comment]
but about my previous question: In the Essentials package, only some regions had the SR withouyt extra cost. That remains? or now any region is without extra cost?

**Comment by akhileshm1** [comment]
both Essentials and Advanced packages are available in all Confluent Cloud regions.

**Comment by Israphel** [comment]
what I'm talking about is:

before this change, you created an environment and then a schema registry cluster. You used to get a list of regions to chose from and only some of them were without additional cost (like us-east-2), but us-east-1 had extra cost. Did that change? How do I know where to create the schema registry cluster without getting charged extra?

the only reason we have clusters in us-east-1 and us-west-2 but the schema registry cluster in us-east-2 is because of that very reason.

**Comment by akhileshm1** [comment]
if you select Essentials package in your environment resource, your SR cluster will always be free (for first 100 schemas) regardless of the region. so, yes, Essentials package in us-east-1 is free. 
https://docs.confluent.io/cloud/current/stream-governance/packages.html#governance-package-types
https://docs.confluent.io/cloud/current/stream-governance/packages.html#cloud-providers-and-region-support

**Comment by Israphel** [comment]
I know you won't change your mind, but this path you're taking is super anti-IaC.

you're leaving the responsibility of one resource creation (schema registry) based on another irrelevant resource (kafka cluster).

Now the typical creation order of (environment+schema registry) -> clusters no longer works, because the data resource won't return anything until you create a cluster, forcing us to add dummy booleans to let the environment TF module know that now the schema registry was created (by another entity) and that it can finally read the data.

**Comment by AlexisDaciuk** [comment]
I will side with @Israphel with this one

We are writing terraform modules to use with Terragrunt

Makes no sense that I need to create a Cluster to get the SR data when it's an Environment resource and makes the relation between our modules weird at best, I would expect to get the endpoint and ID of the SR of the Environment after I create the Environment 

Would be great if the Confluent team can reconsider this and make a better decision for a better IaC approach to this issue

**Comment by akhileshm1** [comment]
feedback received. I agree it's not ideal. The challenge here is that in order to provision the SR cluster after environment creation, we need to know the region. We have no way of knowing that today until you create the first Kafka cluster, at which point we assume that the region of the first Kafka cluster is where you want your SR cluster to be in. 
We'll take this feedback to see if we better support IaC use cases.

**Comment by Israphel** [comment]
> feedback received. I agree it's not ideal. The challenge here is that in order to provision the SR cluster after environment creation, we need to know the region. We have no way of knowing that today until you create the first Kafka cluster, at which point we assume that the region of the first Kafka cluster is where you want your SR cluster to be in. We'll take this feedback to see if we better support IaC use cases.

just allow us passing "region" or "schema_registry_cluster_region" when creating an environment, instead of assuming based on an unrelated resource.
