### ISSUE TITLE
Add new computed attributes for PL network

### ISSUE THREAD

**Issue by linouk23** [confluentinc/terraform-provider-confluent#40]
### What

> The Terraform module which creates the Network with PL doesn’t expose few necessary details (DNS Domain and Sub Domain) in output data, which means I can’t configure the VPC linking without manually coping the details.

**Comment by linouk23** [comment]
We're happy to let you know we've just released `0.9.0` [version](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#090-may-25-2022) of TF Provider that includes `dns_domain` and `zonal_subdomains` computed attributes for `confluent_network` resource.

**Comment by ahmedelnaggartmr** [comment]
Can this be outputted from data source as well?
