### ISSUE TITLE
Error: error creating Connector: error creating Connector: error sending validation request: 404 Not Found

### ISSUE THREAD

**Issue by npfp** [confluentinc/terraform-provider-confluent#402]
Hello team,

When trying to create a s3 sink connector with the terraform plugin based on the `s3-sink-connector` example , I got the following error

```
Error: error creating Connector: error creating Connector: error sending validation request: 404 Not Found
```

Unfortunately, the error is not very informative and I can't understand either the error comes from some wrong settings/authorisations linked to Confluent or linked to AWS.

Would you mind going me some pointers on how I could fix this error?

Thx!

**Comment by linouk23** [comment]
@npfp thanks for waiting!

Could you confirm if you ran into this issue with this [resource definition](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/connectors/s3-sink-connector/main.tf#L382-L424)?

**Comment by npfp** [comment]
Hi @linouk23 

Many thx to get back to me. Indeed, I used this resource definition and finally got the reason: 

```
environment {
    id = confluent_environment.staging.id
  }
  ```
wasn't correctly set (I was using a wrong terraform variable) so the error. It took me some time to get to it as I was more looking on the aws credentials part.
