### ISSUE TITLE
Typo in Upgrade to Terraform 2.0.0 Guide

### ISSUE THREAD

**Issue by lcua-cup** [confluentinc/terraform-provider-confluent#412]
Hello, I am a bit confused with some of the written guidelines. There are 2 things that I have noticed:

1. While reading this portion: [Changes to confluent_schema_registry_region data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/version-2-upgrade#changes-to-confluent_schema_registry_region-data-source), It says:
![image](https://github.com/user-attachments/assets/ee92e850-885d-4327-b16f-d9ef631aa401)

Should it be `confluent_schema_registry_region` and not `confluent_schema_registry_cluster`? Sorry, I am confused.

2. In [data.confluent_schema_registry_cluster Resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema_registry_cluster), It says the data.confluent_schema_registry_cluster will be deprecated, or will it be the `confluent_schema_registry_cluster` resource?
![image](https://github.com/user-attachments/assets/f416a794-aae6-4832-85c5-4aa4edb2f178)

**Comment by linouk23** [comment]
Thanks for creating this issue @lcua-cup!

It does look like a typo to me and we'll make sure to update the guide in our next release 👍

**Comment by linouk23** [comment]
In short, it should have been

```
### Changes to `confluent_schema_registry_region` data source

Deprecated `confluent_schema_registry_region`
[data source](https://registry.terraform.io/providers/confluentinc/confluent/1.65.0/docs/data-sources/confluent_schema_registry_region) will be removed in version `2.0.0`.


Remove the `confluent_schema_registry_region` [data source](https://registry.terraform.io/providers/confluentinc/confluent/1.65.0/docs/data-sources/confluent_schema_registry_region) only from TF configuration (as data sources are not stored in the TF state) instead
to avoid `Warning: Deprecated Resource` messages.

To remove `confluent_schema_registry_region` [data source](https://registry.terraform.io/providers/confluentinc/confluent/1.65.0/docs/data-sources/confluent_schema_registry_region) from TF configuration, you can just remove its definition:

#### Before
    ```
    data "confluent_schema_registry_region" "essentials" {
      # ...
    }
    ```

#### After
    ```
    # empty
    ```
```

which is exactly as you suggested 👍

**Comment by lcua-cup** [comment]
Fantastic, thank you!

**Comment by linouk23** [comment]
Update: Our docs have been updated. Thanks again for spotting the typos @lcua-cup!
