### ISSUE TITLE
connector hangs in provisioning state

### ISSUE THREAD

**Issue by abintrd** [confluentinc/terraform-provider-confluent#42]
Debezium Postgres Connector created using terraform provider 0.8.1 hangs in provisioning state and never moves to success. This  necessarily isn't a provider issue. But its hard to debug since there is no error in connector log and happens only when using terraform.

**Comment by linouk23** [comment]
Thanks for reporting this issue @abintrd!

Connectors generally take 15 minutes or less to provision, however, it can take longer (24 hrs of more) in cases of heavy load. We've seen this happen in the past when customers deleted and recreated hundreds of connectors in a short span.
