### ISSUE TITLE
Provisioning Kafka connectors takes too much time

### ISSUE THREAD

**Issue by dobeerman** [confluentinc/terraform-provider-confluent#429]
Despite the connector type (custom or confluent), deployment takes ~6m 30s. 
In addition, even if the status is set to `PAUSED`, the connector is provisioned as `RUNNING`.

_custom_
```
confluent_connector.nats_sink: Creation complete after 6m27s [id=clcc-......]
confluent_connector.nats_source: Creation complete after 6m27s [id=clcc-......]
```

_confluent_
```
confluent_connector.dynamodb_sink: Creation complete after 6m12s [id=lcc-......]
confluent_connector.http_sink: Creation complete after 6m12s [id=lcc-......]
```

Actually, connectors get provisioned roughly in 2m 20s.

**Comment by linouk23** [comment]
@dobeerman thanks for creating this issue!

> In addition, even if the status is set to PAUSED, the connector is provisioned as RUNNING.

Currently, we do not support the provisioning of "PAUSED" connectors.

> Actually, connectors get provisioned roughly in 2m 20s.

TF Provider's code does include a manual timeout as a workaround for other issues. See https://github.com/confluentinc/terraform-provider-confluent/issues/43#issuecomment-1293804274 for more details, thank you!
