### ISSUE TITLE
sudden value csfle.configs.visible

### ISSUE THREAD

**Issue by marcinkubica** [confluentinc/terraform-provider-confluent#455]
Hello

For gcs sink we're getting sudden change introduced from Confluent side trying to change `csfle.configs.visible` from null to false
![image](https://github.com/user-attachments/assets/82db70d5-487f-4d56-a01d-b3225918269f)

There's [zero documentation](https://docs.confluent.io/search.html#stq=csfle.configs.visible&stp=1&sites=1&components=8%257C99%257C1%257C10%257C100%257C98%257C3%257C7%257C4%257C6%257C5%257C15%257C16%257C19%257C20%257C21%257C65%257C23%257C79%257C80%257C91%257C17%257C34%257C52%257C66%257C18%257C22%257C24%257C25%257C30%257C26%257C27%257C28%257C29%257C31%257C32%257C36%257C37%257C38%257C39%257C11%257C12%257C13%257C14%257C40%257C42%257C51%257C33%257C43%257C44%257C45%257C46%257C47%257C48%257C49%257C41%257C53%257C54%257C55%257C56%257C71%257C57%257C58%257C59%257C60%257C61%257C62%257C63%257C64%257C67%257C68%257C35%257C69%257C70%257C72%257C73%257C74%257C75%257C76%257C77%257C81%257C83%257C84%257C85%257C86%257C86%257C87%257C88%257C89%257C90%257C92%257C93%257C94%257C94%257C95%257C50%257C96%257C97) about this 

Thanks

**Comment by linouk23** [comment]
@marcinkubica thanks for creating the issue! We reached out to the Connect API owners internally, and they identified it as a backend bug. They've created a Jira ticket (CC-29530) to resolve the issue.

**Comment by linouk23** [comment]
@marcinkubica

Update: I just spoke with the Connect team, and they informed me that the fix has already been released. Could you check whether the issue has been resolved? Thank you!

**Comment by tmalikconfluent** [comment]
@marcinkubica, can you please confirm if the fix is working fine?

**Comment by linouk23** [comment]
@marcinkubica, we are going to resolve this bug, as another user reported that the issue was resolved in the duplicate issue: https://github.com/confluentinc/terraform-provider-confluent/issues/466#issuecomment-2443142676
