### ISSUE TITLE
csfle.configs.visible & provider.integration.visible in S3 Sink Connector

### ISSUE THREAD

**Issue by lcua-cup** [confluentinc/terraform-provider-confluent#466]
Hi,

We are always getting the update below for our S3 Sink Connector:
```
- "csfle.configs.visible"        = "true" -> null
- "provider.integration.visible" = "true" -> null
```
![image](https://github.com/user-attachments/assets/3c2a1356-ec07-442d-bc81-b04ac9e01ebf)

Please advise.

**Comment by linouk23** [comment]
Thanks for creating this issue @lcua-cup!

We reached out to the Connect API owners internally, and they identified it as a backend bug. They've created a Jira ticket (CC-29530, CC-29665) to resolve the issue.

**Comment by linouk23** [comment]
Update: I just spoke with the Connect team, and they informed me that the fix has already been released. Could you check whether the issue has been resolved? Thank you!

**Comment by lcua-cup** [comment]
> Update: I just spoke with the Connect team, and they informed me that the fix has already been released. Could you check whether the issue has been resolved? Thank you!

Hi @linouk23, thanks for the update. We are currently in 2.3 version. I will report here back once we have upgraded to the latest Terraform version, thanks!

**Comment by linouk23** [comment]
@lcua-cup given that it was the backend error, it should start working even for your current version of TF Provider.

**Comment by tmalikconfluent** [comment]
@lcua-cup, can you please confirm if the fix is working fine?

**Comment by lcua-cup** [comment]
Hi, the bug is gone after moving to 2.7.0 Confluent provider version.
