### ISSUE TITLE
409 Error - when deleting and creating service account with same name in the plan

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluent#48]
I've run into a scenario when a service account  is being deleted and created with the same name in the same plan run, I see 409 error. 

Below is what happens when I made updates to a resource instance name
1.  terraform detects it needs to destroy the existing service account associated with that resource instance name change and 
2.  create a new service account with the same name

In the logs below, you can see it has "destroyed" the service account but then immediately fails to create a new service account with the same name
```
module.prod-cloudclusteradmin.confluent_api_key.sa-account-kafka-api-key: Destroying... [id=***-*****]
module.prod-cloudclusteradmin.confluent_service_account.cluster: Creating...
module.prod-cloudclusteradmin.confluent_api_key.sa-account-kafka-api-key: Destruction complete after 1s
module.prod-cloudclusteradmin.confluent_role_binding.sa-account-kafka-cluster-admin: Destroying... [id=***-*****]
module.prod-cloudclusteradmin.confluent_role_binding.sa-account-kafka-cluster-admin: Destruction complete after 1s
module.prod-cloudclusteradmin.confluent_service_account.sa-account: Destroying... [id=***-*****]
module.prod-cloudclusteradmin.confluent_service_account.sa-account: Destruction complete after 0s
╷
│ Error: error creating Service Account "prod-***-*****-cloudclusteradmin-sa": 409 Conflict: Service name is already in use.
│
│   with module.prod-cloudclusteradmin.confluent_service_account.cluster,
│   on ../../../../modules/sa-rbac/sa-rbac.tf line 19, in resource "confluent_service_account" "cluster":
│   19: resource "confluent_service_account" "cluster" {
```

I think what may help is - to add some kind of a wait for "x" seconds between the steps , just in the case of creation of key like other scenarios. 

Because of the above, I am not able to apply the changes successfully the next time and when I try to run the same plan/apply command I get 401 error (which I think is an incorrect error indicator).  Also the state file is not in a steady state at this point. 

```
Error: 401 Unauthorized: Authentication failed
```

Thanks.

**Comment by linouk23** [comment]
Thanks for reporting an issue @bluedog13!

That's interesting, could you share the use case for such a scenario? Looks like you delete **and** create a service account with the same name 🤔

**Comment by bluedog13** [comment]
I updated the name of the resource in the module being used to provision the service account.

**Comment by bluedog13** [comment]
I also don't understand the 401 error - it's the same cloud credentials being used. 

I am seeing the same behavior for the topic deletion and creation with the same name as well.

**Comment by linouk23** [comment]
Well I'd say that's not a typical use case, command `terraform state mv` might be a [better option](https://www.terraform.io/cli/commands/state/mv#example-rename-a-resource).

**Comment by bluedog13** [comment]
The underlying state file will change no matter what - when the resource name in the terraform code gets changed.  

So this behaviour of updating a name of a resource in a code - does not work, which implies bad names for resources cannot be changed once committed.

**Comment by linouk23** [comment]
Here's how I think it might work:
1. 
![image](https://user-images.githubusercontent.com/5459870/172264695-30283d33-03c6-4140-a155-b6b61846c515.png)
2. `terraform state mv packet_device.worker packet_device.helper`
3. Run `terraform plan` which will show 0 changes.

That said, I agree it's an issue and we'll address it in our next release.

**Comment by bluedog13** [comment]
Thank you and also for looking into the fix. 

We have 100's of resources that use modules to provision resources.  So even though the above helps when resources are limited, for a bigger scale it is a problem.  We want to get out of the manual process as much as possible to make tweaks.

**Comment by linouk23** [comment]
Actually when I think about it and look at your provided logs (thanks for attaching them!) you can see that the creation process started before `DELETE` request was even called:
```
module.prod-cloudclusteradmin.confluent_service_account.cluster: Creating...
...
module.prod-cloudclusteradmin.confluent_service_account.sa-account: Destroying... [id=***-*****]
module.prod-cloudclusteradmin.confluent_service_account.sa-account: Destruction complete after 0s
```

which is why I think even adding timeout won't help. You could experiment with `terraform apply -parallelism=1` but it still depends on the initial call order I think.

**Comment by bluedog13** [comment]
Thank you. 

I am using  ```terraform apply -parallelism=1``` in my example.  Is there a way, the call order can be controlled?  Because, I see this being a problem whenever we try to clean up code or make updates as above.

**Comment by linouk23** [comment]
> Is there a way, the call order can be controlled?

Not that I'm aware of.

> Because, I see this being a problem whenever we try to clean up code or make updates as above.

One workaround I can see is to create a duplicate for each resource with you target instant name and a fake `display_name` and then remove all the existing resources and update `display_name` for your duplicates.

Again, I think that's more like a TF limitation that is not specific to the provider.

**Comment by linouk23** [comment]
Closing the PR since it's more like a general TF limitation that is not specific to the provider.
