### ISSUE TITLE
Missing arguments to add networking endpoints for "Confluent Kafka Replicator" custom connector

### ISSUE THREAD

**Issue by jinjuewei** [confluentinc/terraform-provider-confluent#494]
I could add and configure the confluent kafka replicator custom connector manully (https://www.confluent.io/hub/confluentinc/kafka-connect-replicator?_ga=2.168227108.461229490.1731923735-1325076423.1727250622&_gac=1.19373514.1731926129.Cj0KCQiA6Ou5BhCrARIsAPoTxrDuTAPqKIm6sKgV33s84T9m1AILOTkoCf_A6fDvPkWic3Oe_vf30ckaAi98EALw_wcB&_gl=1*mpufiw*_gcl_aw*R0NMLjE3MzE5MjYxMjkuQ2owS0NRaUE2T3U1QmhDckFSSXNBUG9UeHJEdVRBUHFLSW02c0tnVjMzczg0VDltMUFJTE9Ua29DZl9BNmZEdlBrV2ljM09lX3ZmMzBja2FBaTk4RUFMd193Y0I.*_gcl_au*ODYzMTIzODA3LjE3MjcyNTA2MjEuMTY3MDMyODg3NC4xNzI4OTExMDUwLjE3Mjg5MTEwNTA.*_ga*MTMyNTA3NjQyMy4xNzI3MjUwNjIy*_ga_D2D3EGKSGD*MTczMjA4ODIzOS45NC4xLjE3MzIwOTEwOTguMTUuMC4w). Now I want to use terraform to create a confluent replicator connector.
To configure this connector I need to add several networking endpoints (see in the following screenshot).
![image](https://github.com/user-attachments/assets/d4881828-7174-4f8a-977c-669901aff643)

Unfortunatelly I could not find where to set the network endpoints arguments in Terraform. Do I need to set the network endpoints manully after the connecor is created by terraform?
https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_connector

**Comment by linouk23** [comment]
@jinjuewei thanks for creating this issue!

Could you share your current TF configuration of `confluent_connector` resource?

**Comment by jinjuewei** [comment]
hi  @linouk23 ,

I fould the solution for this issue. I could use the following argument (description can be found in [https://docs.confluent.io/cloud/current/api.html#tag/Connectors-(connectv1)/operation/createConnectv1Connector]):
`confluent.custom.connection.endpoints   string
[Optional for Custom Connector] Egress endpoint(s) for the connector to use when attaching to the sink or source data system.`

- I can use wildcard, but limited. 

> - with *.xxx.xxx.xxx:9092 I got error message: Connector config "confluent.custom.connection.endpoints" does not support use of only wildcard for a domain.

- > with b*.kafka-factory.powerco.tech:9092, it works

- I can add list of endpoints, with semicolon as seperator, but not with comma.

- > `"confluent.custom.connection.endpoints"` = "lb.xxx.xxx.xxx:9092:TCP;b0.xxx.xxx.xxx:9092:TCP;b1.xxx.xxx.xxx:9092:TCP;b2.kafka-factory.powerco.tech:9092:TCP"` it works

- > `"confluent.custom.connection.endpoints" = "lb.xxx.xxx.xxx:9092:TCP,b0.xxx.xxx.xxx:9092:TCP,b1.xxx.xxx.xxx:9092:TCP,b2.kafka-factory.powerco.tech:9092:TCP" ` it doesn't work. I got error message: `Connector config "confluent.custom.connection.endpoints" have an invalid format. Expected format <HOSTNAME_PATTERN>:<PORTS_LIST>[:<PROTOCOL>]`

**Comment by linouk23** [comment]
That's great to hear @jinjuewei! Is your current solution sufficient to resolve this issue?

The approach I recommend for similar issues is to open the CC UI, set up your target configuration there, and then use your browser's Dev Tools to examine the network requests. Review the exact response from the Connect API (or any other API) and copy them into the corresponding TF definitions (i.e., `confluent_connector`).

**Comment by jinjuewei** [comment]
hi @linouk23 ,

yes, the current solution is sufficient. The problem is solved.
