### ISSUE TITLE
How to import a topic from a set/list using the import block?

### ISSUE THREAD

**Issue by castillao** [confluentinc/terraform-provider-confluent#497]
Hello!

i want to import a manually created topic that is part of a set to my terraform state using the terraform import block

i have my resource definition with the specification for credentials, rest endpoint, partitions, and so

```
resource "confluent_kafka_topic" "source-topics" {
  for_each = toset(var.source_topics_names)

  kafka_cluster {
    id = confluent_kafka_cluster.cluster.id
  }
  topic_name       = each.key
  rest_endpoint    = confluent_kafka_cluster.cluster.rest_endpoint
  partitions_count = var.partitions_count

  credentials {
    key     = xxxx
    secret = xxxx
  }
}
```

and creating my topics from scratch using this specification works correctly

following the id structure i tried to use the terraform [import block](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#import)
as this is a topic from a set i tried using the name specification on the resource

```
import {
  to = confluent_kafka_topic.source-topics["topic-name-here"]
  id = "cluster-id/topic-name-here"
}
```

but trying this will give me an error as if the rest endpoint variable is not set:
`Error: error importing Kafka Topic: one of provider.kafka_rest_endpoint (defaults to KAFKA_REST_ENDPOINT environment variable) or IMPORT_KAFKA_REST_ENDPOINT environment variable must be set`

is the only supported way to use the terraform [import command?](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#import)
(and setting the respective ENV VARS)

or is there a way to use the import block for topics in this scenario?

thanks a lot.

**Comment by sajjadlateef** [comment]
We do not support import_block at this time. We suggest using 'terraform import' as an alternative.

**Comment by castillao** [comment]
alright, thanks for the quick answer!

**Comment by linouk23** [comment]
Update: we just ran the tests and we can confirm that both options ([1](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#option-1-manage-multiple-kafka-clusters-in-the-same-terraform-workspace) and [2](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic)) support import blocks as well. That said, a user has to specify these env vars:
```
$ export IMPORT_KAFKA_API_KEY="<kafka_api_key>"
$ export IMPORT_KAFKA_API_SECRET="<kafka_api_secret>"
$ export IMPORT_KAFKA_REST_ENDPOINT="<kafka_rest_endpoint>"
```
when using [Option #1](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#option-1-manage-multiple-kafka-clusters-in-the-same-terraform-workspace).

**Comment by linouk23** [comment]
Your error message
> IMPORT_KAFKA_REST_ENDPOINT environment variable must be set

implies that you're using [Option #1](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#option-1-manage-multiple-kafka-clusters-in-the-same-terraform-workspace) but didn't set these env vars:
```
$ export IMPORT_KAFKA_API_KEY="<kafka_api_key>"
$ export IMPORT_KAFKA_API_SECRET="<kafka_api_secret>"
$ export IMPORT_KAFKA_REST_ENDPOINT="<kafka_rest_endpoint>"
```
