### ISSUE TITLE
Add confluent_stream_governance_cluster resource

### ISSUE THREAD

**Issue by VipulZopSmart** [confluentinc/terraform-provider-confluent#5]
Hi @linouk23, hope you're doing well!

Could you please kindly let me know how can we manage schema registry in the confluent cloud using terraform. I dont think right now this provider supports that? What are you thoughts about this? Or is there any other way to do that.

**Comment by maheshbhole** [comment]
eagerly waiting for this to release.

**Comment by linouk23** [comment]
That's very exciting to hear! It won't be shipped in Q2 but Q3 is a possibility 🤞

**Comment by linouk23** [comment]
Schema Registry resource is in development still, can't share the timelines yet 😕

**Comment by leewoobin789** [comment]
@linouk23 thank you for sharing the status :) keep doing it would help us a lot as well.

**Comment by lfventura** [comment]
Hello, any update on the development ? :)

**Comment by linouk23** [comment]
@lfventura it's the same as before

> Schema Registry resource is in development still, can't share the timelines 😕

**Comment by tfindlay-au** [comment]
@linouk23 Just politely asking if there is any progress on this issue ?

Specifically pointing out in #114  - I feel like its a significant issue as the product changed without notice and now impacts customers, there is no choice for customers to roll back to the earlier version of Confluent Cloud. So I expect fixing this should be a priority for Confluent.

Happy to ask everyone to raise it as a defect in the support portal to get it escalated if that would help.

**Comment by linouk23** [comment]
@tfindlay-au thanks for asking! It is coming soon, watch out for changes in `CHANGELOG.md` 👌

**Comment by linouk23** [comment]
👋 on a somewhat related note, we kicked off some discussions about resource definitions for `schema` / `subject` resources in https://github.com/confluentinc/terraform-provider-confluent/issues/124#issuecomment-1291206863. All contributions are welcome!

**Comment by linouk23** [comment]
👋 
update: we [released](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1100-october-26-2022) a new `1.10.0` version of TF Provider where we dded new `confluent_stream_governance_cluster` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_stream_governance_cluster) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_stream_governance_cluster) in an [Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy).

cc @tfindlay-au @patakmi @lfventura @leewoobin789 @felleg @AndreasKlein @AlexVasiukov @arkiaconsulting @thibaudfr @mallie-su @schlbra @tbublik @Marcus-James-Adams  @de1et3d @wurthmvnn @manishjain2-tomtom @filippo-qmee @majidazimi, @mattyev87 @mallie-su @thibaudfr @krishnan-mani @schlbra @tbublik @alemairebe.
