### ISSUE TITLE
[Feature] confluent_kafka_cluster for dedicate type

### ISSUE THREAD

**Issue by JayChanggithub** [confluentinc/terraform-provider-confluent#50]
Hi Support

I saw the docs for diedicate cluster that none support create in Azure cloud so far. Did you have plan to support in future? Thank you

**Comment by linouk23** [comment]
@JayChanggithub thanks for opening an issue!

We're sorry for the confusion, we do support creation of dedicated clusters on Azure.

Please find some example configurations:
* [dedicated-privatelink-azure-kafka-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-privatelink-azure-kafka-acls)
* [dedicated-privatelink-azure-kafka-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-privatelink-azure-kafka-rbac)
* [dedicated-public-kafka-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-public-kafka-acls) (might need to edit the config to switch from AWS to Azure)
* [dedicated-public-kafka-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-public-kafka-rbac) (might need to edit the config to switch from AWS to Azure)
* [dedicated-vnet-peering-azure-kafka-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-vnet-peering-azure-kafka-acls)
* [dedicated-vnet-peering-azure-kafka-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-vnet-peering-azure-kafka-rbac)

Let me know if that helps!

**Comment by JayChanggithub** [comment]
@linouk23 Thanks for your replying and detail. And these helpful to us.

**Comment by linouk23** [comment]
That's great to hear, we'll update our documentation in our next release to make it less confusing!
