### ISSUE TITLE
Creation of Schema registry Cluster not possible with 2.12.0?

### ISSUE THREAD

**Issue by conting** [confluentinc/terraform-provider-confluent#502]
Hello Everyone, 

I am trying to update my provider from 1.83.0 to 2.12.0. Everything worked but the the update of the resource "confluent_schema_registry_cluster". This was the code before:
```
resource "confluent_schema_registry_cluster" "cc_sr_cluster" {
  package = "ESSENTIALS"
  environment {
    id = var.confluent_environment_id

  }
  region {
    id ="eu-central-1"
  }
  lifecycle {
    prevent_destroy = false
  }
}
```
and now it looks like this:
```
data "confluent_schema_registry_cluster" "cc_sr_cluster" {
  environment {
    id = var.confluent_environment_id
  }
}
```

but now i get the following error:
│ Error: error reading Schema Registry Clusters: there are no SR clusters in "env-xxxxxx" environment

What steps I am missing here? We want to create a new schema registry cluster. Not create in the CCloud UI and reference it.

Thank you in advance

**Comment by linouk23** [comment]
Thanks for creating the issue @conting! You are absolutely correct. Feel free to read the following guide for more details:

- [Version 2 Upgrade Guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/version-2-upgrade)

In summary, you would need to use the following code snippet:

```hcl
data "confluent_schema_registry_cluster" "essentials" {
  environment {
    id = confluent_environment.staging.id
  }

  depends_on = [
    confluent_kafka_cluster.basic
  ]
}
```
