### ISSUE TITLE
GCP Peering Documentation Issue

### ISSUE THREAD

**Issue by awattez** [confluentinc/terraform-provider-confluent#506]
# GCP Peering Documentation Issue

## Versions Affected
- Prior to version 2.11.0

## Current Issue
The documentation shows an example of GCP peering configuration that includes an unsupported parameter. When using the confluent provider version 2.11.0, attempting to use the `customer_region` parameter in the `confluent_peering` resource results in an error.

## Provider Configuration
```hcl
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "~> 2.11.0"
    }
  }
}
```

## Current Documentation Example
```hcl
resource "confluent_peering" "gcp" {
  display_name = "GCP Peering"
  gcp {
    project = "temp-gear-123456"
    vpc_network = "customer-test-vpc-network"
    customer_region = "us-west4"  # This parameter is not supported
  }
  environment {
    id = confluent_environment.development.id
  }
  network {
    id = confluent_network.gcp-peering.id
  }
  lifecycle {
    prevent_destroy = true
  }
}
```

## Error Message
```
│ Error: Unsupported argument
│ 
│   on main.tf line 58, in resource "confluent_peering" "gcp":
│   58:     customer_region = var.gcp_region_source
```

## Correct Usage
The `customer_region` parameter should be removed from the GCP peering configuration as it's not a supported argument.

```hcl
resource "confluent_peering" "gcp" {
  display_name = "GCP Peering"
  gcp {
    project = "temp-gear-123456"
    vpc_network = "customer-test-vpc-network"
  }
  environment {
    id = confluent_environment.development.id
  }
  network {
    id = confluent_network.gcp-peering.id
  }
  lifecycle {
    prevent_destroy = true
  }
}
```

**Comment by linouk23** [comment]
@awattez, thank you for creating the issue! You're right; this is definitely a typo. In fact, if you check the [Argument Reference](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_peering#argument-reference) section, you won't find customer_region listed under the `gcp` block.

**Comment by awattez** [comment]
You're welcome @linouk23! Indeed, even in real-world examples outside of the documentation, that typo wasn't present. I had submitted [this PR](https://github.com/confluentinc/terraform-provider-confluent/pull/507) to simplify the process, but it's no big deal. I saw that you had a ticket and a PR that was merged into master, cool, thanks!
