### ISSUE TITLE
role-binding-id: unable to find in Confluent Cloud

### ISSUE THREAD

**Issue by hari-rad** [confluentinc/terraform-provider-confluent#52]
Hi,
We have configured resources manually through the Confluent cloud console so far. Now we would like to use terraform. In order to import the existing role-bindings into the tf state, the command line requires role-binding IDs in the format "rb-abc123". I could not find the existing role-binding IDs from the Confluent cloud console or through the CLI. Could you please clarify?
Thanks,
Hari

**Comment by linouk23** [comment]
Thanks for asking @hari-rad!

It's a temporary limitation that you can't see role binding IDs on both Confluent Cloud Console and CLI.

The easiest solution could be to send a curl using Role Bindings API that would lists them all:
```
curl --request GET \
  --url "https://api.confluent.cloud/iam/v2/role-bindings?crn_pattern=crn://confluent.cloud/organization={YOUR_ORG_ID}" \
  --header 'Authorization: Basic {TOKEN}'
```

where

* `YOUR_ORG_ID` is _Cloud Organization ID_ from [this page](https://confluent.cloud/settings/billing/payment)
* `TOKEN` is 
![image](https://user-images.githubusercontent.com/5459870/174418416-5ec348b8-d692-47e2-b051-c61616bcb9a7.png)

(find more details [here]([url](https://docs.confluent.io/cloud/current/api.html#section/Authentication))) 

Let me know if that helps.

**Comment by hari-rad** [comment]
Wow, that helps! Thank you @linouk23
