### ISSUE TITLE
Undefined response type creating connector

### ISSUE THREAD

**Issue by TheTFo** [confluentinc/terraform-provider-confluent#53]
I'm using v.0.10.0 of the Confluent TF provider.  I'm getting issues when creating a connector:

```
 Error: error creating Connector "assets_outbox_source_connector": error sending validation request: undefined response type
   with module.confluent_config.confluent_connector.outbox_source_connector["true"],
   on ../../modules/confluent_config/connector.tf line 13, in resource "confluent_connector" "outbox_source_connector":
   13: resource "confluent_connector" "outbox_source_connector" { 
```
My connector code is the following:

```
resource "confluent_connector" "outbox_source_connector" {
  for_each = local.all_outbox_params_present ? toset(["true"]) : toset([])

  environment {
    id = data.confluent_environment.env.id
  }

  kafka_cluster {
    id = data.confluent_kafka_cluster.cluster.id
  }

  config_sensitive = {
    "database.password" = var.outbox_db_password
  }

  config_nonsensitive = {
    "name"            = "assets_outbox_source_connector"
    "connector.class" = "io.debezium.connector.postgresql.PostgresConnector"

    "kafka.auth.mode"          = "SERVICE_ACCOUNT"
    "kafka.service.account.id" = resource.confluent_service_account.sa.id

    "plugin.name"          = "pgoutput"
    "database.port"        = "${var.outbox_db_port}"
    "database.user"        = var.outbox_db_username
    "database.hostname"    = var.outbox_db_host
    "database.dbname"      = var.outbox_db_database
    "database.server.name" = var.outbox_db_server_name
    "database.sslmode"     = "require"
    "table.includelist"    = var.outbox_db_table
    "tombstones.on.delete" = "false"
    "output.key.format"    = "AVRO"
    "binary.handling.mode" = "bytes"
    "output.data.format"   = "AVRO"

    #transforms = "onlyCreate,useAfterState,setKey,extractKeyValue,setTopic"

    #"transforms.onlyCreate.type"             = "io.confluent.connect.transforms.Filter$Value"
    #"transforms.onlyCreate.filter.condition" = "[?($.op=='c' || $.op=='r')]"
    #"transforms.onlyCreate.filter.type"      = "include"

    #"transforms.useAfterState.type"  = "org.apache.kafka.connect.transforms.ExtractField$Value"
    #"transforms.useAfterState.field" = "after"

    #"transforms.setKey.type"   = "org.apache.kafka.connect.transforms.ValueToKey"
    #"transforms.setKey.fields" = "key"

    #"transforms.extractKeyValue.type"  = "org.apache.kafka.connect.transforms.ExtractField$Key"
    #"transforms.extractKeyValue.field" = "key"

    #"transforms.setTopic.type"  = "io.confluent.connect.transforms.ExtractTopic$Value"
    #"transforms.setTopic.field" = "outboxTopic"
  }

  depends_on = [
    resource.confluent_kafka_acl.assets_topics["cluster_eh_allow_describe"],
    resource.confluent_kafka_acl.assets_topics["cluster_eh_allow_describe_configs"],
    resource.confluent_kafka_acl.assets_topics["topic_outbox_connector_topic_create"],
    resource.confluent_kafka_acl.assets_topics["topic_outbox_connector_topic_write"],
    resource.confluent_kafka_acl.assets_topics["topic_assets_log_allow_describe"],
    resource.confluent_kafka_acl.assets_topics["topic_assets_log_allow_read"],
    resource.confluent_kafka_acl.assets_topics["topic_assets_log_allow_write"],
    resource.confluent_kafka_acl.assets_topics["group_assets_consumer_groups_allow_read"]
  ]
}
```
I've confirmed ACLs look good, all the DB settings are setup, and I've created a very similar connector sucessfully through the UI, basically just with a different name.  I've removed the transforms here to test if those were the issue, but doesn't appear to be.

Is there a way to get better feedback as to why the issue is?

**Comment by linouk23** [comment]
Could you [enable logs](https://www.terraform.io/internals/debugging) in Terraform? Logs will give you detailed error messages that you can use to investigate issues. Use these commands to enable logs:
```
export TF_LOG_PATH="./full_log.txt"
export TF_LOG=trace
terraform apply --auto-approve
```
You should then open the log file in TF_LOG_PATH path to see the full logs.

**Comment by TheTFo** [comment]
Thanks for the response.  I'm concerned about sending the entire set of logs as there could be sensitive information in there.  Is there something I can search on to narrow down what we're looking for?  That being said, there doesn't appear to be much more in there than what I saw in the console. For example, I don't see the HTTP request or response that I see with the AWS provider.

As for the other item, the connector did NOT create, unfortunately.

**Comment by linouk23** [comment]
Sure thing @TheTFo. I'd be specifically interested in logs from [connectorCreate()](https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/resource_connector_v1.go#L96) (they all start with `tflog.Debug(`).

**Comment by TheTFo** [comment]
So good news, I realized I was using the non-confluent hosted class name for the Debezium CDC Connector.  I had:
```
    // In general purpose Kafka Conenct, this is the class
    // "connector.class" = "io.debezium.connector.postgresql.PostgresConnector"

    // In Confluent Cloud Kafka Connect, this is the one
    "connector.class" = "PostgresCdcSource"
```

Still errors, but at least I can see what they are and work through them!

This issue can be closed, though it may be helpful to have some indication that the connector.class attribute was not valid.

**Comment by linouk23** [comment]
@TheTFo actually let me keep this issue open until the team resolves the underlying issue for displaying `Undefined response type creating connector`. FWIW TF should have displayed something like:
```
Error: error creating Connector "assets_outbox_source_connector": error sending validation request: unable to validate connector config: unable to validate plugin type: connect service: connector plugin io.debezium.connector.postgresql. PostgresConnector unavailable: resource not found
```

**Comment by linouk23** [comment]
@TheTFo check out our latest `1.0.0` [release](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#100-june-30-2022) where we
> * Fixed "undefined response type" error for `confluent_connector` resource ([#53](https://github.com/confluentinc/terraform-provider-confluent/issues/53)).
