### ISSUE TITLE
Azure Private links does not fail with Basic Kafka Cluster, but it should.

### ISSUE THREAD

**Issue by rogerioefonseca** [confluentinc/terraform-provider-confluent#56]
**Description:**
I figured that I was able to create a BASIC KAFKA Cluster in terraform and LINK it with an AZURE PRIVATE LINKS.
I took a look at the documentation and looks like the Private link just works with the DEDICATED version.
On our side, it was very frustrating that there were no Warnings on the Terraform PLAN/APPLY side because we were counting on that and we just figured out that limitation while reading the pricing list.

![image](https://user-images.githubusercontent.com/17765109/175971929-ac0f9501-4f1e-4052-9dbd-e26970aed1e0.png)

**How to reproduce:**
Create a terraform code with 
`resource "confluent_private_link_access_v1" "azure-private-link-access" {
  display_name = "Azure Private Link Access for TEST"
  azure {
    subscription = var.azure_subscription
  }
  environment {
    id = confluent_environment_v2.environment.id <---- This should NOT work and fail on TERRAFORM PLAN because the cluster is the BASIC type
  }
  network {
    id = confluent_network_v1.azure-private-link.id
  }
}

resource "confluent_kafka_cluster_v2" "cluster" {
  display_name = var.environment_name
  availability = var.availability
  cloud        = var.cloud
  region       = var.region
  basic {}

  environment {
    id = confluent_environment_v2.environment.id
  }
}`

**Conclusion**
Not sure if that is done by design, but for me looks strange...
I'm able to create a cluster of the BASIC type and attach an AZURE Private link to IT.
On my understanding that should be treated as a Business Error and fail on the Terraform PLAN

**Comment by linouk23** [comment]
@rogerioefonseca thanks for creating an issue!

I think the gotcha here is `confluent_private_link_access_v1` is "attached" to a network (and not to a Kafka cluster) that might contain different clusters. FWIW I don't think you can create any clusters but Dedicated ones attached to the network either.

Let me know if that helps.

**Comment by rogerioefonseca** [comment]
> 

Very good, Thanks a lot, I got it.
So then, at least for me, the issue can be considered closed since it is actually a misunderstanding on my end.

**Comment by linouk23** [comment]
@rogerioefonseca well, we could argue it's unclear documentation on our side 😁  but yeah it might not be relevant to TF Provider.

**Comment by rogerioefonseca** [comment]
> @rogerioefonseca well, we could argue it's unclear documentation on our side 😁 but yeah it might not be relevant to TF Provider.

Haha, that is a point!
Yeah, thanks for the support!
