### ISSUE TITLE
The new Provider version is deprecating resources and it is not MAJOR

### ISSUE THREAD

**Issue by rogerioefonseca** [confluentinc/terraform-provider-confluent#58]
Hello there,
I noticed that 14 hours ago you released a new version of the provider(0.12.0).
While trying to use it I noticed that you renamed/deprecated resources and the new version is compatible only with terraform 0.13+

I can be wrong but that looks is a breaking compatibility release and the version should have a MAJOR change.

Let me know your thoughts...

**Comment by linouk23** [comment]
Thanks for asking @rogerioefonseca!

Hopefully the [migration](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.12.0) to new resources didn't take too much time, it's a very one-off thing that we [hope](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#0120-june-27-2022) to avoid in the future.

> I can be wrong but that looks is a breaking compatibility release and the version should have a MAJOR change.

The idea here is TF Provider is currently in _Public Preview_ (i.e., not recommended for production):
![image](https://user-images.githubusercontent.com/5459870/176225484-10c41607-bf08-4657-8752-f49964f4f192.png)

but once it is (it's coming very soon!), we'd like to version this release as `1.0.0`. And going forward, exactly as you said, we'd bump a major version for every breaking change.

Let me know if it helps.

**Comment by rogerioefonseca** [comment]
> Thanks for asking @rogerioefonseca!
> 
> Hopefully the [migration](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.12.0) to new resources didn't take too much time, it's a very one-off thing that we [hope](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#0120-june-27-2022) to avoid in the future.
> 
> > I can be wrong but that looks is a breaking compatibility release and the version should have a MAJOR change.
> 
> The idea here is TF Provider is currently in _Public Preview_ (i.e., not recommended for production): ![image](https://user-images.githubusercontent.com/5459870/176225484-10c41607-bf08-4657-8752-f49964f4f192.png)
> 
> but once it is (it's coming very soon!), we'd like to version this release as `1.0.0`. And going forward, exactly as you said, we'd bump a major version for every breaking change.
> 
> Let me know if it helps.

Thanks for the explanation
