### ISSUE TITLE
Support for managed connectors

### ISSUE THREAD

**Issue by atimush** [confluentinc/terraform-provider-confluent#6]
Hello,
Do you folks have anything in the roadmap to manage the connectors in TF?
Would be super nice, for example, to manage S3 Synk for backup purposes and keep the connector config updated dynamically with all the topics!

Thank you,
Andrei

**Comment by linouk23** [comment]
@atimush, @czerasz-mineiros, @matefarkas-recrd, @smag-bmesseca, @aakarshg, @mohitreddy1996, @thekiwi, @maheshbhole, and @mool we're happy to let you know that we shipped `confluent_connector` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_connector) in our latest `0.8.0` [release](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#080-may-12-2022).

I'm closing this issue, feel free to open more "specific" ones related to connector resource.
