### ISSUE TITLE
Cluster API Keys get refreshed for every run of terraform

### ISSUE THREAD

**Issue by maheshbhole** [confluentinc/terraform-provider-confluent#62]
Description :
When we run terraform script multiple times (which will be always the case) , API keys for cluster gets refreshed.
This will be problem if we are sharing API keys and secrets with other consumers.
Is there any way so that we can refrain API keys from refreshing.
Also API_Keys are not available as data resource.

**Comment by linouk23** [comment]
Thanks for asking @maheshbhole!

I'm not quite sure I fully understand the issue here.

> API keys for cluster gets refreshed.

By "refreshed" you mean like deleted & created again?

Looking at [managing-single-cluster](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/managing-single-cluster) might help where both `confluent_kafka_acl` & `confluent_kafka_topic` don't use `credentials` (Kafka API Keys) in their definitions / TF state.

**Comment by maheshbhole** [comment]
Yes. thats right , getting deleted and created again.
But isn't terraform state file maintains that API Keys and Secert are already available and should not try to recreate it ?

**Comment by linouk23** [comment]
@maheshbhole 

> Yes. thats right , getting deleted and created again.

By default, that's definitely not expected (for example, you can run [basic-kafka-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/basic-kafka-acls) example and then when you run `terraform plan` after applying the plan, you'll see no changes -- Kafka API Keys from that example are not getting deleted / created again.

> But isn't terraform state file maintains that API Keys and Secert are already available and should not try to recreate it ?

That's absolutely correct, we shouldn't expect them to be recreated.

Could you share your TF configuration with `cflt-tf-access@confluent.io` / Confluent support so we could take a look at it? That definitely sounds weird.

**Comment by linouk23** [comment]
@maheshbhole I think my latest comment should be able to help, so I'm closing this stale issue but feel free to reopen if you have any further questions.
