### ISSUE TITLE
Cannot change cluster type dynamically

### ISSUE THREAD

**Issue by col** [confluentinc/terraform-provider-confluent#64]
We're using Terraform to create clusters across multiple environments. Our code to do that looks something like this:

```
resource "confluent_kafka_cluster" "cluster" {
  for_each = toset(var.environments)

  display_name = "${each.key}-cluster"
  availability = "SINGLE_ZONE"
  cloud        = "GCP"
  region       = "asia-southeast1"
  basic {}

  environment {
    id = confluent_environment.env[each.key].id
  }
}
```

This works fine but we would now like to upgrade our prod cluster from `basic` to `standard`. Unfortunately, because the cluster type is determined by these empty blocks it's very difficult (or impossible?) to change the cluster type for a specific environment. 

I tried using dynamic blocks, but this approach doesn't appear to work.
```
resource "confluent_kafka_cluster" "nonprod-cluster" {
  for_each = toset(var.environments)

  display_name = "${each.key}-cluster"
  availability = "SINGLE_ZONE"
  cloud        = "GCP"
  region       = "asia-southeast1"
  dynamic "basic" {
    for_each = each.key != "prod" ? [1] : []
    content {}
  }
  dynamic "standard" {
    for_each = each.key == "prod" ? [1] : []
    content {}
  }

  environment {
    id = confluent_environment.env[each.key].id
  }
}
```

Is there another way to achieve this? If not, it feels like this could be improved by providing a specific attribute to set the cluster type rather than using these empty config blocks. 

For example:
```
resource "confluent_kafka_cluster" "nonprod-cluster" {
  for_each = toset(var.environments)

  display_name = "${each.key}-cluster"
  availability = "SINGLE_ZONE"
  cloud        = "GCP"
  region       = "asia-southeast1"
  type          = each.key == "prod" ? "standard" : "basic"
  
  environment {
    id = confluent_environment.env[each.key].id
  }
}
```

I realise there is some extra config required for the `dedicated` cluster type which would also need to be resolved.

**Comment by col** [comment]
Thanks for the quick response @linouk23!
Reading through the issue you linked to it looks like my original attempt at using dynamic blocks may have worked if we were using a more up to date version of Terraform (>= v0.15.5). I'll see if we can upgrade and give that another try.

**Comment by linouk23** [comment]
> Reading through the issue you linked to it looks like my original attempt at using dynamic blocks may have worked if we were using a more up to date version of Terraform (>= v0.15.5). I'll see if we can upgrade and give that another try.

That's a great catch, let me it know whether it helps.

**Comment by col** [comment]
@linouk23 Upgraded terraform to v0.15.5 and the dynamic blocks are now working as expected. Problem solved. Thanks for your help!
