### ISSUE TITLE
Clarification on whether Ksqldb api_keys, RBAC, etc can be built with current resource/apis - Confluent Cloud

### ISSUE THREAD

**Issue by nick-osborn** [confluentinc/terraform-provider-confluent#69]
I know that there are various components that are not quite yet supported in relation to KSQL and Schema Registry but looking through the V2 api's used for the terraform code has several mentions of allowing api_key creation for either of them(https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/resource_api_key.go#:~:text=Schema%20Registry%20and-,ksqlDB,-don%27t%20use%20paramEnvironment). 
Ive run it down a few different ways and hit various errors.

1) API_keys - have issues applying to a ksql cluster
Error: invalid value for managed_resource.0.id (the resource ID must be of the form 'lkc-')
Im setting an owner to a specific user acct, and managed resource to ksql_db and an env(which is odd cause the repo mentioned above says that ksqldb wont have an environment. 

Are Schema Registry and KSQLDB api_keys not supported?

2) RBAC - have issues understanding how to form RBAC specific to ksql and have strange results 

Initially im able to create the following pattern but debug logs gives a strange response about an older api causing unexpected behaviors but then allowing anyway.

crn_pattern = "${var.cluster_rbac_crn}/kafka=${var.cluster_id}/ksql-cluster=${var.ksql_db}"

the next run causes a replacement that drops the ksql cluster from CRN entirely(each time)
-/+ resource "confluent_role_binding" "svc-ksql-cluster-rbac" {
      ~ crn_pattern = "crn://confluent.cloud/organization=********-****-****-****-***********/environment=env-*****/cloud-cluster=lkc-*****/kafka=lkc-*****" -> "crn://confluent.cloud/organization=********-****-****-****-***********/environment=env-*****/cloud-cluster=lkc-*****/kafka=lkc-*****/ksql-cluster=lksqlc-*****" # forces replacement

Also tried with crn_pattern = "${var.cluster_rbac_crn}/kafka=${var.cluster_id}/ksql=${var.ksql_db}" but that gives an immediate 400 error

**Comment by linouk23** [comment]
Thanks for creating an issue @nick-osborn!

> Are Schema Registry and KSQLDB api_keys not supported?

They're not supported yet.

> ksql & RBAC

That's not supported yet either.

All of ⬆️ are on the roadmap but we don't know the ETAs yet.

**Comment by nick-osborn** [comment]
Ahhh ok. I guess the comments referencing ksqldb and schema registry are for future purposes. It makes sense given the apis dont make any mention of it either. https://docs.confluent.io/cloud/current/api.html 

:( 

Thanks for letting me know @linouk23 . Ill keep an eye out for the enhancements!
