### ISSUE TITLE
Schemaregistry related resources as terraform resource

### ISSUE THREAD

**Issue by andreaskeutner** [confluentinc/terraform-provider-confluent#7]
All schemaregistry related resources should be deployable via terraform.

This includes:

- schemaregistry 
- schema 
- API-keys

**Comment by linouk23** [comment]
Closing it as a duplicate to #5.

**Comment by linouk23** [comment]
update: we [released](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1100-october-26-2022) a new `1.10.0` version of TF Provider where we dded new `confluent_stream_governance_cluster` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_stream_governance_cluster) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_stream_governance_cluster) in an [Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy).

cc @andreaskeutner @lorelei-rupp-imprivata

**Comment by lorelei-rupp-imprivata** [comment]
> update: we [released](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1100-october-26-2022) a new `1.10.0` version of TF Provider where we dded new `confluent_stream_governance_cluster` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_stream_governance_cluster) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_stream_governance_cluster) in an [Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy).
> 
> cc @andreaskeutner @lorelei-rupp-imprivata

This isnt a schema registry resource though right? This is something else? @linouk23

**Comment by linouk23** [comment]
`confluent_stream_governance_cluster` is essentially SR cluster @lorelei-rupp-imprivata.

**Comment by lorelei-rupp-imprivata** [comment]
> `confluent_stream_governance_cluster` is essentially SR cluster @lorelei-rupp-imprivata.
So we are not using governance clusters, but we do set up a schema registry for our environments. I have seen things to upgrade to this stream governance stuff but we are not doing that at this time.

Will schema registry creation still be coming then in the terraform provider?

**Comment by linouk23** [comment]
It's on the roadmap, correct. Subscribe to https://github.com/confluentinc/terraform-provider-confluent/issues/124 for the updates.
