### ISSUE TITLE
Migrating from 0.11.0 to 1.0.0 version

### ISSUE THREAD

**Issue by hari-rad** [confluentinc/terraform-provider-confluent#70]
Hi,
We were using 0.11.0 version of the provider earlier. I was wondering what would be the best way to migrate to the new 1.0.0 version, as most of the resource types have changed; I mean, `confluent_kafka_acl_v3` is now `confluent_kafka_acl` etc. Is there any easy/best way to do this?
Thanks,
Hari

**Comment by linouk23** [comment]
👋 @hari-rad, thanks for asking, that's a great question!

Let me start off by saying we made a bad decision to rename resources and it's unfortunate you have to go through painful migration process twice.

We'd recommend 

1. Going through [this guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.12.0) which will help you to upgrade to `0.12.0` first
2. Update the version from `0.12.0` to `1.0.0` (there were no breaking changes between these version).

Let us know if you have any questions!
