### ISSUE TITLE
Add Support for Dedicated Cluster Configuration Settings

### ISSUE THREAD

**Issue by Jberlinsky** [confluentinc/terraform-provider-confluent#73]
We're trying to configure [Broker Configuration](https://docs.confluent.io/cloud/current/clusters/broker-config.html#custom-settings-dedicated) for a Dedicated Cluster, but can't seem to find support in the provider. Any chance this is on the roadmap for implementation?

**Comment by jfp202** [comment]
Hi @Jberlinsky,
  I'm looking for having more control about how the cluster is deployed. So It would be good if we were able to control some properties, auto.creation.topic, cleanup.policy, number.partitions, etc.

**Comment by linouk23** [comment]
👋 thanks for creating the issue!

> Any chance this is on the roadmap for implementation?

It is on the roadmap 👍

**Comment by linouk23** [comment]
👋 everyone, you might want to check out our latest `1.7.0` [release](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.7.0) where we 

> Added new confluent_kafka_cluster_config [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_cluster_config) in an [Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy) (https://github.com/confluentinc/terraform-provider-confluent/issues/73).

cc @Jberlinsky @jfp202 @devopsmatt @justrp @muresan @sepehrmavedati
