### ISSUE TITLE
Issue with Setting up DNS records in PrivateLink Setup to the Dedicated cluster

### ISSUE THREAD

**Issue by VipulZopSmart** [confluentinc/terraform-provider-confluent#76]
Hi @linouk23, i'm trying to setup PrivateLink setup with the terraform scripts, in the step for setting up the DNS records, it's throwing these errors. Could you please kindly help in the same as i've used the same terraform scripts that are given [here](https://github.com/confluentinc/terraform-provider-confluent/blob/121c1cb349af1aaba12eb759c6953015a61edf0f/examples/configurations/dedicated-privatelink-aws-kafka-acls/main.tf#L258).

```

aws_vpc_endpoint.privatelink: Still creating... [1m40s elapsed]
aws_vpc_endpoint.privatelink: Still creating... [1m50s elapsed]
aws_vpc_endpoint.privatelink: Still creating... [2m0s elapsed]
aws_vpc_endpoint.privatelink: Still creating... [2m10s elapsed]
aws_vpc_endpoint.privatelink: Creation complete after 2m15s [id=vpce-xyz]
╷
│ Error: Error in function call
│ 
│   on main.tf line 253, in locals:
│  253:   hosted_zone      = replace(regex("^[^.]+_([0_9a_zA_Z]+[.].*):[0_9]+$", confluent_kafka_cluster.dedicated.bootstrap_endpoint)[0], "glb.", "")
│     ├────────────────
│     │ confluent_kafka_cluster.dedicated.bootstrap_endpoint is "lkc-w7kgd5-pdwnk6.us-west-2.aws.glb.confluent.cloud:9092"
│ 
│ Call to function "regex" failed: pattern did not match any part of the
│ given string.
╵
Releasing state lock. This may take a few moments...
ERRO[3751] Module /Users/vsharma8/projects/github.int.mcafee.com/mcafee/efw-infra/infra/qa has finished with an error: 1 error occurred:
        * exit status 1
  ```

**Comment by linouk23** [comment]
Thanks for reporting an issue @VipulZopSmart!

That actually looks interesting. Could you double check the value of `confluent_kafka_cluster.dedicated.bootstrap_endpoint`?

When I run it locally:
```
locals {
  new_boostrap = "lkc-w7kgd5-pdwnk6.us-west-2.aws.glb.confluent.cloud:9092"
}

output "foo" {
  value = replace(regex("^[^.]+-([0-9a-zA-Z]+[.].*):[0-9]+$", local.new_boostrap)[0], "glb.", "")
}
```

I can see:
```
terraform plan

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + foo = "pdwnk6.us-west-2.aws.confluent.cloud"
```

I can't reproduce it 🤔

**Comment by VipulZopSmart** [comment]
@linouk23 , i erased the line and copy pasted again, now that is working fine but while creating API keys for the topics now it's failing. The errors are as follows:

```
╷
│ Error: error waiting for Kafka API Key "AKLRQC4ARLUDTXKV" to sync: error listing Kafka Topics using Kafka API Key "AKLRQC4ARLUDTXKV": Get "https://lkc-w7kgd5-pdwnk6.us-west-2.aws.glb.confluent.cloud:443/kafka/v3/clusters/lkc-w7kgd5/topics": GET https://lkc-w7kgd5-pdwnk6.us-west-2.aws.glb.confluent.cloud:443/kafka/v3/clusters/lkc-w7kgd5/topics giving up after 5 attempt(s): Get "https://lkc-w7kgd5-pdwnk6.us-west-2.aws.glb.confluent.cloud:443/kafka/v3/clusters/lkc-w7kgd5/topics": cannotconnect
│ 
│   with confluent_api_key.app_manager_kafka_api_key,
│   on main.tf line 58, in resource "confluent_api_key" "app_manager_kafka_api_key":
│   58: resource "confluent_api_key" "app_manager_kafka_api_key" {
│ 
╵
╷
│ Error: error waiting for Kafka API Key "RGCHUQAXKMVUNX65" to sync: error listing Kafka Topics using Kafka API Key "RGCHUQAXKMVUNX65": Get "https://lkc-w7kgd5-pdwnk6.us-west-2.aws.glb.confluent.cloud:443/kafka/v3/clusters/lkc-w7kgd5/topics": GET https://lkc-w7kgd5-pdwnk6.us-west-2.aws.glb.confluent.cloud:443/kafka/v3/clusters/lkc-w7kgd5/topics giving up after 5 attempt(s): Get "https://lkc-w7kgd5-pdwnk6.us-west-2.aws.glb.confluent.cloud:443/kafka/v3/clusters/lkc-w7kgd5/topics": cannotconnect
│ 
```

Not sure if the API keys got created, it's failing in between.

**Comment by linouk23** [comment]
👍 @VipulZopSmart 

This new issue is related to connectivity issue:

> This example assumes that Terraform is run from a host in the private network, where it will have connectivity to the [Kafka REST API](https://docs.confluent.io/cloud/current/api.html#tag/Topic-(v3)) in other words, to the [REST endpoint](https://docs.confluent.io/cloud/current/clusters/broker-config.html#access-cluster-settings-in-the-ccloud-console) on the provisioned Kafka cluster.

**Comment by VipulZopSmart** [comment]
@linouk23 i added `disable_wait_for_ready`, now it's failing in generating ACLs and the topics, the errors are same like above looks like some connectivity issue. Could you please tell me do i need to add something in the resource of ACLs ant topics?

**Comment by linouk23** [comment]
@VipulZopSmart you need to run the whole example / or at least code snippet that creates ACL / topics from

> a host in the private network, where it will have connectivity to the [Kafka REST API](https://docs.confluent.io/cloud/current/api.html#tag/Topic-(v3)) in other words, to the [REST endpoint](https://docs.confluent.io/cloud/current/clusters/broker-config.html#access-cluster-settings-in-the-ccloud-console) on the provisioned Kafka cluster.

Namely, run Terraform configuration from an ec2 instance that is in the target network (not just from a laptop).
