### ISSUE TITLE
Use the RESOURCE ID OUTPUT from the confluent_private_link_access_v1 to create an Azure Endpoint

### ISSUE THREAD

**Issue by rogerioefonseca** [confluentinc/terraform-provider-confluent#78]
Hello there,
Not sure if I'm doing something wrong, but using the documentation I created a `confluent_private_link_access` and I was hoping that from It's output I could create an `azure_private_endpoint`, but I figured that the output from confluent_private_link_access_v1.azure-private-link-access.id is a code using the pattern XXX-XXXXX
`
resource "confluent_private_link_access_v1" "azure-private-link-access" {
  display_name = "Azure Private Link Access for ${var.application_name}"
  azure {
    subscription = var.azure_subscription
  }
  environment {
    id = confluent_environment_v2.environment.id
  }
  network {
    id = confluent_network_v1.azure-private-link.id
  }
}

resource "azurerm_private_endpoint" "kafka_private_endpoint" {
   name                = var.endpoint_name
   location            = var.region
   resource_group_name = var.azure_resource_group
   subnet_id           = var.subnet_id
 
   dynamic "private_service_connection" {
     for_each = var.type == "dedicated" ? [1] : [0]
     content {
       name                           = var.kafka_private_service_connection_name
       private_connection_resource_id = confluent_private_link_access_v1.azure-private-link-access.id
       is_manual_connection           = var.is_manual_connection
     }
   }
 }
` 

And that is not actually the full resource ID that I can use and of course if I try the pipeline breaks.
![image](https://user-images.githubusercontent.com/17765109/182408042-ada29a84-b3d9-4ae5-b0d5-1787ddaf1a09.png)

I would like to know if there is a way to get the resource ID from the Private Link Service?

**Comment by linouk23** [comment]
Thanks for asking @rogerioefonseca!

Could you share more about the resource ID you'd like private link access object to expose?

Did you also take a look at [dedicated-privatelink-azure-kafka-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-privatelink-azure-kafka-acls)? That's an all-in-one example that sets up DNS on Azure, here's a snippet for `azurerm_private_endpoint`:

```
resource "azurerm_private_endpoint" "endpoint" {
  for_each = confluent_network.private-link.azure[0].private_link_service_aliases

  name                = "confluent-${local.network_id}-${each.key}"
  location            = var.region
  resource_group_name = data.azurerm_resource_group.rg.name

  subnet_id = data.azurerm_subnet.subnet[each.key].id

  private_service_connection {
    name                              = "confluent-${local.network_id}-${each.key}"
    is_manual_connection              = true
    private_connection_resource_alias = each.value
    request_message                   = "PL"
  }
}
```

**Comment by rogerioefonseca** [comment]
> Thanks for asking @rogerioefonseca!
> 
> 
> 
> Could you share more about the resource ID you'd like private link access object to expose?
> 
> 
> 
> Did you also take a look at [dedicated-privatelink-azure-kafka-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-privatelink-azure-kafka-acls)? That's an all-in-one example that sets up DNS on Azure, here's a snippet for `azurerm_private_endpoint`:
> 
> 
> 
> ```
> 
> resource "azurerm_private_endpoint" "endpoint" {
> 
>   for_each = confluent_network.private-link.azure[0].private_link_service_aliases
> 
> 
> 
>   name                = "confluent-${local.network_id}-${each.key}"
> 
>   location            = var.region
> 
>   resource_group_name = data.azurerm_resource_group.rg.name
> 
> 
> 
>   subnet_id = data.azurerm_subnet.subnet[each.key].id
> 
> 
> 
>   private_service_connection {
> 
>     name                              = "confluent-${local.network_id}-${each.key}"
> 
>     is_manual_connection              = true
> 
>     private_connection_resource_alias = each.value
> 
>     request_message                   = "PL"
> 
>   }
> 
> }
> 
> ```

Hello @linouk23 , thanks for your reply.
Yes, I was wrong trying to use the  service ID.
As it is described in the example that you mentioned, I must use the service alias instead.
Thanks for your support
