### ISSUE TITLE
Determine AZ ID(s) of Dedicated Cluster

### ISSUE THREAD

**Issue by patrickherrera** [confluentinc/terraform-provider-confluent#80]
We are automating our AWS PrivateLink setup for a dedicated cluster but there seems to be a piece of information that is not exported by the `confluent_kafka_cluster` resource.  In the PrivateLink manual setup [docs](https://docs.confluent.io/cloud/current/networking/private-links/aws-privatelink.html#set-up-the-vpc-endpoint-for-aws-privatelink-in-your-aws-account) it states:

> Note the availability zones for your Confluent Cloud cluster from the Networking tab in the Confluent Cloud Console. Select the service in these zones. Ensure the desired subnet is selected for each zone. Failure to add all zones as displayed in the Confluent Cloud Console can cause connectivity issues to brokers in the omitted zones, which can result in an unusable cluster.

How can we automate the lookup of the deployed AZ ID(s) for a single/multi-zone cluster?  I can derive the region from the endpoints returned but I don't think that will be sufficient then setup the correct subnets for the PrivateLink endpoint.  A quick look at the API indicates that it doesn't return AZ IDs either.

Are there any suggestions on how this can be done or what I'm missing?

**Comment by linouk23** [comment]
@patrickherrera that's a great catch that we recently run into internally!

I think the fix is specifying `zones` [attribute](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_network) when creating a network that a Kafka cluster is attached to:
```
resource "confluent_network" "private-link" {
  display_name     = "Private Link Network"
  cloud            = "AWS"
  region           = var.region
  connection_types = ["PRIVATELINK"]
  zones            = keys(var.subnets_to_privatelink)
  environment {
    id = confluent_environment.staging.id
  }
}
```

We'll update examples in our next release.

**Comment by patrickherrera** [comment]
Thanks, yes, that makes sense - I hadn't specified them since we don't have a preference.  The docs state however: ` (Optional List of String) The 3 availability zones for this network`, so what does that mean if I want to attach a `SINGLE_ZONE` Cluster to this Network.  Can I specify a single Zone ID? Or does it have to be 3 (or none) and the Cluster is still assigned randomly to one of them, in which case I still won't know which one.
I had a quick look at the source code and it says:
```
	MinItems: 3,
	MaxItems: 3,
```
so it looks like I don't get to specify a single one.

**Comment by linouk23** [comment]
@patrickherrera that's correct, network is always "assigned" to 3 availability zones.

As a result multi-zone clusters are spread across 3 availability zones (If you don't specify `zones`  -- 3 availability zones will be selected by Confluent Cloud).

>  Can I specify a single Zone ID? Or does it have to be 3 (or none) and the Cluster is still assigned randomly to one of them, in which case I still won't know which one.

Speaking about single-zone clusters, for now they can land in any of the 3 availability zones supported by the network. 
There's a feature request to support `single zone selection` for single-zone clusters but it hasn't been implemented yet.

> so it looks like I don't get to specify a single one.

That's accurate 👍

**Comment by linouk23** [comment]
Update: we updated an example to include `zones            = keys(var.subnets_to_privatelink)` in our latest 1.1.0 [release](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#110-august-9-2022).
