### ISSUE TITLE
Confluent Terraform Provider isn't fully Idempotent when we use *.tfsvars Config Type Array Elements

### ISSUE THREAD

**Issue by lturmel** [confluentinc/terraform-provider-confluent#82]
I've try the Confluent Terraform provider to create some elements on my confluent cloud subscription like:

- Environment
- Cluster
- Service Account Cloud API keys
- Service Account Cluster API keys

I notice some strange things when I use the Confluent Terraform scripts on conjunction with *.tfvars with custom type array, in order to avoid having hard coded value in our Terraform scripts.

In this example, I notice that with a cluster type array, defined into a kafkaclusters.dev.tfvars, when the array content changes, it destroy previously created Kafka cluster, even if the cluster name is still present in the kafkaclusters.dev.tfvars file.

**Run #1:** Creating a Dev environment with Two Kafka Cluster into Dev environment
![Run_1](https://user-images.githubusercontent.com/46848645/184674013-9a173089-5e5b-426a-8419-6a3b595f4207.png)

**Run No #1 Results**
- **dev_usweast** cluster is created with id **lkc-xq0xgx**
- **dev_useast** cluster is created with id **lkc-9kopj5**

**Run #2**: We remove cluster named **dev_uswest** (ID: **lkc-xq0xgx**)
![Run_2](https://user-images.githubusercontent.com/46848645/184674329-6863dfb9-edef-4787-8543-da5e4ecbe0b1.png)

**Run #2 Results**
- Terraform detect two clusters to destroy and one to create
- **dev_usweast** cluster is destroy with id **lkc-xq0xgx**
- **dev_useast** cluster is destroy with id **lkc-9kopj5**
- **dev_useast** cluster is created back with id **lkc-5735p2**

**Final Results**
![Resume_Run_1_2](https://user-images.githubusercontent.com/46848645/184685258-ad80f95f-15e0-49fb-965b-3dfb998e4478.png)

**Expectation**:

When we remove an item from the array, only this item is remove when we execute the terraform script.

PS: Link to my GitHub Repository for this issue: https://github.com/lturmel/confluent-terraform-provider-issue

**Comment by linouk23** [comment]
👋 thanks for asking!

Based on the output of `terraform plan`, it seems like an issue with using `count = length(var.clusters)`, I'm not too familiar with it but I might take a look later (sounds like TF decided your `clusters[1]` is the new `clusters[0]`).

That said, is there a specific reason not to hardcode resource definitions? For example, you might consider `basic` -> `standard` Kafka cluster updates at some point in the future so having an ability to run `terraform plan -target="confluent_kafka_cluster.example-123"` might be useful. Generally we expect users to split TF configurations by both env and teams.

Let me know if it helps.

**Comment by lturmel** [comment]
> 👋 thanks for asking!
> 
> Based on the output of `terraform plan`, it seems like an issue with using `count = length(var.clusters)`, I'm not too familiar with it but I might take a look later (sounds like TF decided your `clusters[1]` is the new `clusters[0]`). You might want to use `for_each` instead of `count` for iterated resources (see [here](https://cloud.google.com/docs/terraform/best-practices-for-terraform#count) for more details).
> 
> That said, is there a specific reason not to hardcode resource definitions? For example, you might consider `basic` -> `standard` Kafka cluster updates at some point in the future so having an ability to run `terraform plan -target="confluent_kafka_cluster.example-123"` might be useful. Generally we expect users to split TF configurations by both env and teams.
> 
> Let me know if it helps.

Hi @linouk23 , thanks taking the time to reply to my issue. The simple reason why I don't want to hardcoded the resource is simply because I want to respect the infrastructure as code principle where I can define a dev.tfvars & and prod.tfvars and apply it to the *.tf file I use to deploy my infrastructure component.... Like I always do with Azure Bicep. But here it's Terraform, and I should be able to do the same...

**Comment by lturmel** [comment]
Good morning @linouk23, let me re-phrase my question. 

Why if I define clusters in an array with cluster "name", why the terraform provider doesn't use the "name" that I use to identify which cluster is already existing and/or to be destroy in comparison with the terraform state file ? Which I'm assuming it use the cluster ID.

**Comment by lturmel** [comment]
@linouk23 Any update ?

**Comment by linouk23** [comment]
Did you try a similar setup with other TF Providers? cc @lturmel 

It looks like this might not specific to our TF Provider, did you try asking on StackOverflow or something?

**Comment by lturmel** [comment]
@linouk23 I will do, but I also speak with some peers that told me that my way of using it wasn't too much extreme, and to be honest with you, I found it really weird that we can't do it...

**Comment by linouk23** [comment]
Thank you! I'll try to find some time to experiment with it and report back the findings too.

**Comment by lturmel** [comment]
Hi @linouk23 thanks for you help, I didn't get it that the difference can be count = length(var.clusters) vs for_each... not it's working as expected... thanks you

**Comment by linouk23** [comment]
@lturmel that's great to hear! Could you post / reference an updated version that works? Could you confirm that the fix was to use `for_each` instead of `count`?

> You might want to use for_each instead of count for iterated resources (see [here](https://cloud.google.com/docs/terraform/best-practices-for-terraform#count) for more details).

**Comment by lturmel** [comment]
@linouk23  here are the working solution ;) 
![image](https://user-images.githubusercontent.com/46848645/186773703-11119830-3f20-4de8-9898-6887c5dd56a0.png)


> @lturmel that's great to hear! Could you post / reference an updated version that works? Could you confirm that the fix was to use `for_each` instead of `count`?
> 
> > You might want to use for_each instead of count for iterated resources (see [here](https://cloud.google.com/docs/terraform/best-practices-for-terraform#count) for more details).

**Comment by linouk23** [comment]
👏
