### ISSUE TITLE
confluent_api_key  support for schema registry and KSQL 

### ISSUE THREAD

**Issue by javiervelamindcurv** [confluentinc/terraform-provider-confluent#83]
confluent_api_key can't create API keys to access to Schema Registry or KSQL.

Are there any plan to support them?

**Comment by linouk23** [comment]
Thanks for creating this issue!

It's on the roadmap 👌

**Comment by S1M0NM** [comment]
Is there already an update on this point? With version 1.4.0 it is possible to create KSQL clusters via Terraform, but still no API keys for KSQL.
This means that you can only automate half of it because the API keys still have to be created manually using the CLI.

**Comment by swist** [comment]
You can fully automate ksql cluster! Instead of providing an API key and secret pair, terraform a service account and pass that to the ksql provider as a "credential_identity". We will handle creating the credentials for ksql for you transparently in the background. If you want to revoke access, delete the service account created by the provider

**Comment by S1M0NM** [comment]
This only helps when creating the cluster.
To access the cluster I still need a key-secret pair, which I cannot create via Terraform.

**Comment by Mohapatraabhishek-lab** [comment]
the support for creating API key and Secret for KSQL is available via confluent cli as of now. 
but when doing the same via terraform it is only accepting resource ID to be of KAFKA cluster's not for KSQL cluster.

![image](https://user-images.githubusercontent.com/85798041/189590503-f1d51663-74a7-4278-b970-5d1b6f38194e.png)

and i agree with @S1M0NM on using confluent CLI with loaclexec part.

**Comment by linouk23** [comment]
@Mohapatraabhishek-lab thanks for providing the context!

Adding ksql / SR keys to TF is on the roadmap but it's currently blocked by the capabilities of underlying [API Key Mgmt API](https://docs.confluent.io/cloud/current/api.html#tag/API-Keys-(iamv2)/operation/createIamV2ApiKey):
![image](https://user-images.githubusercontent.com/5459870/189591210-2f29aead-37fd-4cc5-b4f1-f21bd0f6a0fa.png)

**Comment by linouk23** [comment]
fyi the [latest release](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1230-december-16-2022) updates `confluent_api_key` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_api_key) to support Schema Registry API Keys and ksqlDB API Keys. See 

* [multiple-event-types-avro-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-avro-schema)
* [multiple-event-types-proto-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-proto-schema)
* [single-event-types-avro-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/single-event-types-avro-schema)
* [single-event-types-proto-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/single-event-types-proto-schema)
* [ksql-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/ksql-rbac)

to figure out how to create Schema Registry API Keys and ksqlDB API Keys via `confluent_api_key` resource.

cc @Mohapatraabhishek-lab @de1et3d @lturmel @miguelaferreira @poom @manishjain2-tomtom @rstarov @moonsub-kim @crflynn @mtranter @ppennanen @javiervelamindcurv @HSA72 @isaac-nuflo
