### ISSUE TITLE
Connector update in-place on failed connector does not fix it. Manually applying the same creds does. 

### ISSUE THREAD

**Issue by nick-osborn** [confluentinc/terraform-provider-confluent#84]
Hey team, Ive recently updated our connectors in-place with the new TF version(1.1.0) but the AWS AK/SK were longer valid. I added them to our TF process with Vault Key Value v2 and though it registers the change and applies them they do not switch back to running. I then took the same creds and applied directly to the connector manually in UI and it will then self-heal. Im curious if anyone else has encountered this issue. We're working through a process to automate the credential rotation - on a side note, happy to hear any thoughts on best case for this - but currently just waiting til they break while testing unless I remember t do it sooner.

Currently Im getting this: 
# module.sqs_dpe_streams["https://sqs.us-west-2.amazonaws.com/{acct-id}/feedback-sqs-queue-dev"].confluent_connector.sqs_source will be updated in-place
  ~ resource "confluent_connector" "sqs_source" {
      **~ config_sensitive    = (sensitive value)**
        id                  = "lcc-o3622j"
        # (2 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

The bolded section say to me that it should change the values and my assumption is that it should self-heal after that. Is there something else that needs to happen for it to do that?

The error after the change shows this still from UI: Failed
Unable to validate configuration. If an update was made to the configuration, this means that the configuration was invalid, and the connector continues to operate on a previous configuration that passed validation. Errors:
aws.access.key.id: The provided AWS Access Key is invalid

The one that was added manually has no errors and is in running status.

**Comment by linouk23** [comment]
Thanks for creating the issue!

Could you describe the process of updating credentials manually via the UI? More specifically, let's say a connector was in `RUNNING` state and then you updated `aws.access.key`, was there an update of status or something? Looks like you mentioned 

> applied directly to the connector manually in UI and it will then self-heal.

**Comment by linouk23** [comment]
cc @nick-osborn

**Comment by linouk23** [comment]
Thanks for the reply! Let me ask a couple of other questions:

> the AK/SK change

what "AK / SK" stand for here?

> When I manually change the connector, the status begins in failed

That's interesting, I think the expected behavior of a connector is to continue to be in `RUNNING` state unless the credentials are invalid.

But yeah overall I don't think we specifically tested the credential rotation workflow for connectors so we might want to test it on our side too.

**Comment by nick-osborn** [comment]
> Thanks for the reply! Let me ask a couple of other questions:
> 
> > the AK/SK change
> 
> what "AK / SK" stand for here?
AWS access key/secret key 
> > When I manually change the connector, the status begins in failed
> 
> That's interesting, I think the expected behavior of a connector is to continue to be in `RUNNING` state unless the credentials are invalid.
Sorry, yes they start in running on the initial resource creation, but after the TTL for the AK/SK creds ends and they are invalid then they stay in failed state until manually changed.
> But yeah overall I don't think we specifically tested the credential rotation workflow for connectors so we might want to test it on our side too.
That would be great. We've been discussing the best way to manage this somehow as we're using vault to manage creds in the terraform pipeline build but we'll need to make sure that if we use the same method to update the creds that the cred update process is solid from TF-perspective.
Ideally we would have another mechanism(thinking possibly lambda/k8s cronjob as a work-around) that isnt tied to connector/topic/etc resource creation for rotation but I know your team is already really busy with ksql/sr mgmt for terraform(saw a few ksql updates on api-side... exciting :) ).
 
Ill also let you know once ive had a chance to test on the 1.1.0 version to see if there was something there that I missed.

**Comment by nick-osborn** [comment]
^Sorry... trying to figure out the best way to format this

**Comment by linouk23** [comment]
Based on [this code snippet](https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/resource_connector.go#L267) it doesn't look like `1.1.0` support updates for sensitive attributes in `config_sensitive` block so we'll definitely need to update a source code.

Luckily, the change seems to be pretty simple so I might be able to test out a change and ship it in our new release shortly.

**Comment by nick-osborn** [comment]
Thanks so much for digging in and finding that Kostya! I hadnt yet had a chance to test it out but ill hold off until the new change comes up since you were able to verify.

**Comment by linouk23** [comment]
@nick-osborn we've just released `1.2.0` that hopefully should fix the issue, could you test whether it helps?

**Comment by nick-osborn** [comment]
Will do, thanks!

**Comment by nick-osborn** [comment]
@linouk23 This is fixed! I did a manual break and then pushed new creds with Terraform 1.2 to fix and it worked as expected. Thanks Kostya
