### ISSUE TITLE
Kafka ACL Fails to Read after some time without Changes

### ISSUE THREAD

**Issue by FischlerA** [confluentinc/terraform-provider-confluent#88]
We recently started using the terraform provider an are currently creating some ServiceAccounts, ApiKeys and ACLs through terraform.

However we are currently facing the issue, that the ACLs suddenly can't be read anymore some time after creation
Even without any changes to the terraform code.
We get the following error

The ClusterId and Endpoint have been replaced in the following error log.

```
╷
│ Error: error reading Kafka ACLs: Get "[https://xxx.eu-central-1.aws.confluent.cloud:443/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC"](https://xxx.%2A%2A%2A.aws.confluent.cloud/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC%22): GET [https://xxx.eu-central-1.aws.confluent.cloud:443/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC](https://xxx.%2A%2A%2A.aws.confluent.cloud/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC) giving up after 5 attempt(s): Get "[https://xxx.eu-central-1.aws.confluent.cloud:443/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC"](https://xxx.%2A%2A%2A.aws.confluent.cloud/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC%22): http: server gave HTTP response to HTTPS client
│ 
│   with confluent_kafka_acl.allow-write-vti-topics,
│   on vti-ams-credentials.tf line 33, in resource "confluent_kafka_acl" "allow-write-vti-topics":
│   33: resource "confluent_kafka_acl" "allow-write-vti-topics" {
│ 
╵
```

For Some Reason the ':' in the username as well as the host suddenly contain a 'MISSING'
The terraform statefile contains the correct values.

**Comment by linouk23** [comment]
@FischlerA thanks for opening an issue!

I'm a little bit confused about

> `?host=%!A(MISSING)` and `User%!A(MISSING)832913`

Is that something you updated as well (similar to `clusterId / endpoint`?)?

It'd be great if you could share TF definition of that `confluent_kafka_acl.allow-write-vti-topics` instance and we'd be interested to see TF logs at `cflt-tf-access@confluent.io` (if you could redact all the sensitive data).
```
# https://www.terraform.io/internals/debugging
$ export TF_LOG=trace
$ export TF_LOG_PATH="./logs.txt"
$ terraform plan
```

**Comment by FischlerA** [comment]
> ?host=%!A(MISSING) and User%!A(MISSING)832913

No these values have not been updated, but those are the values causing us issues.

If i replace them with proper values (host=* and User:832913) i can send a request via postman just fine and get an answer if i use appropriate credentials,

I also checked the statefile and there it all looks good to me, the values are properly set.

And here is the definition of the ACL

```
resource "confluent_kafka_acl" "allow-write-vti-topics" {
  kafka_cluster {
    id = var.confluent_cloud_kafka_cluster_id
  }
  resource_type = "TOPIC"
  resource_name = "SomeTopic"
  pattern_type  = "PREFIXED"
  principal     = "User:${confluent_service_account.ams-vti-push-access.id}"
  host          = "*"
  operation     = "WRITE"
  permission    = "ALLOW"
  rest_endpoint = data.confluent_kafka_cluster.kafka-cluster.rest_endpoint
  credentials {
    key    = confluent_api_key.terraform-cluster-manager-kafka-api-key.id
    secret = confluent_api_key.terraform-cluster-manager-kafka-api-key.secret
  }
}
```

I am unable to access the terraform logs at this moment but will send them as soon as i get access.

**Comment by FischlerA** [comment]
I know this probably won't help a lot but the confusing thing for me is, how the error occurs without any changes:
We are running terraform in Azure DevOps Pipelines, the first stage is irrelevant as it is not terraform, the seconds stage is the creation of a terraform plan.

As you can see it the same commitId running both times, the first time it worked and this was after the acl was alredy created but then about 2h 30m later the second run fails during the terraform plan even though there were no changes.

![image](https://user-images.githubusercontent.com/51916108/186834264-1cce72d3-2486-4a3e-8d49-943ef9c671ab.png)

**Comment by linouk23** [comment]
Thanks for the provided info!

While we're waiting for logs, could you double check that `principal` attribute equals to `"User:sa-abc123"` in TF state (and not `"User:832913"`).

**Comment by linouk23** [comment]
Speaking about `%!A(MISSING)` these 2 questions seems relevant:

* https://stackoverflow.com/questions/17157836/gae-go-user-service-login-url-contains-amissing
* https://stackoverflow.com/questions/24661862/url-escaping-producing-amissing-instead-of-3a

Namely,
```
Too few arguments: %!verb(MISSING)
  Printf("hi%d"):            hi %!d(MISSING)
```
🤔

**Comment by FischlerA** [comment]
> Thanks for the provided info!
> 
> While we're waiting for logs, could you double check that `principal` attribute equals to `"User:sa-abc123"` (basically that it starts with `"User:sa-..."`) in TF state (and not `"User:832913"`).

I just send you the log file via email. 
And yes i can confirm the terraform state contains the principal as "User:sa..." and not the number.

We recreate our Environments everyday and so all the resources were recreated as well. 
Once again the creation worked just fine and further runs worked as well but the issue still occurred after about 2 hours, and now we get the same error as yesterday and again without any changes to the terraform code. So it's not a one of occurrence.

**Comment by linouk23** [comment]
Did you use `cflt-tf-access@confluent.io`? I haven't received it yet, and I checked `spam` folder as well.

**Comment by FischlerA** [comment]
> Did you use `cflt-tf-access@confluent.io`? I haven't received it yet, and I checked `spam` folder as well.

Yes i did 
![image](https://user-images.githubusercontent.com/51916108/186879962-4b60408f-d54c-4ed6-a507-2a385554b694.png)

**Comment by linouk23** [comment]
Hmm interesting, could you also forward it to `klinou+debug@confluent.io`?

**Comment by linouk23** [comment]
Received the forwarded email, thanks!

**Comment by linouk23** [comment]
@FischlerA 

I've been thinking about this issue recently.

One of the potential issues could be the fact that not all brokers have been synced (so let's say 1 of the brokers is up-to-date but the other is out of sync and since we're using round robin your request might have been routed to #2 if that makes sense). Could you confirm you can still see the issue after like an hour after ACL creation or something?

**Comment by FischlerA** [comment]
To be honest, we haven't tried it since i opened this issue as the solution didn't seem reliable, so we had to use another solution.
We probably won't be revisiting the terraform provider for the next few month, and since we seem to be the only ones facing this error the issue can be closed if you want.

**Comment by linouk23** [comment]
> Could you confirm you can still see the issue after like an hour after ACL creation or something?

I could see that in one of your previous messages in this thread you mentioned:

> As you can see it the same commitId running both times, the first time it worked and this was after the acl was alredy created but then about **2h 30m** later the second run fails during the terraform plan even though there were no changes.

Let's keep it open for one more month to see if someone else runs into this issue 👌

**Comment by mps021** [comment]
I have been facing the issue, while trying to create an ACL rule over the confluent cloud, at times it works and at times it is miss for a certain period. I am not sure what is causing this ? 
In addition to this it throws 401 unauthorised.

**Comment by linouk23** [comment]
@mps021 it looks like your error is slightly difference, the author of this issue reported `http: server gave HTTP response to HTTPS client` error:
```
Error: error reading Kafka ACLs: Get "[https://xxx.eu-central-1.aws.confluent.cloud:443/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC"](https://xxx.%2A%2A%2A.aws.confluent.cloud/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC%22): GET [https://xxx.eu-central-1.aws.confluent.cloud:443/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC](https://xxx.%2A%2A%2A.aws.confluent.cloud/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC) giving up after 5 attempt(s): Get "[https://xxx.eu-central-1.aws.confluent.cloud:443/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC"](https://xxx.%2A%2A%2A.aws.confluent.cloud/kafka/v3/clusters/yyy/acls?host=%!A(MISSING)&operation=WRITE&pattern_type=PREFIXED&permission=ALLOW&principal=User%!A(MISSING)832913&resource_name=SomeTopic&resource_type=TOPIC%22): http: server gave HTTP response to HTTPS client
```

Could you double check you provided Kafka API Key & Kafka API Secret in either `credentials` block of target `confluent_kafka_acl` resource or in `providers` block as specified [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs#example-usage)?

**Comment by linouk23** [comment]
@FischlerA there's some more information about this issue.

2 users [reported](https://confluentcommunity.slack.com/archives/C02JJ23HZD3/p1674622569265029) a similar issue on Community Slack. Their findings are:


> I’ve had that in our setup but always chocked it up to our networking (runs fine from our ci/cd server, just not locally)

> Thanks for the pointer, it appears to be networking related. It works when tested locally, but the failure is happening from our GitHub runners.

**Comment by linouk23** [comment]
OK so it looks like the issue has been happening on CI / CD pipelines like _Azure DevOps Pipelines_ and _GitHub Actions_. After I searched for `""%!A(MISSING)" github actions"` I could find [this comment](https://github.com/gruntwork-io/terratest/issues/706#issuecomment-733495166):

> Assuming you are using https://github.com/hashicorp/setup-terraform to setup terraform in your github action, you need to configure it with `terraform_wrapper: false`. The wrapper that it installs by default is designed for direct use in the github action, and formats the output in a way that can be consumed in an action to feedforward the parameters. This behavior isn't supported in terratest, so you want to ensure the raw terraform binary gets bound to the `terraform` name in the `PATH` by avoiding the wrapper.

**Comment by FischlerA** [comment]
@linouk23 thanks for the update, we will look into this on our side.
