### ISSUE TITLE
Cluster creation fails with 403 Forbidden

### ISSUE THREAD

**Issue by ppennanen** [confluentinc/terraform-provider-confluent#89]
When creating a basic Kafka cluster, creation of the cluster fails with the message:

```
Error: error creating Kafka Cluster "offerta-test": 403 Forbidden: Forbidden Access
with module.kafka.confluent_kafka_cluster.cluster
on ../modules/kafka_cluster/cluster.tf line 5, in resource "confluent_kafka_cluster" "cluster":
resource "confluent_kafka_cluster" "cluster" {
```

The provider is configured to use an API key for a service account with the `OrganizationAdmin` role. A Confluent environment and several service accounts are created, which indicates that key and role binding work as expected.

The relevant code: 

```terraform
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.2.0"
    }
  }
}

resource "confluent_environment" "environment" {
  display_name = "test-environment"
}

resource "confluent_kafka_cluster" "cluster" {
  display_name = "test-cluster"
  availability = "SINGLE_ZONE"
  cloud        = "AZURE"
  region       = "northeurope"
  basic {}
  environment {
    id = confluent_environment.environment.id
  }
}
```

Is this a misconfiguration or a bug? I will be grateful for any help here :-)

**Comment by linouk23** [comment]
Thanks for opening an issue!

Could you share the configuration for your TF module as well? I can see
```
module.kafka.confluent_kafka_cluster.cluster
 ../modules/kafka_cluster/cluster.tf
```

`403` might also represent `404` so might be a good idea to double check `environment.id`.

**Comment by linouk23** [comment]
cc @ppennanen

**Comment by ppennanen** [comment]
I shared the real error message and simplified example code, but you found the source of the error anyway.

In the actual module I passed in a variable with an environment name to the `confluent_kafka_cluster` resource, rather than the `id` of the `confluent_environment`.
