### ISSUE TITLE
Service Account - 409 Conflict: Service name is already in use.

### ISSUE THREAD

**Issue by rogerioefonseca** [confluentinc/terraform-provider-confluent#92]
While testing some scenarios in my sandbox environment with Terraform, I removed a cluster that was manually created to recreate it via terraform.
While creating the new cluster, TF triggered an error related to a service account that already exists:

`##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
│ Error: error creating Service Account "cloudops-sandbox": 409 Conflict: Service name is already in use.
│ 
│   with module.confluentcloud_kafka_cluster.confluent_service_account_v2.app-manager,
│   on .terraform/modules/confluentcloud_kafka_cluster/main.tf line 53, in resource "confluent_service_account_v2" "app-manager":
│   53: resource "confluent_service_account_v2" "app-manager" {
`

I tried then to enter the Confluent Web interface and delete it from there, but I could not find a delete button or something.
![image](https://user-images.githubusercontent.com/17765109/187933925-8f22f4f9-2895-4729-828c-67aaa8cb11cf.png)

Fortunately, I was able to remove it using `confluent cli`
![image](https://user-images.githubusercontent.com/17765109/187934913-6a7a0181-bb5b-4db8-a9ea-5763f3571395.png)

I'm listing here 2 points:
* I'm Not sure if I made something wrong or if it is by design, but I was not able to delete the service-account via interface
* I believe that the best behavior for the terraform provider in the case above should be to check if the resource exists in the cloud and not exists in the TFSTATE and if YES print it's id and resource name so them I cam import it.

**Comment by linouk23** [comment]
👋 @rogerioefonseca, thanks for creating an issue!

> I was not able to delete the service-account via interface

I notified our UI team about this weird limitation.

> I believe that the best behavior for the terraform provider in the case above should be to check if the resource exists in the cloud and not exists in the TFSTATE and if YES print it's id and resource name so them I cam import it.

This ask looks similar to #28 and #48 and TLDR is
> we looked at other TF Provider and figured most of them explicitly return a similar error instead of trying to check whether existing remote object matches the one a user wants to create so we'll likely continue to return an error too: `409 Conflict: Service name is already in use.`

**Comment by rogerioefonseca** [comment]
> 👋 @rogerioefonseca, thanks for creating an issue!
> 
> 
> 
> > I was not able to delete the service-account via interface
> 
> 
> 
> I notified our UI team about this limitation.
> 
> 
> 
> > I believe that the best behavior for the terraform provider in the case above should be to check if the resource exists in the cloud and not exists in the TFSTATE and if YES print it's id and resource name so them I cam import it.
> 
> 
> 
> This ask looks similar to #28 and #48 and TLDR is
> 
> > we looked at other TF Provider and figured most of them explicitly return a similar error instead of trying to check whether existing remote object matches the one a user wants to create so we'll likely continue to return an error too: `409 Conflict: Service name is already in use.`

Fair enough!
Thanks!!
