### ISSUE TITLE
terraform init fails with confluent provider with specific folder structure

### ISSUE THREAD

**Issue by spin9** [confluentinc/terraform-provider-confluent#95]
Hi,
I am trying to setup my confluent terraform project with specific folder structure.
\terraform-confluent-kafka\
                                           environments\
                                                                  \dev\
                                                                      main.tf
                                                                      terraform.tfvars
                                                                      variables.tf
                                                                   \uat
                                                                   \prod
                                           topics.tf
                                           variables.tf                        
                         

I am getting following error. The folder structure works with Azure "azurerm" provider.

`Initializing modules...
- cc in ..\..

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/confluent...
- Finding confluentinc/confluent versions matching "1.4.0"...
- Installing confluentinc/confluent v1.4.0...
- Installed confluentinc/confluent v1.4.0 (signed by a HashiCorp partner, key ID D4A2B1EDB0EC0C8E)

╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/confluent: provider registry
│ registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/confluent
│
│ Did you intend to use confluentinc/confluent? If so, you must specify that source address in each module which
│ requires that provider. To see which modules are currently depending on hashicorp/confluent, run the following
│ command:
│     terraform providers`

terraform providers command shows this 
`Providers required by configuration:
.
├── provider[registry.terraform.io/confluentinc/confluent] 1.4.0
├── provider[registry.terraform.io/hashicorp/confluent]
└── module.cc
    └── provider[registry.terraform.io/hashicorp/confluent]`

This is what I have in my main.tf file

`# Configure the Confluent Provider
terraform {
  required_providers {
    azurerm = {
      source  = "confluentinc/confluent"
      version = "1.4.0"
    }
  }
}

provider "confluent" {
  kafka_rest_endpoint = var.kafka_rest_endpoint        # optionally use KAFKA_REST_ENDPOINT env var 
  kafka_api_key       = var.kafka_api_key              # optionally use KAFKA_API_KEY env var
  kafka_api_secret    = var.kafka_api_secret           # optionally use KAFKA_API_SECRET env var
}

module "cc" {
  source = "../.."
  
  kafka_cluster_id                  = var.kafka_cluster_id
  confluent_cloud_environment_id    = var.confluent_cloud_environment_id
  data_center                       = var.data_center
  environment_instance              = var.environment_instance

}`

![Folder Structure](https://user-images.githubusercontent.com/105332710/188327250-716f06a8-9268-41e4-bf1e-3d3f5b74661f.PNG)
[main.tf.txt](https://github.com/confluentinc/terraform-provider-confluent/files/9485239/main.tf.txt)

**Comment by linouk23** [comment]
@spin9 thanks for creating an issue!

Could you double check whether https://github.com/confluentinc/terraform-provider-confluentcloud/issues/20#issuecomment-1011833161 helps with your question?

**Comment by spin9** [comment]
It doesn't work for me even adding in the module.

`terraform {
  required_providers {
    azurerm = {
      source  = "confluentinc/confluent"
      version = "1.4.0"
    }
  }
}

provider "confluent" {
  kafka_rest_endpoint = var.kafka_rest_endpoint        # optionally use KAFKA_REST_ENDPOINT env var 
  kafka_api_key       = var.kafka_api_key              # optionally use KAFKA_API_KEY env var
  kafka_api_secret    = var.kafka_api_secret           # optionally use KAFKA_API_SECRET env var
}`

**Comment by spin9** [comment]
@linouk23 Thanks for quick response. It works now after explicitly adding the "**required_providers**" block in the module
