### ISSUE TITLE
confluent_kafka_topic resource failing to apply a second time without changes

### ISSUE THREAD

**Issue by laurence-hubbard** [confluentinc/terraform-provider-confluent#98]
Getting this error:

> Error: error updating Kafka Topic "XXX": "YYY" topic setting is read-only and cannot be updated.

Whenever any of the following settings are defined in the `config` block of the `confluent_kafka_topic` resource and then you run apply twice in a row without making any changes:
* "compression.type"
* "connection.failed.authentication.delay.ms"
* "default.replication.factor"
* "file.delete.delay.ms"
* "flush.messages"
* "flush.ms"
* "group.max.session.timeout.ms"
* "index.interval.bytes"
* "message.downconversion.enable"
* "message.format.version"
* "min.cleanable.dirty.ratio"
* "num.partitions"
* "offsets.retention.minutes"
* "preallocate"
* "segment.index.bytes"
* "segment.jitter.ms"
* "unclean.leader.election.enable"

Using this provider version:
```
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.2.0"
    }
```

**Comment by linouk23** [comment]
@laurence-hubbard thanks for creating an issue!

That's expected -- see [Confluent Cloud Cluster and Topic Configuration Settings](https://docs.confluent.io/cloud/current/clusters/broker-config.html#custom-topic-settings-for-all-cluster-types) for more details.
![image](https://user-images.githubusercontent.com/5459870/188765540-cd2be965-4bfd-411b-8d8a-c4a72ee97753.png)
